// This is generated code. DO NOT EDIT
package main

import (
	"gioui.org/gesture"
	. "golang.org/x/exp/shiny/materialdesign/icons"
)

var allIndices []int

func init() {
	allIndices = make([]int, len(allEntries))
	for i := 0; i < len(allIndices); i++ {
		allIndices[i] = i
	}
}

var _g0 = gesture.Click{}

var allEntries = [...]iconEntry{
	{"AVAV Timer", "avavtimer", "AVAVTimer", mi(AVAVTimer), _g0},
	{"AV Add To Queue", "avaddtoqueue", "AVAddToQueue", mi(AVAddToQueue), _g0},
	{"AV Airplay", "avairplay", "AVAirplay", mi(AVAirplay), _g0},
	{"AV Album", "avalbum", "AVAlbum", mi(AVAlbum), _g0},
	{"AV Art Track", "avarttrack", "AVArtTrack", mi(AVArtTrack), _g0},
	{"AV Branding Watermark", "avbrandingwatermark", "AVBrandingWatermark", mi(AVBrandingWatermark), _g0},
	{"AV Call To Action", "avcalltoaction", "AVCallToAction", mi(AVCallToAction), _g0},
	{"AV Closed Caption", "avclosedcaption", "AVClosedCaption", mi(AVClosedCaption), _g0},
	{"AV Equalizer", "avequalizer", "AVEqualizer", mi(AVEqualizer), _g0},
	{"AV Explicit", "avexplicit", "AVExplicit", mi(AVExplicit), _g0},
	{"AV Fast Forward", "avfastforward", "AVFastForward", mi(AVFastForward), _g0},
	{"AV Fast Rewind", "avfastrewind", "AVFastRewind", mi(AVFastRewind), _g0},
	{"AV Featured Play List", "avfeaturedplaylist", "AVFeaturedPlayList", mi(AVFeaturedPlayList), _g0},
	{"AV Featured Video", "avfeaturedvideo", "AVFeaturedVideo", mi(AVFeaturedVideo), _g0},
	{"AV Fiber DVR", "avfiberdvr", "AVFiberDVR", mi(AVFiberDVR), _g0},
	{"AV Fiber Manual Record", "avfibermanualrecord", "AVFiberManualRecord", mi(AVFiberManualRecord), _g0},
	{"AV Fiber New", "avfibernew", "AVFiberNew", mi(AVFiberNew), _g0},
	{"AV Fiber Pin", "avfiberpin", "AVFiberPin", mi(AVFiberPin), _g0},
	{"AV Fiber Smart Record", "avfibersmartrecord", "AVFiberSmartRecord", mi(AVFiberSmartRecord), _g0},
	{"AV Forward 10", "avforward10", "AVForward10", mi(AVForward10), _g0},
	{"AV Forward 30", "avforward30", "AVForward30", mi(AVForward30), _g0},
	{"AV Forward 5", "avforward5", "AVForward5", mi(AVForward5), _g0},
	{"AV Games", "avgames", "AVGames", mi(AVGames), _g0},
	{"AVHD", "avhd", "AVHD", mi(AVHD), _g0},
	{"AV Hearing", "avhearing", "AVHearing", mi(AVHearing), _g0},
	{"AV High Quality", "avhighquality", "AVHighQuality", mi(AVHighQuality), _g0},
	{"AV Library Add", "avlibraryadd", "AVLibraryAdd", mi(AVLibraryAdd), _g0},
	{"AV Library Books", "avlibrarybooks", "AVLibraryBooks", mi(AVLibraryBooks), _g0},
	{"AV Library Music", "avlibrarymusic", "AVLibraryMusic", mi(AVLibraryMusic), _g0},
	{"AV Loop", "avloop", "AVLoop", mi(AVLoop), _g0},
	{"AV Mic", "avmic", "AVMic", mi(AVMic), _g0},
	{"AV Mic None", "avmicnone", "AVMicNone", mi(AVMicNone), _g0},
	{"AV Mic Off", "avmicoff", "AVMicOff", mi(AVMicOff), _g0},
	{"AV Movie", "avmovie", "AVMovie", mi(AVMovie), _g0},
	{"AV Music Video", "avmusicvideo", "AVMusicVideo", mi(AVMusicVideo), _g0},
	{"AV New Releases", "avnewreleases", "AVNewReleases", mi(AVNewReleases), _g0},
	{"AV Not Interested", "avnotinterested", "AVNotInterested", mi(AVNotInterested), _g0},
	{"AV Note", "avnote", "AVNote", mi(AVNote), _g0},
	{"AV Pause", "avpause", "AVPause", mi(AVPause), _g0},
	{"AV Pause Circle Filled", "avpausecirclefilled", "AVPauseCircleFilled", mi(AVPauseCircleFilled), _g0},
	{"AV Pause Circle Outline", "avpausecircleoutline", "AVPauseCircleOutline", mi(AVPauseCircleOutline), _g0},
	{"AV Play Arrow", "avplayarrow", "AVPlayArrow", mi(AVPlayArrow), _g0},
	{"AV Play Circle Filled", "avplaycirclefilled", "AVPlayCircleFilled", mi(AVPlayCircleFilled), _g0},
	{"AV Play Circle Outline", "avplaycircleoutline", "AVPlayCircleOutline", mi(AVPlayCircleOutline), _g0},
	{"AV Playlist Add", "avplaylistadd", "AVPlaylistAdd", mi(AVPlaylistAdd), _g0},
	{"AV Playlist Add Check", "avplaylistaddcheck", "AVPlaylistAddCheck", mi(AVPlaylistAddCheck), _g0},
	{"AV Playlist Play", "avplaylistplay", "AVPlaylistPlay", mi(AVPlaylistPlay), _g0},
	{"AV Queue", "avqueue", "AVQueue", mi(AVQueue), _g0},
	{"AV Queue Music", "avqueuemusic", "AVQueueMusic", mi(AVQueueMusic), _g0},
	{"AV Queue Play Next", "avqueueplaynext", "AVQueuePlayNext", mi(AVQueuePlayNext), _g0},
	{"AV Radio", "avradio", "AVRadio", mi(AVRadio), _g0},
	{"AV Recent Actors", "avrecentactors", "AVRecentActors", mi(AVRecentActors), _g0},
	{"AV Remove From Queue", "avremovefromqueue", "AVRemoveFromQueue", mi(AVRemoveFromQueue), _g0},
	{"AV Repeat", "avrepeat", "AVRepeat", mi(AVRepeat), _g0},
	{"AV Repeat One", "avrepeatone", "AVRepeatOne", mi(AVRepeatOne), _g0},
	{"AV Replay", "avreplay", "AVReplay", mi(AVReplay), _g0},
	{"AV Replay 10", "avreplay10", "AVReplay10", mi(AVReplay10), _g0},
	{"AV Replay 30", "avreplay30", "AVReplay30", mi(AVReplay30), _g0},
	{"AV Replay 5", "avreplay5", "AVReplay5", mi(AVReplay5), _g0},
	{"AV Shuffle", "avshuffle", "AVShuffle", mi(AVShuffle), _g0},
	{"AV Skip Next", "avskipnext", "AVSkipNext", mi(AVSkipNext), _g0},
	{"AV Skip Previous", "avskipprevious", "AVSkipPrevious", mi(AVSkipPrevious), _g0},
	{"AV Slow Motion Video", "avslowmotionvideo", "AVSlowMotionVideo", mi(AVSlowMotionVideo), _g0},
	{"AV Snooze", "avsnooze", "AVSnooze", mi(AVSnooze), _g0},
	{"AV Sort By Alpha", "avsortbyalpha", "AVSortByAlpha", mi(AVSortByAlpha), _g0},
	{"AV Stop", "avstop", "AVStop", mi(AVStop), _g0},
	{"AV Subscriptions", "avsubscriptions", "AVSubscriptions", mi(AVSubscriptions), _g0},
	{"AV Subtitles", "avsubtitles", "AVSubtitles", mi(AVSubtitles), _g0},
	{"AV Surround Sound", "avsurroundsound", "AVSurroundSound", mi(AVSurroundSound), _g0},
	{"AV Video Call", "avvideocall", "AVVideoCall", mi(AVVideoCall), _g0},
	{"AV Video Label", "avvideolabel", "AVVideoLabel", mi(AVVideoLabel), _g0},
	{"AV Video Library", "avvideolibrary", "AVVideoLibrary", mi(AVVideoLibrary), _g0},
	{"AV Videocam", "avvideocam", "AVVideocam", mi(AVVideocam), _g0},
	{"AV Videocam Off", "avvideocamoff", "AVVideocamOff", mi(AVVideocamOff), _g0},
	{"AV Volume Down", "avvolumedown", "AVVolumeDown", mi(AVVolumeDown), _g0},
	{"AV Volume Mute", "avvolumemute", "AVVolumeMute", mi(AVVolumeMute), _g0},
	{"AV Volume Off", "avvolumeoff", "AVVolumeOff", mi(AVVolumeOff), _g0},
	{"AV Volume Up", "avvolumeup", "AVVolumeUp", mi(AVVolumeUp), _g0},
	{"AV Web", "avweb", "AVWeb", mi(AVWeb), _g0},
	{"AV Web Asset", "avwebasset", "AVWebAsset", mi(AVWebAsset), _g0},
	{"Action 3 D Rotation", "action3drotation", "Action3DRotation", mi(Action3DRotation), _g0},
	{"Action Accessibility", "actionaccessibility", "ActionAccessibility", mi(ActionAccessibility), _g0},
	{"Action Accessible", "actionaccessible", "ActionAccessible", mi(ActionAccessible), _g0},
	{"Action Account Balance", "actionaccountbalance", "ActionAccountBalance", mi(ActionAccountBalance), _g0},
	{"Action Account Balance Wallet", "actionaccountbalancewallet", "ActionAccountBalanceWallet", mi(ActionAccountBalanceWallet), _g0},
	{"Action Account Box", "actionaccountbox", "ActionAccountBox", mi(ActionAccountBox), _g0},
	{"Action Account Circle", "actionaccountcircle", "ActionAccountCircle", mi(ActionAccountCircle), _g0},
	{"Action Add Shopping Cart", "actionaddshoppingcart", "ActionAddShoppingCart", mi(ActionAddShoppingCart), _g0},
	{"Action Alarm", "actionalarm", "ActionAlarm", mi(ActionAlarm), _g0},
	{"Action Alarm Add", "actionalarmadd", "ActionAlarmAdd", mi(ActionAlarmAdd), _g0},
	{"Action Alarm Off", "actionalarmoff", "ActionAlarmOff", mi(ActionAlarmOff), _g0},
	{"Action Alarm On", "actionalarmon", "ActionAlarmOn", mi(ActionAlarmOn), _g0},
	{"Action All Out", "actionallout", "ActionAllOut", mi(ActionAllOut), _g0},
	{"Action Android", "actionandroid", "ActionAndroid", mi(ActionAndroid), _g0},
	{"Action Announcement", "actionannouncement", "ActionAnnouncement", mi(ActionAnnouncement), _g0},
	{"Action Aspect Ratio", "actionaspectratio", "ActionAspectRatio", mi(ActionAspectRatio), _g0},
	{"Action Assessment", "actionassessment", "ActionAssessment", mi(ActionAssessment), _g0},
	{"Action Assignment", "actionassignment", "ActionAssignment", mi(ActionAssignment), _g0},
	{"Action Assignment Ind", "actionassignmentind", "ActionAssignmentInd", mi(ActionAssignmentInd), _g0},
	{"Action Assignment Late", "actionassignmentlate", "ActionAssignmentLate", mi(ActionAssignmentLate), _g0},
	{"Action Assignment Return", "actionassignmentreturn", "ActionAssignmentReturn", mi(ActionAssignmentReturn), _g0},
	{"Action Assignment Returned", "actionassignmentreturned", "ActionAssignmentReturned", mi(ActionAssignmentReturned), _g0},
	{"Action Assignment Turned In", "actionassignmentturnedin", "ActionAssignmentTurnedIn", mi(ActionAssignmentTurnedIn), _g0},
	{"Action Autorenew", "actionautorenew", "ActionAutorenew", mi(ActionAutorenew), _g0},
	{"Action Backup", "actionbackup", "ActionBackup", mi(ActionBackup), _g0},
	{"Action Book", "actionbook", "ActionBook", mi(ActionBook), _g0},
	{"Action Bookmark", "actionbookmark", "ActionBookmark", mi(ActionBookmark), _g0},
	{"Action Bookmark Border", "actionbookmarkborder", "ActionBookmarkBorder", mi(ActionBookmarkBorder), _g0},
	{"Action Bug Report", "actionbugreport", "ActionBugReport", mi(ActionBugReport), _g0},
	{"Action Build", "actionbuild", "ActionBuild", mi(ActionBuild), _g0},
	{"Action Cached", "actioncached", "ActionCached", mi(ActionCached), _g0},
	{"Action Camera Enhance", "actioncameraenhance", "ActionCameraEnhance", mi(ActionCameraEnhance), _g0},
	{"Action Card Giftcard", "actioncardgiftcard", "ActionCardGiftcard", mi(ActionCardGiftcard), _g0},
	{"Action Card Membership", "actioncardmembership", "ActionCardMembership", mi(ActionCardMembership), _g0},
	{"Action Card Travel", "actioncardtravel", "ActionCardTravel", mi(ActionCardTravel), _g0},
	{"Action Change History", "actionchangehistory", "ActionChangeHistory", mi(ActionChangeHistory), _g0},
	{"Action Check Circle", "actioncheckcircle", "ActionCheckCircle", mi(ActionCheckCircle), _g0},
	{"Action Chrome Reader Mode", "actionchromereadermode", "ActionChromeReaderMode", mi(ActionChromeReaderMode), _g0},
	{"Action Class", "actionclass", "ActionClass", mi(ActionClass), _g0},
	{"Action Code", "actioncode", "ActionCode", mi(ActionCode), _g0},
	{"Action Compare Arrows", "actioncomparearrows", "ActionCompareArrows", mi(ActionCompareArrows), _g0},
	{"Action Copyright", "actioncopyright", "ActionCopyright", mi(ActionCopyright), _g0},
	{"Action Credit Card", "actioncreditcard", "ActionCreditCard", mi(ActionCreditCard), _g0},
	{"Action DNS", "actiondns", "ActionDNS", mi(ActionDNS), _g0},
	{"Action Dashboard", "actiondashboard", "ActionDashboard", mi(ActionDashboard), _g0},
	{"Action Date Range", "actiondaterange", "ActionDateRange", mi(ActionDateRange), _g0},
	{"Action Delete", "actiondelete", "ActionDelete", mi(ActionDelete), _g0},
	{"Action Delete Forever", "actiondeleteforever", "ActionDeleteForever", mi(ActionDeleteForever), _g0},
	{"Action Description", "actiondescription", "ActionDescription", mi(ActionDescription), _g0},
	{"Action Done", "actiondone", "ActionDone", mi(ActionDone), _g0},
	{"Action Done All", "actiondoneall", "ActionDoneAll", mi(ActionDoneAll), _g0},
	{"Action Donut Large", "actiondonutlarge", "ActionDonutLarge", mi(ActionDonutLarge), _g0},
	{"Action Donut Small", "actiondonutsmall", "ActionDonutSmall", mi(ActionDonutSmall), _g0},
	{"Action Eject", "actioneject", "ActionEject", mi(ActionEject), _g0},
	{"Action Euro Symbol", "actioneurosymbol", "ActionEuroSymbol", mi(ActionEuroSymbol), _g0},
	{"Action Event", "actionevent", "ActionEvent", mi(ActionEvent), _g0},
	{"Action Event Seat", "actioneventseat", "ActionEventSeat", mi(ActionEventSeat), _g0},
	{"Action Exit To App", "actionexittoapp", "ActionExitToApp", mi(ActionExitToApp), _g0},
	{"Action Explore", "actionexplore", "ActionExplore", mi(ActionExplore), _g0},
	{"Action Extension", "actionextension", "ActionExtension", mi(ActionExtension), _g0},
	{"Action Face", "actionface", "ActionFace", mi(ActionFace), _g0},
	{"Action Favorite", "actionfavorite", "ActionFavorite", mi(ActionFavorite), _g0},
	{"Action Favorite Border", "actionfavoriteborder", "ActionFavoriteBorder", mi(ActionFavoriteBorder), _g0},
	{"Action Feedback", "actionfeedback", "ActionFeedback", mi(ActionFeedback), _g0},
	{"Action Find In Page", "actionfindinpage", "ActionFindInPage", mi(ActionFindInPage), _g0},
	{"Action Find Replace", "actionfindreplace", "ActionFindReplace", mi(ActionFindReplace), _g0},
	{"Action Fingerprint", "actionfingerprint", "ActionFingerprint", mi(ActionFingerprint), _g0},
	{"Action Flight Land", "actionflightland", "ActionFlightLand", mi(ActionFlightLand), _g0},
	{"Action Flight Takeoff", "actionflighttakeoff", "ActionFlightTakeoff", mi(ActionFlightTakeoff), _g0},
	{"Action Flip To Back", "actionfliptoback", "ActionFlipToBack", mi(ActionFlipToBack), _g0},
	{"Action Flip To Front", "actionfliptofront", "ActionFlipToFront", mi(ActionFlipToFront), _g0},
	{"Action GIF", "actiongif", "ActionGIF", mi(ActionGIF), _g0},
	{"Action G Translate", "actiongtranslate", "ActionGTranslate", mi(ActionGTranslate), _g0},
	{"Action Gavel", "actiongavel", "ActionGavel", mi(ActionGavel), _g0},
	{"Action Get App", "actiongetapp", "ActionGetApp", mi(ActionGetApp), _g0},
	{"Action Grade", "actiongrade", "ActionGrade", mi(ActionGrade), _g0},
	{"Action Group Work", "actiongroupwork", "ActionGroupWork", mi(ActionGroupWork), _g0},
	{"Action HTTP", "actionhttp", "ActionHTTP", mi(ActionHTTP), _g0},
	{"Action HTTPS", "actionhttps", "ActionHTTPS", mi(ActionHTTPS), _g0},
	{"Action Help", "actionhelp", "ActionHelp", mi(ActionHelp), _g0},
	{"Action Help Outline", "actionhelpoutline", "ActionHelpOutline", mi(ActionHelpOutline), _g0},
	{"Action Highlight Off", "actionhighlightoff", "ActionHighlightOff", mi(ActionHighlightOff), _g0},
	{"Action History", "actionhistory", "ActionHistory", mi(ActionHistory), _g0},
	{"Action Home", "actionhome", "ActionHome", mi(ActionHome), _g0},
	{"Action Hourglass Empty", "actionhourglassempty", "ActionHourglassEmpty", mi(ActionHourglassEmpty), _g0},
	{"Action Hourglass Full", "actionhourglassfull", "ActionHourglassFull", mi(ActionHourglassFull), _g0},
	{"Action Important Devices", "actionimportantdevices", "ActionImportantDevices", mi(ActionImportantDevices), _g0},
	{"Action Info", "actioninfo", "ActionInfo", mi(ActionInfo), _g0},
	{"Action Info Outline", "actioninfooutline", "ActionInfoOutline", mi(ActionInfoOutline), _g0},
	{"Action Input", "actioninput", "ActionInput", mi(ActionInput), _g0},
	{"Action Invert Colors", "actioninvertcolors", "ActionInvertColors", mi(ActionInvertColors), _g0},
	{"Action Label", "actionlabel", "ActionLabel", mi(ActionLabel), _g0},
	{"Action Label Outline", "actionlabeloutline", "ActionLabelOutline", mi(ActionLabelOutline), _g0},
	{"Action Language", "actionlanguage", "ActionLanguage", mi(ActionLanguage), _g0},
	{"Action Launch", "actionlaunch", "ActionLaunch", mi(ActionLaunch), _g0},
	{"Action Lightbulb Outline", "actionlightbulboutline", "ActionLightbulbOutline", mi(ActionLightbulbOutline), _g0},
	{"Action Line Style", "actionlinestyle", "ActionLineStyle", mi(ActionLineStyle), _g0},
	{"Action Line Weight", "actionlineweight", "ActionLineWeight", mi(ActionLineWeight), _g0},
	{"Action List", "actionlist", "ActionList", mi(ActionList), _g0},
	{"Action Lock", "actionlock", "ActionLock", mi(ActionLock), _g0},
	{"Action Lock Open", "actionlockopen", "ActionLockOpen", mi(ActionLockOpen), _g0},
	{"Action Lock Outline", "actionlockoutline", "ActionLockOutline", mi(ActionLockOutline), _g0},
	{"Action Loyalty", "actionloyalty", "ActionLoyalty", mi(ActionLoyalty), _g0},
	{"Action Mark Unread Mailbox", "actionmarkunreadmailbox", "ActionMarkUnreadMailbox", mi(ActionMarkUnreadMailbox), _g0},
	{"Action Motorcycle", "actionmotorcycle", "ActionMotorcycle", mi(ActionMotorcycle), _g0},
	{"Action Note Add", "actionnoteadd", "ActionNoteAdd", mi(ActionNoteAdd), _g0},
	{"Action Offline Pin", "actionofflinepin", "ActionOfflinePin", mi(ActionOfflinePin), _g0},
	{"Action Opacity", "actionopacity", "ActionOpacity", mi(ActionOpacity), _g0},
	{"Action Open In Browser", "actionopeninbrowser", "ActionOpenInBrowser", mi(ActionOpenInBrowser), _g0},
	{"Action Open In New", "actionopeninnew", "ActionOpenInNew", mi(ActionOpenInNew), _g0},
	{"Action Open With", "actionopenwith", "ActionOpenWith", mi(ActionOpenWith), _g0},
	{"Action Pageview", "actionpageview", "ActionPageview", mi(ActionPageview), _g0},
	{"Action Pan Tool", "actionpantool", "ActionPanTool", mi(ActionPanTool), _g0},
	{"Action Payment", "actionpayment", "ActionPayment", mi(ActionPayment), _g0},
	{"Action Perm Camera Mic", "actionpermcameramic", "ActionPermCameraMic", mi(ActionPermCameraMic), _g0},
	{"Action Perm Contact Calendar", "actionpermcontactcalendar", "ActionPermContactCalendar", mi(ActionPermContactCalendar), _g0},
	{"Action Perm Data Setting", "actionpermdatasetting", "ActionPermDataSetting", mi(ActionPermDataSetting), _g0},
	{"Action Perm Device Information", "actionpermdeviceinformation", "ActionPermDeviceInformation", mi(ActionPermDeviceInformation), _g0},
	{"Action Perm Identity", "actionpermidentity", "ActionPermIdentity", mi(ActionPermIdentity), _g0},
	{"Action Perm Media", "actionpermmedia", "ActionPermMedia", mi(ActionPermMedia), _g0},
	{"Action Perm Phone Msg", "actionpermphonemsg", "ActionPermPhoneMsg", mi(ActionPermPhoneMsg), _g0},
	{"Action Perm Scan Wi Fi", "actionpermscanwifi", "ActionPermScanWiFi", mi(ActionPermScanWiFi), _g0},
	{"Action Pets", "actionpets", "ActionPets", mi(ActionPets), _g0},
	{"Action Picture In Picture", "actionpictureinpicture", "ActionPictureInPicture", mi(ActionPictureInPicture), _g0},
	{"Action Picture In Picture Alt", "actionpictureinpicturealt", "ActionPictureInPictureAlt", mi(ActionPictureInPictureAlt), _g0},
	{"Action Play For Work", "actionplayforwork", "ActionPlayForWork", mi(ActionPlayForWork), _g0},
	{"Action Polymer", "actionpolymer", "ActionPolymer", mi(ActionPolymer), _g0},
	{"Action Power Settings New", "actionpowersettingsnew", "ActionPowerSettingsNew", mi(ActionPowerSettingsNew), _g0},
	{"Action Pregnant Woman", "actionpregnantwoman", "ActionPregnantWoman", mi(ActionPregnantWoman), _g0},
	{"Action Print", "actionprint", "ActionPrint", mi(ActionPrint), _g0},
	{"Action Query Builder", "actionquerybuilder", "ActionQueryBuilder", mi(ActionQueryBuilder), _g0},
	{"Action Question Answer", "actionquestionanswer", "ActionQuestionAnswer", mi(ActionQuestionAnswer), _g0},
	{"Action Receipt", "actionreceipt", "ActionReceipt", mi(ActionReceipt), _g0},
	{"Action Record Voice Over", "actionrecordvoiceover", "ActionRecordVoiceOver", mi(ActionRecordVoiceOver), _g0},
	{"Action Redeem", "actionredeem", "ActionRedeem", mi(ActionRedeem), _g0},
	{"Action Remove Shopping Cart", "actionremoveshoppingcart", "ActionRemoveShoppingCart", mi(ActionRemoveShoppingCart), _g0},
	{"Action Reorder", "actionreorder", "ActionReorder", mi(ActionReorder), _g0},
	{"Action Report Problem", "actionreportproblem", "ActionReportProblem", mi(ActionReportProblem), _g0},
	{"Action Restore", "actionrestore", "ActionRestore", mi(ActionRestore), _g0},
	{"Action Restore Page", "actionrestorepage", "ActionRestorePage", mi(ActionRestorePage), _g0},
	{"Action Room", "actionroom", "ActionRoom", mi(ActionRoom), _g0},
	{"Action Rounded Corner", "actionroundedcorner", "ActionRoundedCorner", mi(ActionRoundedCorner), _g0},
	{"Action Rowing", "actionrowing", "ActionRowing", mi(ActionRowing), _g0},
	{"Action Schedule", "actionschedule", "ActionSchedule", mi(ActionSchedule), _g0},
	{"Action Search", "actionsearch", "ActionSearch", mi(ActionSearch), _g0},
	{"Action Settings", "actionsettings", "ActionSettings", mi(ActionSettings), _g0},
	{"Action Settings Applications", "actionsettingsapplications", "ActionSettingsApplications", mi(ActionSettingsApplications), _g0},
	{"Action Settings Backup Restore", "actionsettingsbackuprestore", "ActionSettingsBackupRestore", mi(ActionSettingsBackupRestore), _g0},
	{"Action Settings Bluetooth", "actionsettingsbluetooth", "ActionSettingsBluetooth", mi(ActionSettingsBluetooth), _g0},
	{"Action Settings Brightness", "actionsettingsbrightness", "ActionSettingsBrightness", mi(ActionSettingsBrightness), _g0},
	{"Action Settings Cell", "actionsettingscell", "ActionSettingsCell", mi(ActionSettingsCell), _g0},
	{"Action Settings Ethernet", "actionsettingsethernet", "ActionSettingsEthernet", mi(ActionSettingsEthernet), _g0},
	{"Action Settings Input Antenna", "actionsettingsinputantenna", "ActionSettingsInputAntenna", mi(ActionSettingsInputAntenna), _g0},
	{"Action Settings Input Component", "actionsettingsinputcomponent", "ActionSettingsInputComponent", mi(ActionSettingsInputComponent), _g0},
	{"Action Settings Input Composite", "actionsettingsinputcomposite", "ActionSettingsInputComposite", mi(ActionSettingsInputComposite), _g0},
	{"Action Settings Input HDMI", "actionsettingsinputhdmi", "ActionSettingsInputHDMI", mi(ActionSettingsInputHDMI), _g0},
	{"Action Settings Input S Video", "actionsettingsinputsvideo", "ActionSettingsInputSVideo", mi(ActionSettingsInputSVideo), _g0},
	{"Action Settings Overscan", "actionsettingsoverscan", "ActionSettingsOverscan", mi(ActionSettingsOverscan), _g0},
	{"Action Settings Phone", "actionsettingsphone", "ActionSettingsPhone", mi(ActionSettingsPhone), _g0},
	{"Action Settings Power", "actionsettingspower", "ActionSettingsPower", mi(ActionSettingsPower), _g0},
	{"Action Settings Remote", "actionsettingsremote", "ActionSettingsRemote", mi(ActionSettingsRemote), _g0},
	{"Action Settings Voice", "actionsettingsvoice", "ActionSettingsVoice", mi(ActionSettingsVoice), _g0},
	{"Action Shop", "actionshop", "ActionShop", mi(ActionShop), _g0},
	{"Action Shop Two", "actionshoptwo", "ActionShopTwo", mi(ActionShopTwo), _g0},
	{"Action Shopping Basket", "actionshoppingbasket", "ActionShoppingBasket", mi(ActionShoppingBasket), _g0},
	{"Action Shopping Cart", "actionshoppingcart", "ActionShoppingCart", mi(ActionShoppingCart), _g0},
	{"Action Speaker Notes", "actionspeakernotes", "ActionSpeakerNotes", mi(ActionSpeakerNotes), _g0},
	{"Action Speaker Notes Off", "actionspeakernotesoff", "ActionSpeakerNotesOff", mi(ActionSpeakerNotesOff), _g0},
	{"Action Spellcheck", "actionspellcheck", "ActionSpellcheck", mi(ActionSpellcheck), _g0},
	{"Action Star Rate", "actionstarrate", "ActionStarRate", mi(ActionStarRate), _g0},
	{"Action Stars", "actionstars", "ActionStars", mi(ActionStars), _g0},
	{"Action Store", "actionstore", "ActionStore", mi(ActionStore), _g0},
	{"Action Subject", "actionsubject", "ActionSubject", mi(ActionSubject), _g0},
	{"Action Supervisor Account", "actionsupervisoraccount", "ActionSupervisorAccount", mi(ActionSupervisorAccount), _g0},
	{"Action Swap Horiz", "actionswaphoriz", "ActionSwapHoriz", mi(ActionSwapHoriz), _g0},
	{"Action Swap Vert", "actionswapvert", "ActionSwapVert", mi(ActionSwapVert), _g0},
	{"Action Swap Vertical Circle", "actionswapverticalcircle", "ActionSwapVerticalCircle", mi(ActionSwapVerticalCircle), _g0},
	{"Action System Update Alt", "actionsystemupdatealt", "ActionSystemUpdateAlt", mi(ActionSystemUpdateAlt), _g0},
	{"Action TOC", "actiontoc", "ActionTOC", mi(ActionTOC), _g0},
	{"Action Tab", "actiontab", "ActionTab", mi(ActionTab), _g0},
	{"Action Tab Unselected", "actiontabunselected", "ActionTabUnselected", mi(ActionTabUnselected), _g0},
	{"Action Theaters", "actiontheaters", "ActionTheaters", mi(ActionTheaters), _g0},
	{"Action Thumb Down", "actionthumbdown", "ActionThumbDown", mi(ActionThumbDown), _g0},
	{"Action Thumb Up", "actionthumbup", "ActionThumbUp", mi(ActionThumbUp), _g0},
	{"Action Thumbs Up Down", "actionthumbsupdown", "ActionThumbsUpDown", mi(ActionThumbsUpDown), _g0},
	{"Action Timeline", "actiontimeline", "ActionTimeline", mi(ActionTimeline), _g0},
	{"Action Today", "actiontoday", "ActionToday", mi(ActionToday), _g0},
	{"Action Toll", "actiontoll", "ActionToll", mi(ActionToll), _g0},
	{"Action Touch App", "actiontouchapp", "ActionTouchApp", mi(ActionTouchApp), _g0},
	{"Action Track Changes", "actiontrackchanges", "ActionTrackChanges", mi(ActionTrackChanges), _g0},
	{"Action Translate", "actiontranslate", "ActionTranslate", mi(ActionTranslate), _g0},
	{"Action Trending Down", "actiontrendingdown", "ActionTrendingDown", mi(ActionTrendingDown), _g0},
	{"Action Trending Flat", "actiontrendingflat", "ActionTrendingFlat", mi(ActionTrendingFlat), _g0},
	{"Action Trending Up", "actiontrendingup", "ActionTrendingUp", mi(ActionTrendingUp), _g0},
	{"Action Turned In", "actionturnedin", "ActionTurnedIn", mi(ActionTurnedIn), _g0},
	{"Action Turned In Not", "actionturnedinnot", "ActionTurnedInNot", mi(ActionTurnedInNot), _g0},
	{"Action Update", "actionupdate", "ActionUpdate", mi(ActionUpdate), _g0},
	{"Action Verified User", "actionverifieduser", "ActionVerifiedUser", mi(ActionVerifiedUser), _g0},
	{"Action View Agenda", "actionviewagenda", "ActionViewAgenda", mi(ActionViewAgenda), _g0},
	{"Action View Array", "actionviewarray", "ActionViewArray", mi(ActionViewArray), _g0},
	{"Action View Carousel", "actionviewcarousel", "ActionViewCarousel", mi(ActionViewCarousel), _g0},
	{"Action View Column", "actionviewcolumn", "ActionViewColumn", mi(ActionViewColumn), _g0},
	{"Action View Day", "actionviewday", "ActionViewDay", mi(ActionViewDay), _g0},
	{"Action View Headline", "actionviewheadline", "ActionViewHeadline", mi(ActionViewHeadline), _g0},
	{"Action View List", "actionviewlist", "ActionViewList", mi(ActionViewList), _g0},
	{"Action View Module", "actionviewmodule", "ActionViewModule", mi(ActionViewModule), _g0},
	{"Action View Quilt", "actionviewquilt", "ActionViewQuilt", mi(ActionViewQuilt), _g0},
	{"Action View Stream", "actionviewstream", "ActionViewStream", mi(ActionViewStream), _g0},
	{"Action View Week", "actionviewweek", "ActionViewWeek", mi(ActionViewWeek), _g0},
	{"Action Visibility", "actionvisibility", "ActionVisibility", mi(ActionVisibility), _g0},
	{"Action Visibility Off", "actionvisibilityoff", "ActionVisibilityOff", mi(ActionVisibilityOff), _g0},
	{"Action Watch Later", "actionwatchlater", "ActionWatchLater", mi(ActionWatchLater), _g0},
	{"Action Work", "actionwork", "ActionWork", mi(ActionWork), _g0},
	{"Action Youtube Searched For", "actionyoutubesearchedfor", "ActionYoutubeSearchedFor", mi(ActionYoutubeSearchedFor), _g0},
	{"Action Zoom In", "actionzoomin", "ActionZoomIn", mi(ActionZoomIn), _g0},
	{"Action Zoom Out", "actionzoomout", "ActionZoomOut", mi(ActionZoomOut), _g0},
	{"Alert Add Alert", "alertaddalert", "AlertAddAlert", mi(AlertAddAlert), _g0},
	{"Alert Error", "alerterror", "AlertError", mi(AlertError), _g0},
	{"Alert Error Outline", "alerterroroutline", "AlertErrorOutline", mi(AlertErrorOutline), _g0},
	{"Alert Warning", "alertwarning", "AlertWarning", mi(AlertWarning), _g0},
	{"Communication Business", "communicationbusiness", "CommunicationBusiness", mi(CommunicationBusiness), _g0},
	{"Communication Call", "communicationcall", "CommunicationCall", mi(CommunicationCall), _g0},
	{"Communication Call End", "communicationcallend", "CommunicationCallEnd", mi(CommunicationCallEnd), _g0},
	{"Communication Call Made", "communicationcallmade", "CommunicationCallMade", mi(CommunicationCallMade), _g0},
	{"Communication Call Merge", "communicationcallmerge", "CommunicationCallMerge", mi(CommunicationCallMerge), _g0},
	{"Communication Call Missed", "communicationcallmissed", "CommunicationCallMissed", mi(CommunicationCallMissed), _g0},
	{"Communication Call Missed Outgoing", "communicationcallmissedoutgoing", "CommunicationCallMissedOutgoing", mi(CommunicationCallMissedOutgoing), _g0},
	{"Communication Call Received", "communicationcallreceived", "CommunicationCallReceived", mi(CommunicationCallReceived), _g0},
	{"Communication Call Split", "communicationcallsplit", "CommunicationCallSplit", mi(CommunicationCallSplit), _g0},
	{"Communication Chat", "communicationchat", "CommunicationChat", mi(CommunicationChat), _g0},
	{"Communication Chat Bubble", "communicationchatbubble", "CommunicationChatBubble", mi(CommunicationChatBubble), _g0},
	{"Communication Chat Bubble Outline", "communicationchatbubbleoutline", "CommunicationChatBubbleOutline", mi(CommunicationChatBubbleOutline), _g0},
	{"Communication Clear All", "communicationclearall", "CommunicationClearAll", mi(CommunicationClearAll), _g0},
	{"Communication Comment", "communicationcomment", "CommunicationComment", mi(CommunicationComment), _g0},
	{"Communication Contact Mail", "communicationcontactmail", "CommunicationContactMail", mi(CommunicationContactMail), _g0},
	{"Communication Contact Phone", "communicationcontactphone", "CommunicationContactPhone", mi(CommunicationContactPhone), _g0},
	{"Communication Contacts", "communicationcontacts", "CommunicationContacts", mi(CommunicationContacts), _g0},
	{"Communication Dialer SIP", "communicationdialersip", "CommunicationDialerSIP", mi(CommunicationDialerSIP), _g0},
	{"Communication Dialpad", "communicationdialpad", "CommunicationDialpad", mi(CommunicationDialpad), _g0},
	{"Communication Email", "communicationemail", "CommunicationEmail", mi(CommunicationEmail), _g0},
	{"Communication Forum", "communicationforum", "CommunicationForum", mi(CommunicationForum), _g0},
	{"Communication Import Contacts", "communicationimportcontacts", "CommunicationImportContacts", mi(CommunicationImportContacts), _g0},
	{"Communication Import Export", "communicationimportexport", "CommunicationImportExport", mi(CommunicationImportExport), _g0},
	{"Communication Invert Colors Off", "communicationinvertcolorsoff", "CommunicationInvertColorsOff", mi(CommunicationInvertColorsOff), _g0},
	{"Communication Live Help", "communicationlivehelp", "CommunicationLiveHelp", mi(CommunicationLiveHelp), _g0},
	{"Communication Location Off", "communicationlocationoff", "CommunicationLocationOff", mi(CommunicationLocationOff), _g0},
	{"Communication Location On", "communicationlocationon", "CommunicationLocationOn", mi(CommunicationLocationOn), _g0},
	{"Communication Mail Outline", "communicationmailoutline", "CommunicationMailOutline", mi(CommunicationMailOutline), _g0},
	{"Communication Message", "communicationmessage", "CommunicationMessage", mi(CommunicationMessage), _g0},
	{"Communication No SIM", "communicationnosim", "CommunicationNoSIM", mi(CommunicationNoSIM), _g0},
	{"Communication Phone", "communicationphone", "CommunicationPhone", mi(CommunicationPhone), _g0},
	{"Communication Phone Link Erase", "communicationphonelinkerase", "CommunicationPhoneLinkErase", mi(CommunicationPhoneLinkErase), _g0},
	{"Communication Phone Link Lock", "communicationphonelinklock", "CommunicationPhoneLinkLock", mi(CommunicationPhoneLinkLock), _g0},
	{"Communication Phone Link Ring", "communicationphonelinkring", "CommunicationPhoneLinkRing", mi(CommunicationPhoneLinkRing), _g0},
	{"Communication Phone Link Setup", "communicationphonelinksetup", "CommunicationPhoneLinkSetup", mi(CommunicationPhoneLinkSetup), _g0},
	{"Communication Portable Wi Fi Off", "communicationportablewifioff", "CommunicationPortableWiFiOff", mi(CommunicationPortableWiFiOff), _g0},
	{"Communication Present To All", "communicationpresenttoall", "CommunicationPresentToAll", mi(CommunicationPresentToAll), _g0},
	{"Communication RSS Feed", "communicationrssfeed", "CommunicationRSSFeed", mi(CommunicationRSSFeed), _g0},
	{"Communication Ring Volume", "communicationringvolume", "CommunicationRingVolume", mi(CommunicationRingVolume), _g0},
	{"Communication Screen Share", "communicationscreenshare", "CommunicationScreenShare", mi(CommunicationScreenShare), _g0},
	{"Communication Speaker Phone", "communicationspeakerphone", "CommunicationSpeakerPhone", mi(CommunicationSpeakerPhone), _g0},
	{"Communication Stay Current Landscape", "communicationstaycurrentlandscape", "CommunicationStayCurrentLandscape", mi(CommunicationStayCurrentLandscape), _g0},
	{"Communication Stay Current Portrait", "communicationstaycurrentportrait", "CommunicationStayCurrentPortrait", mi(CommunicationStayCurrentPortrait), _g0},
	{"Communication Stay Primary Landscape", "communicationstayprimarylandscape", "CommunicationStayPrimaryLandscape", mi(CommunicationStayPrimaryLandscape), _g0},
	{"Communication Stay Primary Portrait", "communicationstayprimaryportrait", "CommunicationStayPrimaryPortrait", mi(CommunicationStayPrimaryPortrait), _g0},
	{"Communication Stop Screen Share", "communicationstopscreenshare", "CommunicationStopScreenShare", mi(CommunicationStopScreenShare), _g0},
	{"Communication Swap Calls", "communicationswapcalls", "CommunicationSwapCalls", mi(CommunicationSwapCalls), _g0},
	{"Communication Text SMS", "communicationtextsms", "CommunicationTextSMS", mi(CommunicationTextSMS), _g0},
	{"Communication VPN Key", "communicationvpnkey", "CommunicationVPNKey", mi(CommunicationVPNKey), _g0},
	{"Communication Voicemail", "communicationvoicemail", "CommunicationVoicemail", mi(CommunicationVoicemail), _g0},
	{"Content Add", "contentadd", "ContentAdd", mi(ContentAdd), _g0},
	{"Content Add Box", "contentaddbox", "ContentAddBox", mi(ContentAddBox), _g0},
	{"Content Add Circle", "contentaddcircle", "ContentAddCircle", mi(ContentAddCircle), _g0},
	{"Content Add Circle Outline", "contentaddcircleoutline", "ContentAddCircleOutline", mi(ContentAddCircleOutline), _g0},
	{"Content Archive", "contentarchive", "ContentArchive", mi(ContentArchive), _g0},
	{"Content Backspace", "contentbackspace", "ContentBackspace", mi(ContentBackspace), _g0},
	{"Content Block", "contentblock", "ContentBlock", mi(ContentBlock), _g0},
	{"Content Clear", "contentclear", "ContentClear", mi(ContentClear), _g0},
	{"Content Content Copy", "contentcontentcopy", "ContentContentCopy", mi(ContentContentCopy), _g0},
	{"Content Content Cut", "contentcontentcut", "ContentContentCut", mi(ContentContentCut), _g0},
	{"Content Content Paste", "contentcontentpaste", "ContentContentPaste", mi(ContentContentPaste), _g0},
	{"Content Create", "contentcreate", "ContentCreate", mi(ContentCreate), _g0},
	{"Content Delete Sweep", "contentdeletesweep", "ContentDeleteSweep", mi(ContentDeleteSweep), _g0},
	{"Content Drafts", "contentdrafts", "ContentDrafts", mi(ContentDrafts), _g0},
	{"Content Filter List", "contentfilterlist", "ContentFilterList", mi(ContentFilterList), _g0},
	{"Content Flag", "contentflag", "ContentFlag", mi(ContentFlag), _g0},
	{"Content Font Download", "contentfontdownload", "ContentFontDownload", mi(ContentFontDownload), _g0},
	{"Content Forward", "contentforward", "ContentForward", mi(ContentForward), _g0},
	{"Content Gesture", "contentgesture", "ContentGesture", mi(ContentGesture), _g0},
	{"Content Inbox", "contentinbox", "ContentInbox", mi(ContentInbox), _g0},
	{"Content Link", "contentlink", "ContentLink", mi(ContentLink), _g0},
	{"Content Low Priority", "contentlowpriority", "ContentLowPriority", mi(ContentLowPriority), _g0},
	{"Content Mail", "contentmail", "ContentMail", mi(ContentMail), _g0},
	{"Content Mark Unread", "contentmarkunread", "ContentMarkUnread", mi(ContentMarkUnread), _g0},
	{"Content Move To Inbox", "contentmovetoinbox", "ContentMoveToInbox", mi(ContentMoveToInbox), _g0},
	{"Content Next Week", "contentnextweek", "ContentNextWeek", mi(ContentNextWeek), _g0},
	{"Content Redo", "contentredo", "ContentRedo", mi(ContentRedo), _g0},
	{"Content Remove", "contentremove", "ContentRemove", mi(ContentRemove), _g0},
	{"Content Remove Circle", "contentremovecircle", "ContentRemoveCircle", mi(ContentRemoveCircle), _g0},
	{"Content Remove Circle Outline", "contentremovecircleoutline", "ContentRemoveCircleOutline", mi(ContentRemoveCircleOutline), _g0},
	{"Content Reply", "contentreply", "ContentReply", mi(ContentReply), _g0},
	{"Content Reply All", "contentreplyall", "ContentReplyAll", mi(ContentReplyAll), _g0},
	{"Content Report", "contentreport", "ContentReport", mi(ContentReport), _g0},
	{"Content Save", "contentsave", "ContentSave", mi(ContentSave), _g0},
	{"Content Select All", "contentselectall", "ContentSelectAll", mi(ContentSelectAll), _g0},
	{"Content Send", "contentsend", "ContentSend", mi(ContentSend), _g0},
	{"Content Sort", "contentsort", "ContentSort", mi(ContentSort), _g0},
	{"Content Text Format", "contenttextformat", "ContentTextFormat", mi(ContentTextFormat), _g0},
	{"Content Unarchive", "contentunarchive", "ContentUnarchive", mi(ContentUnarchive), _g0},
	{"Content Undo", "contentundo", "ContentUndo", mi(ContentUndo), _g0},
	{"Content Weekend", "contentweekend", "ContentWeekend", mi(ContentWeekend), _g0},
	{"Device Access Alarm", "deviceaccessalarm", "DeviceAccessAlarm", mi(DeviceAccessAlarm), _g0},
	{"Device Access Alarms", "deviceaccessalarms", "DeviceAccessAlarms", mi(DeviceAccessAlarms), _g0},
	{"Device Access Time", "deviceaccesstime", "DeviceAccessTime", mi(DeviceAccessTime), _g0},
	{"Device Add Alarm", "deviceaddalarm", "DeviceAddAlarm", mi(DeviceAddAlarm), _g0},
	{"Device Airplane Mode Active", "deviceairplanemodeactive", "DeviceAirplaneModeActive", mi(DeviceAirplaneModeActive), _g0},
	{"Device Airplane Mode Inactive", "deviceairplanemodeinactive", "DeviceAirplaneModeInactive", mi(DeviceAirplaneModeInactive), _g0},
	{"Device Battery 20", "devicebattery20", "DeviceBattery20", mi(DeviceBattery20), _g0},
	{"Device Battery 30", "devicebattery30", "DeviceBattery30", mi(DeviceBattery30), _g0},
	{"Device Battery 50", "devicebattery50", "DeviceBattery50", mi(DeviceBattery50), _g0},
	{"Device Battery 60", "devicebattery60", "DeviceBattery60", mi(DeviceBattery60), _g0},
	{"Device Battery 80", "devicebattery80", "DeviceBattery80", mi(DeviceBattery80), _g0},
	{"Device Battery 90", "devicebattery90", "DeviceBattery90", mi(DeviceBattery90), _g0},
	{"Device Battery Alert", "devicebatteryalert", "DeviceBatteryAlert", mi(DeviceBatteryAlert), _g0},
	{"Device Battery Charging 20", "devicebatterycharging20", "DeviceBatteryCharging20", mi(DeviceBatteryCharging20), _g0},
	{"Device Battery Charging 30", "devicebatterycharging30", "DeviceBatteryCharging30", mi(DeviceBatteryCharging30), _g0},
	{"Device Battery Charging 50", "devicebatterycharging50", "DeviceBatteryCharging50", mi(DeviceBatteryCharging50), _g0},
	{"Device Battery Charging 60", "devicebatterycharging60", "DeviceBatteryCharging60", mi(DeviceBatteryCharging60), _g0},
	{"Device Battery Charging 80", "devicebatterycharging80", "DeviceBatteryCharging80", mi(DeviceBatteryCharging80), _g0},
	{"Device Battery Charging 90", "devicebatterycharging90", "DeviceBatteryCharging90", mi(DeviceBatteryCharging90), _g0},
	{"Device Battery Charging Full", "devicebatterychargingfull", "DeviceBatteryChargingFull", mi(DeviceBatteryChargingFull), _g0},
	{"Device Battery Full", "devicebatteryfull", "DeviceBatteryFull", mi(DeviceBatteryFull), _g0},
	{"Device Battery Std", "devicebatterystd", "DeviceBatteryStd", mi(DeviceBatteryStd), _g0},
	{"Device Battery Unknown", "devicebatteryunknown", "DeviceBatteryUnknown", mi(DeviceBatteryUnknown), _g0},
	{"Device Bluetooth", "devicebluetooth", "DeviceBluetooth", mi(DeviceBluetooth), _g0},
	{"Device Bluetooth Connected", "devicebluetoothconnected", "DeviceBluetoothConnected", mi(DeviceBluetoothConnected), _g0},
	{"Device Bluetooth Disabled", "devicebluetoothdisabled", "DeviceBluetoothDisabled", mi(DeviceBluetoothDisabled), _g0},
	{"Device Bluetooth Searching", "devicebluetoothsearching", "DeviceBluetoothSearching", mi(DeviceBluetoothSearching), _g0},
	{"Device Brightness Auto", "devicebrightnessauto", "DeviceBrightnessAuto", mi(DeviceBrightnessAuto), _g0},
	{"Device Brightness High", "devicebrightnesshigh", "DeviceBrightnessHigh", mi(DeviceBrightnessHigh), _g0},
	{"Device Brightness Low", "devicebrightnesslow", "DeviceBrightnessLow", mi(DeviceBrightnessLow), _g0},
	{"Device Brightness Medium", "devicebrightnessmedium", "DeviceBrightnessMedium", mi(DeviceBrightnessMedium), _g0},
	{"Device DVR", "devicedvr", "DeviceDVR", mi(DeviceDVR), _g0},
	{"Device Data Usage", "devicedatausage", "DeviceDataUsage", mi(DeviceDataUsage), _g0},
	{"Device Developer Mode", "devicedevelopermode", "DeviceDeveloperMode", mi(DeviceDeveloperMode), _g0},
	{"Device Devices", "devicedevices", "DeviceDevices", mi(DeviceDevices), _g0},
	{"Device GPS Fixed", "devicegpsfixed", "DeviceGPSFixed", mi(DeviceGPSFixed), _g0},
	{"Device GPS Not Fixed", "devicegpsnotfixed", "DeviceGPSNotFixed", mi(DeviceGPSNotFixed), _g0},
	{"Device GPS Off", "devicegpsoff", "DeviceGPSOff", mi(DeviceGPSOff), _g0},
	{"Device Graphic Eq", "devicegraphiceq", "DeviceGraphicEq", mi(DeviceGraphicEq), _g0},
	{"Device Location Disabled", "devicelocationdisabled", "DeviceLocationDisabled", mi(DeviceLocationDisabled), _g0},
	{"Device Location Searching", "devicelocationsearching", "DeviceLocationSearching", mi(DeviceLocationSearching), _g0},
	{"Device NFC", "devicenfc", "DeviceNFC", mi(DeviceNFC), _g0},
	{"Device Network Cell", "devicenetworkcell", "DeviceNetworkCell", mi(DeviceNetworkCell), _g0},
	{"Device Network Wi Fi", "devicenetworkwifi", "DeviceNetworkWiFi", mi(DeviceNetworkWiFi), _g0},
	{"Device SD Storage", "devicesdstorage", "DeviceSDStorage", mi(DeviceSDStorage), _g0},
	{"Device Screen Lock Landscape", "devicescreenlocklandscape", "DeviceScreenLockLandscape", mi(DeviceScreenLockLandscape), _g0},
	{"Device Screen Lock Portrait", "devicescreenlockportrait", "DeviceScreenLockPortrait", mi(DeviceScreenLockPortrait), _g0},
	{"Device Screen Lock Rotation", "devicescreenlockrotation", "DeviceScreenLockRotation", mi(DeviceScreenLockRotation), _g0},
	{"Device Screen Rotation", "devicescreenrotation", "DeviceScreenRotation", mi(DeviceScreenRotation), _g0},
	{"Device Settings System Daydream", "devicesettingssystemdaydream", "DeviceSettingsSystemDaydream", mi(DeviceSettingsSystemDaydream), _g0},
	{"Device Signal Cellular 0 Bar", "devicesignalcellular0bar", "DeviceSignalCellular0Bar", mi(DeviceSignalCellular0Bar), _g0},
	{"Device Signal Cellular 1 Bar", "devicesignalcellular1bar", "DeviceSignalCellular1Bar", mi(DeviceSignalCellular1Bar), _g0},
	{"Device Signal Cellular 2 Bar", "devicesignalcellular2bar", "DeviceSignalCellular2Bar", mi(DeviceSignalCellular2Bar), _g0},
	{"Device Signal Cellular 3 Bar", "devicesignalcellular3bar", "DeviceSignalCellular3Bar", mi(DeviceSignalCellular3Bar), _g0},
	{"Device Signal Cellular 4 Bar", "devicesignalcellular4bar", "DeviceSignalCellular4Bar", mi(DeviceSignalCellular4Bar), _g0},
	{"Device Signal Cellular Connected No Internet 0 Bar", "devicesignalcellularconnectednointernet0bar", "DeviceSignalCellularConnectedNoInternet0Bar", mi(DeviceSignalCellularConnectedNoInternet0Bar), _g0},
	{"Device Signal Cellular Connected No Internet 1 Bar", "devicesignalcellularconnectednointernet1bar", "DeviceSignalCellularConnectedNoInternet1Bar", mi(DeviceSignalCellularConnectedNoInternet1Bar), _g0},
	{"Device Signal Cellular Connected No Internet 2 Bar", "devicesignalcellularconnectednointernet2bar", "DeviceSignalCellularConnectedNoInternet2Bar", mi(DeviceSignalCellularConnectedNoInternet2Bar), _g0},
	{"Device Signal Cellular Connected No Internet 3 Bar", "devicesignalcellularconnectednointernet3bar", "DeviceSignalCellularConnectedNoInternet3Bar", mi(DeviceSignalCellularConnectedNoInternet3Bar), _g0},
	{"Device Signal Cellular Connected No Internet 4 Bar", "devicesignalcellularconnectednointernet4bar", "DeviceSignalCellularConnectedNoInternet4Bar", mi(DeviceSignalCellularConnectedNoInternet4Bar), _g0},
	{"Device Signal Cellular No SIM", "devicesignalcellularnosim", "DeviceSignalCellularNoSIM", mi(DeviceSignalCellularNoSIM), _g0},
	{"Device Signal Cellular Null", "devicesignalcellularnull", "DeviceSignalCellularNull", mi(DeviceSignalCellularNull), _g0},
	{"Device Signal Cellular Off", "devicesignalcellularoff", "DeviceSignalCellularOff", mi(DeviceSignalCellularOff), _g0},
	{"Device Signal Wi Fi 0 Bar", "devicesignalwifi0bar", "DeviceSignalWiFi0Bar", mi(DeviceSignalWiFi0Bar), _g0},
	{"Device Signal Wi Fi 1 Bar", "devicesignalwifi1bar", "DeviceSignalWiFi1Bar", mi(DeviceSignalWiFi1Bar), _g0},
	{"Device Signal Wi Fi 1 Bar Lock", "devicesignalwifi1barlock", "DeviceSignalWiFi1BarLock", mi(DeviceSignalWiFi1BarLock), _g0},
	{"Device Signal Wi Fi 2 Bar", "devicesignalwifi2bar", "DeviceSignalWiFi2Bar", mi(DeviceSignalWiFi2Bar), _g0},
	{"Device Signal Wi Fi 2 Bar Lock", "devicesignalwifi2barlock", "DeviceSignalWiFi2BarLock", mi(DeviceSignalWiFi2BarLock), _g0},
	{"Device Signal Wi Fi 3 Bar", "devicesignalwifi3bar", "DeviceSignalWiFi3Bar", mi(DeviceSignalWiFi3Bar), _g0},
	{"Device Signal Wi Fi 3 Bar Lock", "devicesignalwifi3barlock", "DeviceSignalWiFi3BarLock", mi(DeviceSignalWiFi3BarLock), _g0},
	{"Device Signal Wi Fi 4 Bar", "devicesignalwifi4bar", "DeviceSignalWiFi4Bar", mi(DeviceSignalWiFi4Bar), _g0},
	{"Device Signal Wi Fi 4 Bar Lock", "devicesignalwifi4barlock", "DeviceSignalWiFi4BarLock", mi(DeviceSignalWiFi4BarLock), _g0},
	{"Device Signal Wi Fi Off", "devicesignalwifioff", "DeviceSignalWiFiOff", mi(DeviceSignalWiFiOff), _g0},
	{"Device Storage", "devicestorage", "DeviceStorage", mi(DeviceStorage), _g0},
	{"Device USB", "deviceusb", "DeviceUSB", mi(DeviceUSB), _g0},
	{"Device Wallpaper", "devicewallpaper", "DeviceWallpaper", mi(DeviceWallpaper), _g0},
	{"Device Wi Fi Lock", "devicewifilock", "DeviceWiFiLock", mi(DeviceWiFiLock), _g0},
	{"Device Wi Fi Tethering", "devicewifitethering", "DeviceWiFiTethering", mi(DeviceWiFiTethering), _g0},
	{"Device Widgets", "devicewidgets", "DeviceWidgets", mi(DeviceWidgets), _g0},
	{"Editor Attach File", "editorattachfile", "EditorAttachFile", mi(EditorAttachFile), _g0},
	{"Editor Attach Money", "editorattachmoney", "EditorAttachMoney", mi(EditorAttachMoney), _g0},
	{"Editor Border All", "editorborderall", "EditorBorderAll", mi(EditorBorderAll), _g0},
	{"Editor Border Bottom", "editorborderbottom", "EditorBorderBottom", mi(EditorBorderBottom), _g0},
	{"Editor Border Clear", "editorborderclear", "EditorBorderClear", mi(EditorBorderClear), _g0},
	{"Editor Border Color", "editorbordercolor", "EditorBorderColor", mi(EditorBorderColor), _g0},
	{"Editor Border Horizontal", "editorborderhorizontal", "EditorBorderHorizontal", mi(EditorBorderHorizontal), _g0},
	{"Editor Border Inner", "editorborderinner", "EditorBorderInner", mi(EditorBorderInner), _g0},
	{"Editor Border Left", "editorborderleft", "EditorBorderLeft", mi(EditorBorderLeft), _g0},
	{"Editor Border Outer", "editorborderouter", "EditorBorderOuter", mi(EditorBorderOuter), _g0},
	{"Editor Border Right", "editorborderright", "EditorBorderRight", mi(EditorBorderRight), _g0},
	{"Editor Border Style", "editorborderstyle", "EditorBorderStyle", mi(EditorBorderStyle), _g0},
	{"Editor Border Top", "editorbordertop", "EditorBorderTop", mi(EditorBorderTop), _g0},
	{"Editor Border Vertical", "editorbordervertical", "EditorBorderVertical", mi(EditorBorderVertical), _g0},
	{"Editor Bubble Chart", "editorbubblechart", "EditorBubbleChart", mi(EditorBubbleChart), _g0},
	{"Editor Drag Handle", "editordraghandle", "EditorDragHandle", mi(EditorDragHandle), _g0},
	{"Editor Format Align Center", "editorformataligncenter", "EditorFormatAlignCenter", mi(EditorFormatAlignCenter), _g0},
	{"Editor Format Align Justify", "editorformatalignjustify", "EditorFormatAlignJustify", mi(EditorFormatAlignJustify), _g0},
	{"Editor Format Align Left", "editorformatalignleft", "EditorFormatAlignLeft", mi(EditorFormatAlignLeft), _g0},
	{"Editor Format Align Right", "editorformatalignright", "EditorFormatAlignRight", mi(EditorFormatAlignRight), _g0},
	{"Editor Format Bold", "editorformatbold", "EditorFormatBold", mi(EditorFormatBold), _g0},
	{"Editor Format Clear", "editorformatclear", "EditorFormatClear", mi(EditorFormatClear), _g0},
	{"Editor Format Color Fill", "editorformatcolorfill", "EditorFormatColorFill", mi(EditorFormatColorFill), _g0},
	{"Editor Format Color Reset", "editorformatcolorreset", "EditorFormatColorReset", mi(EditorFormatColorReset), _g0},
	{"Editor Format Color Text", "editorformatcolortext", "EditorFormatColorText", mi(EditorFormatColorText), _g0},
	{"Editor Format Indent Decrease", "editorformatindentdecrease", "EditorFormatIndentDecrease", mi(EditorFormatIndentDecrease), _g0},
	{"Editor Format Indent Increase", "editorformatindentincrease", "EditorFormatIndentIncrease", mi(EditorFormatIndentIncrease), _g0},
	{"Editor Format Italic", "editorformatitalic", "EditorFormatItalic", mi(EditorFormatItalic), _g0},
	{"Editor Format Line Spacing", "editorformatlinespacing", "EditorFormatLineSpacing", mi(EditorFormatLineSpacing), _g0},
	{"Editor Format List Bulleted", "editorformatlistbulleted", "EditorFormatListBulleted", mi(EditorFormatListBulleted), _g0},
	{"Editor Format List Numbered", "editorformatlistnumbered", "EditorFormatListNumbered", mi(EditorFormatListNumbered), _g0},
	{"Editor Format Paint", "editorformatpaint", "EditorFormatPaint", mi(EditorFormatPaint), _g0},
	{"Editor Format Quote", "editorformatquote", "EditorFormatQuote", mi(EditorFormatQuote), _g0},
	{"Editor Format Shapes", "editorformatshapes", "EditorFormatShapes", mi(EditorFormatShapes), _g0},
	{"Editor Format Size", "editorformatsize", "EditorFormatSize", mi(EditorFormatSize), _g0},
	{"Editor Format Strikethrough", "editorformatstrikethrough", "EditorFormatStrikethrough", mi(EditorFormatStrikethrough), _g0},
	{"Editor Format Text Direction L To R", "editorformattextdirectionltor", "EditorFormatTextDirectionLToR", mi(EditorFormatTextDirectionLToR), _g0},
	{"Editor Format Text Direction R To L", "editorformattextdirectionrtol", "EditorFormatTextDirectionRToL", mi(EditorFormatTextDirectionRToL), _g0},
	{"Editor Format Underlined", "editorformatunderlined", "EditorFormatUnderlined", mi(EditorFormatUnderlined), _g0},
	{"Editor Functions", "editorfunctions", "EditorFunctions", mi(EditorFunctions), _g0},
	{"Editor Highlight", "editorhighlight", "EditorHighlight", mi(EditorHighlight), _g0},
	{"Editor Insert Chart", "editorinsertchart", "EditorInsertChart", mi(EditorInsertChart), _g0},
	{"Editor Insert Comment", "editorinsertcomment", "EditorInsertComment", mi(EditorInsertComment), _g0},
	{"Editor Insert Drive File", "editorinsertdrivefile", "EditorInsertDriveFile", mi(EditorInsertDriveFile), _g0},
	{"Editor Insert Emoticon", "editorinsertemoticon", "EditorInsertEmoticon", mi(EditorInsertEmoticon), _g0},
	{"Editor Insert Invitation", "editorinsertinvitation", "EditorInsertInvitation", mi(EditorInsertInvitation), _g0},
	{"Editor Insert Link", "editorinsertlink", "EditorInsertLink", mi(EditorInsertLink), _g0},
	{"Editor Insert Photo", "editorinsertphoto", "EditorInsertPhoto", mi(EditorInsertPhoto), _g0},
	{"Editor Linear Scale", "editorlinearscale", "EditorLinearScale", mi(EditorLinearScale), _g0},
	{"Editor Merge Type", "editormergetype", "EditorMergeType", mi(EditorMergeType), _g0},
	{"Editor Mode Comment", "editormodecomment", "EditorModeComment", mi(EditorModeComment), _g0},
	{"Editor Mode Edit", "editormodeedit", "EditorModeEdit", mi(EditorModeEdit), _g0},
	{"Editor Monetization On", "editormonetizationon", "EditorMonetizationOn", mi(EditorMonetizationOn), _g0},
	{"Editor Money Off", "editormoneyoff", "EditorMoneyOff", mi(EditorMoneyOff), _g0},
	{"Editor Multiline Chart", "editormultilinechart", "EditorMultilineChart", mi(EditorMultilineChart), _g0},
	{"Editor Pie Chart", "editorpiechart", "EditorPieChart", mi(EditorPieChart), _g0},
	{"Editor Pie Chart Outlined", "editorpiechartoutlined", "EditorPieChartOutlined", mi(EditorPieChartOutlined), _g0},
	{"Editor Publish", "editorpublish", "EditorPublish", mi(EditorPublish), _g0},
	{"Editor Short Text", "editorshorttext", "EditorShortText", mi(EditorShortText), _g0},
	{"Editor Show Chart", "editorshowchart", "EditorShowChart", mi(EditorShowChart), _g0},
	{"Editor Space Bar", "editorspacebar", "EditorSpaceBar", mi(EditorSpaceBar), _g0},
	{"Editor Strikethrough S", "editorstrikethroughs", "EditorStrikethroughS", mi(EditorStrikethroughS), _g0},
	{"Editor Text Fields", "editortextfields", "EditorTextFields", mi(EditorTextFields), _g0},
	{"Editor Title", "editortitle", "EditorTitle", mi(EditorTitle), _g0},
	{"Editor Vertical Align Bottom", "editorverticalalignbottom", "EditorVerticalAlignBottom", mi(EditorVerticalAlignBottom), _g0},
	{"Editor Vertical Align Center", "editorverticalaligncenter", "EditorVerticalAlignCenter", mi(EditorVerticalAlignCenter), _g0},
	{"Editor Vertical Align Top", "editorverticalaligntop", "EditorVerticalAlignTop", mi(EditorVerticalAlignTop), _g0},
	{"Editor Wrap Text", "editorwraptext", "EditorWrapText", mi(EditorWrapText), _g0},
	{"File Attachment", "fileattachment", "FileAttachment", mi(FileAttachment), _g0},
	{"File Cloud", "filecloud", "FileCloud", mi(FileCloud), _g0},
	{"File Cloud Circle", "filecloudcircle", "FileCloudCircle", mi(FileCloudCircle), _g0},
	{"File Cloud Done", "fileclouddone", "FileCloudDone", mi(FileCloudDone), _g0},
	{"File Cloud Download", "fileclouddownload", "FileCloudDownload", mi(FileCloudDownload), _g0},
	{"File Cloud Off", "filecloudoff", "FileCloudOff", mi(FileCloudOff), _g0},
	{"File Cloud Queue", "filecloudqueue", "FileCloudQueue", mi(FileCloudQueue), _g0},
	{"File Cloud Upload", "filecloudupload", "FileCloudUpload", mi(FileCloudUpload), _g0},
	{"File Create New Folder", "filecreatenewfolder", "FileCreateNewFolder", mi(FileCreateNewFolder), _g0},
	{"File File Download", "filefiledownload", "FileFileDownload", mi(FileFileDownload), _g0},
	{"File File Upload", "filefileupload", "FileFileUpload", mi(FileFileUpload), _g0},
	{"File Folder", "filefolder", "FileFolder", mi(FileFolder), _g0},
	{"File Folder Open", "filefolderopen", "FileFolderOpen", mi(FileFolderOpen), _g0},
	{"File Folder Shared", "filefoldershared", "FileFolderShared", mi(FileFolderShared), _g0},
	{"Hardware Cast", "hardwarecast", "HardwareCast", mi(HardwareCast), _g0},
	{"Hardware Cast Connected", "hardwarecastconnected", "HardwareCastConnected", mi(HardwareCastConnected), _g0},
	{"Hardware Computer", "hardwarecomputer", "HardwareComputer", mi(HardwareComputer), _g0},
	{"Hardware Desktop Mac", "hardwaredesktopmac", "HardwareDesktopMac", mi(HardwareDesktopMac), _g0},
	{"Hardware Desktop Windows", "hardwaredesktopwindows", "HardwareDesktopWindows", mi(HardwareDesktopWindows), _g0},
	{"Hardware Developer Board", "hardwaredeveloperboard", "HardwareDeveloperBoard", mi(HardwareDeveloperBoard), _g0},
	{"Hardware Device Hub", "hardwaredevicehub", "HardwareDeviceHub", mi(HardwareDeviceHub), _g0},
	{"Hardware Devices Other", "hardwaredevicesother", "HardwareDevicesOther", mi(HardwareDevicesOther), _g0},
	{"Hardware Dock", "hardwaredock", "HardwareDock", mi(HardwareDock), _g0},
	{"Hardware Gamepad", "hardwaregamepad", "HardwareGamepad", mi(HardwareGamepad), _g0},
	{"Hardware Headset", "hardwareheadset", "HardwareHeadset", mi(HardwareHeadset), _g0},
	{"Hardware Headset Mic", "hardwareheadsetmic", "HardwareHeadsetMic", mi(HardwareHeadsetMic), _g0},
	{"Hardware Keyboard", "hardwarekeyboard", "HardwareKeyboard", mi(HardwareKeyboard), _g0},
	{"Hardware Keyboard Arrow Down", "hardwarekeyboardarrowdown", "HardwareKeyboardArrowDown", mi(HardwareKeyboardArrowDown), _g0},
	{"Hardware Keyboard Arrow Left", "hardwarekeyboardarrowleft", "HardwareKeyboardArrowLeft", mi(HardwareKeyboardArrowLeft), _g0},
	{"Hardware Keyboard Arrow Right", "hardwarekeyboardarrowright", "HardwareKeyboardArrowRight", mi(HardwareKeyboardArrowRight), _g0},
	{"Hardware Keyboard Arrow Up", "hardwarekeyboardarrowup", "HardwareKeyboardArrowUp", mi(HardwareKeyboardArrowUp), _g0},
	{"Hardware Keyboard Backspace", "hardwarekeyboardbackspace", "HardwareKeyboardBackspace", mi(HardwareKeyboardBackspace), _g0},
	{"Hardware Keyboard Capslock", "hardwarekeyboardcapslock", "HardwareKeyboardCapslock", mi(HardwareKeyboardCapslock), _g0},
	{"Hardware Keyboard Hide", "hardwarekeyboardhide", "HardwareKeyboardHide", mi(HardwareKeyboardHide), _g0},
	{"Hardware Keyboard Return", "hardwarekeyboardreturn", "HardwareKeyboardReturn", mi(HardwareKeyboardReturn), _g0},
	{"Hardware Keyboard Tab", "hardwarekeyboardtab", "HardwareKeyboardTab", mi(HardwareKeyboardTab), _g0},
	{"Hardware Keyboard Voice", "hardwarekeyboardvoice", "HardwareKeyboardVoice", mi(HardwareKeyboardVoice), _g0},
	{"Hardware Laptop", "hardwarelaptop", "HardwareLaptop", mi(HardwareLaptop), _g0},
	{"Hardware Laptop Chromebook", "hardwarelaptopchromebook", "HardwareLaptopChromebook", mi(HardwareLaptopChromebook), _g0},
	{"Hardware Laptop Mac", "hardwarelaptopmac", "HardwareLaptopMac", mi(HardwareLaptopMac), _g0},
	{"Hardware Laptop Windows", "hardwarelaptopwindows", "HardwareLaptopWindows", mi(HardwareLaptopWindows), _g0},
	{"Hardware Memory", "hardwarememory", "HardwareMemory", mi(HardwareMemory), _g0},
	{"Hardware Mouse", "hardwaremouse", "HardwareMouse", mi(HardwareMouse), _g0},
	{"Hardware Phone Android", "hardwarephoneandroid", "HardwarePhoneAndroid", mi(HardwarePhoneAndroid), _g0},
	{"Hardware Phone I Phone", "hardwarephoneiphone", "HardwarePhoneIPhone", mi(HardwarePhoneIPhone), _g0},
	{"Hardware Phone Link", "hardwarephonelink", "HardwarePhoneLink", mi(HardwarePhoneLink), _g0},
	{"Hardware Phone Link Off", "hardwarephonelinkoff", "HardwarePhoneLinkOff", mi(HardwarePhoneLinkOff), _g0},
	{"Hardware Power Input", "hardwarepowerinput", "HardwarePowerInput", mi(HardwarePowerInput), _g0},
	{"Hardware Router", "hardwarerouter", "HardwareRouter", mi(HardwareRouter), _g0},
	{"Hardware SIM Card", "hardwaresimcard", "HardwareSIMCard", mi(HardwareSIMCard), _g0},
	{"Hardware Scanner", "hardwarescanner", "HardwareScanner", mi(HardwareScanner), _g0},
	{"Hardware Security", "hardwaresecurity", "HardwareSecurity", mi(HardwareSecurity), _g0},
	{"Hardware Smartphone", "hardwaresmartphone", "HardwareSmartphone", mi(HardwareSmartphone), _g0},
	{"Hardware Speaker", "hardwarespeaker", "HardwareSpeaker", mi(HardwareSpeaker), _g0},
	{"Hardware Speaker Group", "hardwarespeakergroup", "HardwareSpeakerGroup", mi(HardwareSpeakerGroup), _g0},
	{"Hardware TV", "hardwaretv", "HardwareTV", mi(HardwareTV), _g0},
	{"Hardware Tablet", "hardwaretablet", "HardwareTablet", mi(HardwareTablet), _g0},
	{"Hardware Tablet Android", "hardwaretabletandroid", "HardwareTabletAndroid", mi(HardwareTabletAndroid), _g0},
	{"Hardware Tablet Mac", "hardwaretabletmac", "HardwareTabletMac", mi(HardwareTabletMac), _g0},
	{"Hardware Toys", "hardwaretoys", "HardwareToys", mi(HardwareToys), _g0},
	{"Hardware Videogame Asset", "hardwarevideogameasset", "HardwareVideogameAsset", mi(HardwareVideogameAsset), _g0},
	{"Hardware Watch", "hardwarewatch", "HardwareWatch", mi(HardwareWatch), _g0},
	{"Image Add A Photo", "imageaddaphoto", "ImageAddAPhoto", mi(ImageAddAPhoto), _g0},
	{"Image Add To Photos", "imageaddtophotos", "ImageAddToPhotos", mi(ImageAddToPhotos), _g0},
	{"Image Adjust", "imageadjust", "ImageAdjust", mi(ImageAdjust), _g0},
	{"Image Assistant", "imageassistant", "ImageAssistant", mi(ImageAssistant), _g0},
	{"Image Assistant Photo", "imageassistantphoto", "ImageAssistantPhoto", mi(ImageAssistantPhoto), _g0},
	{"Image Audiotrack", "imageaudiotrack", "ImageAudiotrack", mi(ImageAudiotrack), _g0},
	{"Image Blur Circular", "imageblurcircular", "ImageBlurCircular", mi(ImageBlurCircular), _g0},
	{"Image Blur Linear", "imageblurlinear", "ImageBlurLinear", mi(ImageBlurLinear), _g0},
	{"Image Blur Off", "imagebluroff", "ImageBlurOff", mi(ImageBlurOff), _g0},
	{"Image Blur On", "imagebluron", "ImageBlurOn", mi(ImageBlurOn), _g0},
	{"Image Brightness 1", "imagebrightness1", "ImageBrightness1", mi(ImageBrightness1), _g0},
	{"Image Brightness 2", "imagebrightness2", "ImageBrightness2", mi(ImageBrightness2), _g0},
	{"Image Brightness 3", "imagebrightness3", "ImageBrightness3", mi(ImageBrightness3), _g0},
	{"Image Brightness 4", "imagebrightness4", "ImageBrightness4", mi(ImageBrightness4), _g0},
	{"Image Brightness 5", "imagebrightness5", "ImageBrightness5", mi(ImageBrightness5), _g0},
	{"Image Brightness 6", "imagebrightness6", "ImageBrightness6", mi(ImageBrightness6), _g0},
	{"Image Brightness 7", "imagebrightness7", "ImageBrightness7", mi(ImageBrightness7), _g0},
	{"Image Broken Image", "imagebrokenimage", "ImageBrokenImage", mi(ImageBrokenImage), _g0},
	{"Image Brush", "imagebrush", "ImageBrush", mi(ImageBrush), _g0},
	{"Image Burst Mode", "imageburstmode", "ImageBurstMode", mi(ImageBurstMode), _g0},
	{"Image Camera", "imagecamera", "ImageCamera", mi(ImageCamera), _g0},
	{"Image Camera Alt", "imagecameraalt", "ImageCameraAlt", mi(ImageCameraAlt), _g0},
	{"Image Camera Front", "imagecamerafront", "ImageCameraFront", mi(ImageCameraFront), _g0},
	{"Image Camera Rear", "imagecamerarear", "ImageCameraRear", mi(ImageCameraRear), _g0},
	{"Image Camera Roll", "imagecameraroll", "ImageCameraRoll", mi(ImageCameraRoll), _g0},
	{"Image Center Focus Strong", "imagecenterfocusstrong", "ImageCenterFocusStrong", mi(ImageCenterFocusStrong), _g0},
	{"Image Center Focus Weak", "imagecenterfocusweak", "ImageCenterFocusWeak", mi(ImageCenterFocusWeak), _g0},
	{"Image Collections", "imagecollections", "ImageCollections", mi(ImageCollections), _g0},
	{"Image Collections Bookmark", "imagecollectionsbookmark", "ImageCollectionsBookmark", mi(ImageCollectionsBookmark), _g0},
	{"Image Color Lens", "imagecolorlens", "ImageColorLens", mi(ImageColorLens), _g0},
	{"Image Colorize", "imagecolorize", "ImageColorize", mi(ImageColorize), _g0},
	{"Image Compare", "imagecompare", "ImageCompare", mi(ImageCompare), _g0},
	{"Image Control Point", "imagecontrolpoint", "ImageControlPoint", mi(ImageControlPoint), _g0},
	{"Image Control Point Duplicate", "imagecontrolpointduplicate", "ImageControlPointDuplicate", mi(ImageControlPointDuplicate), _g0},
	{"Image Crop", "imagecrop", "ImageCrop", mi(ImageCrop), _g0},
	{"Image Crop 169", "imagecrop169", "ImageCrop169", mi(ImageCrop169), _g0},
	{"Image Crop 32", "imagecrop32", "ImageCrop32", mi(ImageCrop32), _g0},
	{"Image Crop 54", "imagecrop54", "ImageCrop54", mi(ImageCrop54), _g0},
	{"Image Crop 75", "imagecrop75", "ImageCrop75", mi(ImageCrop75), _g0},
	{"Image Crop DIN", "imagecropdin", "ImageCropDIN", mi(ImageCropDIN), _g0},
	{"Image Crop Free", "imagecropfree", "ImageCropFree", mi(ImageCropFree), _g0},
	{"Image Crop Landscape", "imagecroplandscape", "ImageCropLandscape", mi(ImageCropLandscape), _g0},
	{"Image Crop Original", "imagecroporiginal", "ImageCropOriginal", mi(ImageCropOriginal), _g0},
	{"Image Crop Portrait", "imagecropportrait", "ImageCropPortrait", mi(ImageCropPortrait), _g0},
	{"Image Crop Rotate", "imagecroprotate", "ImageCropRotate", mi(ImageCropRotate), _g0},
	{"Image Crop Square", "imagecropsquare", "ImageCropSquare", mi(ImageCropSquare), _g0},
	{"Image Dehaze", "imagedehaze", "ImageDehaze", mi(ImageDehaze), _g0},
	{"Image Details", "imagedetails", "ImageDetails", mi(ImageDetails), _g0},
	{"Image Edit", "imageedit", "ImageEdit", mi(ImageEdit), _g0},
	{"Image Exposure", "imageexposure", "ImageExposure", mi(ImageExposure), _g0},
	{"Image Exposure Neg 1", "imageexposureneg1", "ImageExposureNeg1", mi(ImageExposureNeg1), _g0},
	{"Image Exposure Neg 2", "imageexposureneg2", "ImageExposureNeg2", mi(ImageExposureNeg2), _g0},
	{"Image Exposure Plus 1", "imageexposureplus1", "ImageExposurePlus1", mi(ImageExposurePlus1), _g0},
	{"Image Exposure Plus 2", "imageexposureplus2", "ImageExposurePlus2", mi(ImageExposurePlus2), _g0},
	{"Image Exposure Zero", "imageexposurezero", "ImageExposureZero", mi(ImageExposureZero), _g0},
	{"Image Filter", "imagefilter", "ImageFilter", mi(ImageFilter), _g0},
	{"Image Filter 1", "imagefilter1", "ImageFilter1", mi(ImageFilter1), _g0},
	{"Image Filter 2", "imagefilter2", "ImageFilter2", mi(ImageFilter2), _g0},
	{"Image Filter 3", "imagefilter3", "ImageFilter3", mi(ImageFilter3), _g0},
	{"Image Filter 4", "imagefilter4", "ImageFilter4", mi(ImageFilter4), _g0},
	{"Image Filter 5", "imagefilter5", "ImageFilter5", mi(ImageFilter5), _g0},
	{"Image Filter 6", "imagefilter6", "ImageFilter6", mi(ImageFilter6), _g0},
	{"Image Filter 7", "imagefilter7", "ImageFilter7", mi(ImageFilter7), _g0},
	{"Image Filter 8", "imagefilter8", "ImageFilter8", mi(ImageFilter8), _g0},
	{"Image Filter 9", "imagefilter9", "ImageFilter9", mi(ImageFilter9), _g0},
	{"Image Filter 9 Plus", "imagefilter9plus", "ImageFilter9Plus", mi(ImageFilter9Plus), _g0},
	{"Image Filter B And W", "imagefilterbandw", "ImageFilterBAndW", mi(ImageFilterBAndW), _g0},
	{"Image Filter Center Focus", "imagefiltercenterfocus", "ImageFilterCenterFocus", mi(ImageFilterCenterFocus), _g0},
	{"Image Filter Drama", "imagefilterdrama", "ImageFilterDrama", mi(ImageFilterDrama), _g0},
	{"Image Filter Frames", "imagefilterframes", "ImageFilterFrames", mi(ImageFilterFrames), _g0},
	{"Image Filter HDR", "imagefilterhdr", "ImageFilterHDR", mi(ImageFilterHDR), _g0},
	{"Image Filter None", "imagefilternone", "ImageFilterNone", mi(ImageFilterNone), _g0},
	{"Image Filter Tilt Shift", "imagefiltertiltshift", "ImageFilterTiltShift", mi(ImageFilterTiltShift), _g0},
	{"Image Filter Vintage", "imagefiltervintage", "ImageFilterVintage", mi(ImageFilterVintage), _g0},
	{"Image Flare", "imageflare", "ImageFlare", mi(ImageFlare), _g0},
	{"Image Flash Auto", "imageflashauto", "ImageFlashAuto", mi(ImageFlashAuto), _g0},
	{"Image Flash Off", "imageflashoff", "ImageFlashOff", mi(ImageFlashOff), _g0},
	{"Image Flash On", "imageflashon", "ImageFlashOn", mi(ImageFlashOn), _g0},
	{"Image Flip", "imageflip", "ImageFlip", mi(ImageFlip), _g0},
	{"Image Gradient", "imagegradient", "ImageGradient", mi(ImageGradient), _g0},
	{"Image Grain", "imagegrain", "ImageGrain", mi(ImageGrain), _g0},
	{"Image Grid Off", "imagegridoff", "ImageGridOff", mi(ImageGridOff), _g0},
	{"Image Grid On", "imagegridon", "ImageGridOn", mi(ImageGridOn), _g0},
	{"Image HDR Off", "imagehdroff", "ImageHDROff", mi(ImageHDROff), _g0},
	{"Image HDR On", "imagehdron", "ImageHDROn", mi(ImageHDROn), _g0},
	{"Image HDR Strong", "imagehdrstrong", "ImageHDRStrong", mi(ImageHDRStrong), _g0},
	{"Image HDR Weak", "imagehdrweak", "ImageHDRWeak", mi(ImageHDRWeak), _g0},
	{"Image Healing", "imagehealing", "ImageHealing", mi(ImageHealing), _g0},
	{"Image ISO", "imageiso", "ImageISO", mi(ImageISO), _g0},
	{"Image Image", "imageimage", "ImageImage", mi(ImageImage), _g0},
	{"Image Image Aspect Ratio", "imageimageaspectratio", "ImageImageAspectRatio", mi(ImageImageAspectRatio), _g0},
	{"Image Landscape", "imagelandscape", "ImageLandscape", mi(ImageLandscape), _g0},
	{"Image Leak Add", "imageleakadd", "ImageLeakAdd", mi(ImageLeakAdd), _g0},
	{"Image Leak Remove", "imageleakremove", "ImageLeakRemove", mi(ImageLeakRemove), _g0},
	{"Image Lens", "imagelens", "ImageLens", mi(ImageLens), _g0},
	{"Image Linked Camera", "imagelinkedcamera", "ImageLinkedCamera", mi(ImageLinkedCamera), _g0},
	{"Image Looks", "imagelooks", "ImageLooks", mi(ImageLooks), _g0},
	{"Image Looks 3", "imagelooks3", "ImageLooks3", mi(ImageLooks3), _g0},
	{"Image Looks 4", "imagelooks4", "ImageLooks4", mi(ImageLooks4), _g0},
	{"Image Looks 5", "imagelooks5", "ImageLooks5", mi(ImageLooks5), _g0},
	{"Image Looks 6", "imagelooks6", "ImageLooks6", mi(ImageLooks6), _g0},
	{"Image Looks One", "imagelooksone", "ImageLooksOne", mi(ImageLooksOne), _g0},
	{"Image Looks Two", "imagelookstwo", "ImageLooksTwo", mi(ImageLooksTwo), _g0},
	{"Image Loupe", "imageloupe", "ImageLoupe", mi(ImageLoupe), _g0},
	{"Image Monochrome Photos", "imagemonochromephotos", "ImageMonochromePhotos", mi(ImageMonochromePhotos), _g0},
	{"Image Movie Creation", "imagemoviecreation", "ImageMovieCreation", mi(ImageMovieCreation), _g0},
	{"Image Movie Filter", "imagemoviefilter", "ImageMovieFilter", mi(ImageMovieFilter), _g0},
	{"Image Music Note", "imagemusicnote", "ImageMusicNote", mi(ImageMusicNote), _g0},
	{"Image Nature", "imagenature", "ImageNature", mi(ImageNature), _g0},
	{"Image Nature People", "imagenaturepeople", "ImageNaturePeople", mi(ImageNaturePeople), _g0},
	{"Image Navigate Before", "imagenavigatebefore", "ImageNavigateBefore", mi(ImageNavigateBefore), _g0},
	{"Image Navigate Next", "imagenavigatenext", "ImageNavigateNext", mi(ImageNavigateNext), _g0},
	{"Image Palette", "imagepalette", "ImagePalette", mi(ImagePalette), _g0},
	{"Image Panorama", "imagepanorama", "ImagePanorama", mi(ImagePanorama), _g0},
	{"Image Panorama Fish Eye", "imagepanoramafisheye", "ImagePanoramaFishEye", mi(ImagePanoramaFishEye), _g0},
	{"Image Panorama Horizontal", "imagepanoramahorizontal", "ImagePanoramaHorizontal", mi(ImagePanoramaHorizontal), _g0},
	{"Image Panorama Vertical", "imagepanoramavertical", "ImagePanoramaVertical", mi(ImagePanoramaVertical), _g0},
	{"Image Panorama Wide Angle", "imagepanoramawideangle", "ImagePanoramaWideAngle", mi(ImagePanoramaWideAngle), _g0},
	{"Image Photo", "imagephoto", "ImagePhoto", mi(ImagePhoto), _g0},
	{"Image Photo Album", "imagephotoalbum", "ImagePhotoAlbum", mi(ImagePhotoAlbum), _g0},
	{"Image Photo Camera", "imagephotocamera", "ImagePhotoCamera", mi(ImagePhotoCamera), _g0},
	{"Image Photo Filter", "imagephotofilter", "ImagePhotoFilter", mi(ImagePhotoFilter), _g0},
	{"Image Photo Library", "imagephotolibrary", "ImagePhotoLibrary", mi(ImagePhotoLibrary), _g0},
	{"Image Photo Size Select Actual", "imagephotosizeselectactual", "ImagePhotoSizeSelectActual", mi(ImagePhotoSizeSelectActual), _g0},
	{"Image Photo Size Select Large", "imagephotosizeselectlarge", "ImagePhotoSizeSelectLarge", mi(ImagePhotoSizeSelectLarge), _g0},
	{"Image Photo Size Select Small", "imagephotosizeselectsmall", "ImagePhotoSizeSelectSmall", mi(ImagePhotoSizeSelectSmall), _g0},
	{"Image Picture As PDF", "imagepictureaspdf", "ImagePictureAsPDF", mi(ImagePictureAsPDF), _g0},
	{"Image Portrait", "imageportrait", "ImagePortrait", mi(ImagePortrait), _g0},
	{"Image Remove Red Eye", "imageremoveredeye", "ImageRemoveRedEye", mi(ImageRemoveRedEye), _g0},
	{"Image Rotate 90 Degrees CCW", "imagerotate90degreesccw", "ImageRotate90DegreesCCW", mi(ImageRotate90DegreesCCW), _g0},
	{"Image Rotate Left", "imagerotateleft", "ImageRotateLeft", mi(ImageRotateLeft), _g0},
	{"Image Rotate Right", "imagerotateright", "ImageRotateRight", mi(ImageRotateRight), _g0},
	{"Image Slideshow", "imageslideshow", "ImageSlideshow", mi(ImageSlideshow), _g0},
	{"Image Straighten", "imagestraighten", "ImageStraighten", mi(ImageStraighten), _g0},
	{"Image Style", "imagestyle", "ImageStyle", mi(ImageStyle), _g0},
	{"Image Switch Camera", "imageswitchcamera", "ImageSwitchCamera", mi(ImageSwitchCamera), _g0},
	{"Image Switch Video", "imageswitchvideo", "ImageSwitchVideo", mi(ImageSwitchVideo), _g0},
	{"Image Tag Faces", "imagetagfaces", "ImageTagFaces", mi(ImageTagFaces), _g0},
	{"Image Texture", "imagetexture", "ImageTexture", mi(ImageTexture), _g0},
	{"Image Time Lapse", "imagetimelapse", "ImageTimeLapse", mi(ImageTimeLapse), _g0},
	{"Image Timer", "imagetimer", "ImageTimer", mi(ImageTimer), _g0},
	{"Image Timer 10", "imagetimer10", "ImageTimer10", mi(ImageTimer10), _g0},
	{"Image Timer 3", "imagetimer3", "ImageTimer3", mi(ImageTimer3), _g0},
	{"Image Timer Off", "imagetimeroff", "ImageTimerOff", mi(ImageTimerOff), _g0},
	{"Image Tonality", "imagetonality", "ImageTonality", mi(ImageTonality), _g0},
	{"Image Transform", "imagetransform", "ImageTransform", mi(ImageTransform), _g0},
	{"Image Tune", "imagetune", "ImageTune", mi(ImageTune), _g0},
	{"Image View Comfy", "imageviewcomfy", "ImageViewComfy", mi(ImageViewComfy), _g0},
	{"Image View Compact", "imageviewcompact", "ImageViewCompact", mi(ImageViewCompact), _g0},
	{"Image Vignette", "imagevignette", "ImageVignette", mi(ImageVignette), _g0},
	{"Image WB Auto", "imagewbauto", "ImageWBAuto", mi(ImageWBAuto), _g0},
	{"Image WB Cloudy", "imagewbcloudy", "ImageWBCloudy", mi(ImageWBCloudy), _g0},
	{"Image WB Incandescent", "imagewbincandescent", "ImageWBIncandescent", mi(ImageWBIncandescent), _g0},
	{"Image WB Iridescent", "imagewbiridescent", "ImageWBIridescent", mi(ImageWBIridescent), _g0},
	{"Image WB Sunny", "imagewbsunny", "ImageWBSunny", mi(ImageWBSunny), _g0},
	{"Maps Add Location", "mapsaddlocation", "MapsAddLocation", mi(MapsAddLocation), _g0},
	{"Maps Beenhere", "mapsbeenhere", "MapsBeenhere", mi(MapsBeenhere), _g0},
	{"Maps Directions", "mapsdirections", "MapsDirections", mi(MapsDirections), _g0},
	{"Maps Directions Bike", "mapsdirectionsbike", "MapsDirectionsBike", mi(MapsDirectionsBike), _g0},
	{"Maps Directions Boat", "mapsdirectionsboat", "MapsDirectionsBoat", mi(MapsDirectionsBoat), _g0},
	{"Maps Directions Bus", "mapsdirectionsbus", "MapsDirectionsBus", mi(MapsDirectionsBus), _g0},
	{"Maps Directions Car", "mapsdirectionscar", "MapsDirectionsCar", mi(MapsDirectionsCar), _g0},
	{"Maps Directions Railway", "mapsdirectionsrailway", "MapsDirectionsRailway", mi(MapsDirectionsRailway), _g0},
	{"Maps Directions Run", "mapsdirectionsrun", "MapsDirectionsRun", mi(MapsDirectionsRun), _g0},
	{"Maps Directions Subway", "mapsdirectionssubway", "MapsDirectionsSubway", mi(MapsDirectionsSubway), _g0},
	{"Maps Directions Transit", "mapsdirectionstransit", "MapsDirectionsTransit", mi(MapsDirectionsTransit), _g0},
	{"Maps Directions Walk", "mapsdirectionswalk", "MapsDirectionsWalk", mi(MapsDirectionsWalk), _g0},
	{"Maps EV Station", "mapsevstation", "MapsEVStation", mi(MapsEVStation), _g0},
	{"Maps Edit Location", "mapseditlocation", "MapsEditLocation", mi(MapsEditLocation), _g0},
	{"Maps Flight", "mapsflight", "MapsFlight", mi(MapsFlight), _g0},
	{"Maps Hotel", "mapshotel", "MapsHotel", mi(MapsHotel), _g0},
	{"Maps Layers", "mapslayers", "MapsLayers", mi(MapsLayers), _g0},
	{"Maps Layers Clear", "mapslayersclear", "MapsLayersClear", mi(MapsLayersClear), _g0},
	{"Maps Local ATM", "mapslocalatm", "MapsLocalATM", mi(MapsLocalATM), _g0},
	{"Maps Local Activity", "mapslocalactivity", "MapsLocalActivity", mi(MapsLocalActivity), _g0},
	{"Maps Local Airport", "mapslocalairport", "MapsLocalAirport", mi(MapsLocalAirport), _g0},
	{"Maps Local Bar", "mapslocalbar", "MapsLocalBar", mi(MapsLocalBar), _g0},
	{"Maps Local Cafe", "mapslocalcafe", "MapsLocalCafe", mi(MapsLocalCafe), _g0},
	{"Maps Local Car Wash", "mapslocalcarwash", "MapsLocalCarWash", mi(MapsLocalCarWash), _g0},
	{"Maps Local Convenience Store", "mapslocalconveniencestore", "MapsLocalConvenienceStore", mi(MapsLocalConvenienceStore), _g0},
	{"Maps Local Dining", "mapslocaldining", "MapsLocalDining", mi(MapsLocalDining), _g0},
	{"Maps Local Drink", "mapslocaldrink", "MapsLocalDrink", mi(MapsLocalDrink), _g0},
	{"Maps Local Florist", "mapslocalflorist", "MapsLocalFlorist", mi(MapsLocalFlorist), _g0},
	{"Maps Local Gas Station", "mapslocalgasstation", "MapsLocalGasStation", mi(MapsLocalGasStation), _g0},
	{"Maps Local Grocery Store", "mapslocalgrocerystore", "MapsLocalGroceryStore", mi(MapsLocalGroceryStore), _g0},
	{"Maps Local Hospital", "mapslocalhospital", "MapsLocalHospital", mi(MapsLocalHospital), _g0},
	{"Maps Local Hotel", "mapslocalhotel", "MapsLocalHotel", mi(MapsLocalHotel), _g0},
	{"Maps Local Laundry Service", "mapslocallaundryservice", "MapsLocalLaundryService", mi(MapsLocalLaundryService), _g0},
	{"Maps Local Library", "mapslocallibrary", "MapsLocalLibrary", mi(MapsLocalLibrary), _g0},
	{"Maps Local Mall", "mapslocalmall", "MapsLocalMall", mi(MapsLocalMall), _g0},
	{"Maps Local Movies", "mapslocalmovies", "MapsLocalMovies", mi(MapsLocalMovies), _g0},
	{"Maps Local Offer", "mapslocaloffer", "MapsLocalOffer", mi(MapsLocalOffer), _g0},
	{"Maps Local Parking", "mapslocalparking", "MapsLocalParking", mi(MapsLocalParking), _g0},
	{"Maps Local Pharmacy", "mapslocalpharmacy", "MapsLocalPharmacy", mi(MapsLocalPharmacy), _g0},
	{"Maps Local Phone", "mapslocalphone", "MapsLocalPhone", mi(MapsLocalPhone), _g0},
	{"Maps Local Pizza", "mapslocalpizza", "MapsLocalPizza", mi(MapsLocalPizza), _g0},
	{"Maps Local Play", "mapslocalplay", "MapsLocalPlay", mi(MapsLocalPlay), _g0},
	{"Maps Local Post Office", "mapslocalpostoffice", "MapsLocalPostOffice", mi(MapsLocalPostOffice), _g0},
	{"Maps Local Printshop", "mapslocalprintshop", "MapsLocalPrintshop", mi(MapsLocalPrintshop), _g0},
	{"Maps Local See", "mapslocalsee", "MapsLocalSee", mi(MapsLocalSee), _g0},
	{"Maps Local Shipping", "mapslocalshipping", "MapsLocalShipping", mi(MapsLocalShipping), _g0},
	{"Maps Local Taxi", "mapslocaltaxi", "MapsLocalTaxi", mi(MapsLocalTaxi), _g0},
	{"Maps Map", "mapsmap", "MapsMap", mi(MapsMap), _g0},
	{"Maps My Location", "mapsmylocation", "MapsMyLocation", mi(MapsMyLocation), _g0},
	{"Maps Navigation", "mapsnavigation", "MapsNavigation", mi(MapsNavigation), _g0},
	{"Maps Near Me", "mapsnearme", "MapsNearMe", mi(MapsNearMe), _g0},
	{"Maps Person Pin", "mapspersonpin", "MapsPersonPin", mi(MapsPersonPin), _g0},
	{"Maps Person Pin Circle", "mapspersonpincircle", "MapsPersonPinCircle", mi(MapsPersonPinCircle), _g0},
	{"Maps Pin Drop", "mapspindrop", "MapsPinDrop", mi(MapsPinDrop), _g0},
	{"Maps Place", "mapsplace", "MapsPlace", mi(MapsPlace), _g0},
	{"Maps Rate Review", "mapsratereview", "MapsRateReview", mi(MapsRateReview), _g0},
	{"Maps Restaurant", "mapsrestaurant", "MapsRestaurant", mi(MapsRestaurant), _g0},
	{"Maps Restaurant Menu", "mapsrestaurantmenu", "MapsRestaurantMenu", mi(MapsRestaurantMenu), _g0},
	{"Maps Satellite", "mapssatellite", "MapsSatellite", mi(MapsSatellite), _g0},
	{"Maps Store Mall Directory", "mapsstoremalldirectory", "MapsStoreMallDirectory", mi(MapsStoreMallDirectory), _g0},
	{"Maps Street View", "mapsstreetview", "MapsStreetView", mi(MapsStreetView), _g0},
	{"Maps Subway", "mapssubway", "MapsSubway", mi(MapsSubway), _g0},
	{"Maps Terrain", "mapsterrain", "MapsTerrain", mi(MapsTerrain), _g0},
	{"Maps Traffic", "mapstraffic", "MapsTraffic", mi(MapsTraffic), _g0},
	{"Maps Train", "mapstrain", "MapsTrain", mi(MapsTrain), _g0},
	{"Maps Tram", "mapstram", "MapsTram", mi(MapsTram), _g0},
	{"Maps Transfer Within A Station", "mapstransferwithinastation", "MapsTransferWithinAStation", mi(MapsTransferWithinAStation), _g0},
	{"Maps Zoom Out Map", "mapszoomoutmap", "MapsZoomOutMap", mi(MapsZoomOutMap), _g0},
	{"Navigation Apps", "navigationapps", "NavigationApps", mi(NavigationApps), _g0},
	{"Navigation Arrow Back", "navigationarrowback", "NavigationArrowBack", mi(NavigationArrowBack), _g0},
	{"Navigation Arrow Downward", "navigationarrowdownward", "NavigationArrowDownward", mi(NavigationArrowDownward), _g0},
	{"Navigation Arrow Drop Down", "navigationarrowdropdown", "NavigationArrowDropDown", mi(NavigationArrowDropDown), _g0},
	{"Navigation Arrow Drop Down Circle", "navigationarrowdropdowncircle", "NavigationArrowDropDownCircle", mi(NavigationArrowDropDownCircle), _g0},
	{"Navigation Arrow Drop Up", "navigationarrowdropup", "NavigationArrowDropUp", mi(NavigationArrowDropUp), _g0},
	{"Navigation Arrow Forward", "navigationarrowforward", "NavigationArrowForward", mi(NavigationArrowForward), _g0},
	{"Navigation Arrow Upward", "navigationarrowupward", "NavigationArrowUpward", mi(NavigationArrowUpward), _g0},
	{"Navigation Cancel", "navigationcancel", "NavigationCancel", mi(NavigationCancel), _g0},
	{"Navigation Check", "navigationcheck", "NavigationCheck", mi(NavigationCheck), _g0},
	{"Navigation Chevron Left", "navigationchevronleft", "NavigationChevronLeft", mi(NavigationChevronLeft), _g0},
	{"Navigation Chevron Right", "navigationchevronright", "NavigationChevronRight", mi(NavigationChevronRight), _g0},
	{"Navigation Close", "navigationclose", "NavigationClose", mi(NavigationClose), _g0},
	{"Navigation Expand Less", "navigationexpandless", "NavigationExpandLess", mi(NavigationExpandLess), _g0},
	{"Navigation Expand More", "navigationexpandmore", "NavigationExpandMore", mi(NavigationExpandMore), _g0},
	{"Navigation First Page", "navigationfirstpage", "NavigationFirstPage", mi(NavigationFirstPage), _g0},
	{"Navigation Fullscreen", "navigationfullscreen", "NavigationFullscreen", mi(NavigationFullscreen), _g0},
	{"Navigation Fullscreen Exit", "navigationfullscreenexit", "NavigationFullscreenExit", mi(NavigationFullscreenExit), _g0},
	{"Navigation Last Page", "navigationlastpage", "NavigationLastPage", mi(NavigationLastPage), _g0},
	{"Navigation Menu", "navigationmenu", "NavigationMenu", mi(NavigationMenu), _g0},
	{"Navigation More Horiz", "navigationmorehoriz", "NavigationMoreHoriz", mi(NavigationMoreHoriz), _g0},
	{"Navigation More Vert", "navigationmorevert", "NavigationMoreVert", mi(NavigationMoreVert), _g0},
	{"Navigation Refresh", "navigationrefresh", "NavigationRefresh", mi(NavigationRefresh), _g0},
	{"Navigation Subdirectory Arrow Left", "navigationsubdirectoryarrowleft", "NavigationSubdirectoryArrowLeft", mi(NavigationSubdirectoryArrowLeft), _g0},
	{"Navigation Subdirectory Arrow Right", "navigationsubdirectoryarrowright", "NavigationSubdirectoryArrowRight", mi(NavigationSubdirectoryArrowRight), _g0},
	{"Navigation Unfold Less", "navigationunfoldless", "NavigationUnfoldLess", mi(NavigationUnfoldLess), _g0},
	{"Navigation Unfold More", "navigationunfoldmore", "NavigationUnfoldMore", mi(NavigationUnfoldMore), _g0},
	{"Notification ADB", "notificationadb", "NotificationADB", mi(NotificationADB), _g0},
	{"Notification Airline Seat Flat", "notificationairlineseatflat", "NotificationAirlineSeatFlat", mi(NotificationAirlineSeatFlat), _g0},
	{"Notification Airline Seat Flat Angled", "notificationairlineseatflatangled", "NotificationAirlineSeatFlatAngled", mi(NotificationAirlineSeatFlatAngled), _g0},
	{"Notification Airline Seat Individual Suite", "notificationairlineseatindividualsuite", "NotificationAirlineSeatIndividualSuite", mi(NotificationAirlineSeatIndividualSuite), _g0},
	{"Notification Airline Seat Legroom Extra", "notificationairlineseatlegroomextra", "NotificationAirlineSeatLegroomExtra", mi(NotificationAirlineSeatLegroomExtra), _g0},
	{"Notification Airline Seat Legroom Normal", "notificationairlineseatlegroomnormal", "NotificationAirlineSeatLegroomNormal", mi(NotificationAirlineSeatLegroomNormal), _g0},
	{"Notification Airline Seat Legroom Reduced", "notificationairlineseatlegroomreduced", "NotificationAirlineSeatLegroomReduced", mi(NotificationAirlineSeatLegroomReduced), _g0},
	{"Notification Airline Seat Recline Extra", "notificationairlineseatreclineextra", "NotificationAirlineSeatReclineExtra", mi(NotificationAirlineSeatReclineExtra), _g0},
	{"Notification Airline Seat Recline Normal", "notificationairlineseatreclinenormal", "NotificationAirlineSeatReclineNormal", mi(NotificationAirlineSeatReclineNormal), _g0},
	{"Notification Bluetooth Audio", "notificationbluetoothaudio", "NotificationBluetoothAudio", mi(NotificationBluetoothAudio), _g0},
	{"Notification Confirmation Number", "notificationconfirmationnumber", "NotificationConfirmationNumber", mi(NotificationConfirmationNumber), _g0},
	{"Notification Disc Full", "notificationdiscfull", "NotificationDiscFull", mi(NotificationDiscFull), _g0},
	{"Notification Do Not Disturb", "notificationdonotdisturb", "NotificationDoNotDisturb", mi(NotificationDoNotDisturb), _g0},
	{"Notification Do Not Disturb Alt", "notificationdonotdisturbalt", "NotificationDoNotDisturbAlt", mi(NotificationDoNotDisturbAlt), _g0},
	{"Notification Do Not Disturb Off", "notificationdonotdisturboff", "NotificationDoNotDisturbOff", mi(NotificationDoNotDisturbOff), _g0},
	{"Notification Do Not Disturb On", "notificationdonotdisturbon", "NotificationDoNotDisturbOn", mi(NotificationDoNotDisturbOn), _g0},
	{"Notification Drive ETA", "notificationdriveeta", "NotificationDriveETA", mi(NotificationDriveETA), _g0},
	{"Notification Enhanced Encryption", "notificationenhancedencryption", "NotificationEnhancedEncryption", mi(NotificationEnhancedEncryption), _g0},
	{"Notification Event Available", "notificationeventavailable", "NotificationEventAvailable", mi(NotificationEventAvailable), _g0},
	{"Notification Event Busy", "notificationeventbusy", "NotificationEventBusy", mi(NotificationEventBusy), _g0},
	{"Notification Event Note", "notificationeventnote", "NotificationEventNote", mi(NotificationEventNote), _g0},
	{"Notification Folder Special", "notificationfolderspecial", "NotificationFolderSpecial", mi(NotificationFolderSpecial), _g0},
	{"Notification Live TV", "notificationlivetv", "NotificationLiveTV", mi(NotificationLiveTV), _g0},
	{"Notification MMS", "notificationmms", "NotificationMMS", mi(NotificationMMS), _g0},
	{"Notification More", "notificationmore", "NotificationMore", mi(NotificationMore), _g0},
	{"Notification Network Check", "notificationnetworkcheck", "NotificationNetworkCheck", mi(NotificationNetworkCheck), _g0},
	{"Notification Network Locked", "notificationnetworklocked", "NotificationNetworkLocked", mi(NotificationNetworkLocked), _g0},
	{"Notification No Encryption", "notificationnoencryption", "NotificationNoEncryption", mi(NotificationNoEncryption), _g0},
	{"Notification On Demand Video", "notificationondemandvideo", "NotificationOnDemandVideo", mi(NotificationOnDemandVideo), _g0},
	{"Notification Personal Video", "notificationpersonalvideo", "NotificationPersonalVideo", mi(NotificationPersonalVideo), _g0},
	{"Notification Phone Bluetooth Speaker", "notificationphonebluetoothspeaker", "NotificationPhoneBluetoothSpeaker", mi(NotificationPhoneBluetoothSpeaker), _g0},
	{"Notification Phone Forwarded", "notificationphoneforwarded", "NotificationPhoneForwarded", mi(NotificationPhoneForwarded), _g0},
	{"Notification Phone In Talk", "notificationphoneintalk", "NotificationPhoneInTalk", mi(NotificationPhoneInTalk), _g0},
	{"Notification Phone Locked", "notificationphonelocked", "NotificationPhoneLocked", mi(NotificationPhoneLocked), _g0},
	{"Notification Phone Missed", "notificationphonemissed", "NotificationPhoneMissed", mi(NotificationPhoneMissed), _g0},
	{"Notification Phone Paused", "notificationphonepaused", "NotificationPhonePaused", mi(NotificationPhonePaused), _g0},
	{"Notification Power", "notificationpower", "NotificationPower", mi(NotificationPower), _g0},
	{"Notification Priority High", "notificationpriorityhigh", "NotificationPriorityHigh", mi(NotificationPriorityHigh), _g0},
	{"Notification RV Hookup", "notificationrvhookup", "NotificationRVHookup", mi(NotificationRVHookup), _g0},
	{"Notification SD Card", "notificationsdcard", "NotificationSDCard", mi(NotificationSDCard), _g0},
	{"Notification SIM Card Alert", "notificationsimcardalert", "NotificationSIMCardAlert", mi(NotificationSIMCardAlert), _g0},
	{"Notification SMS", "notificationsms", "NotificationSMS", mi(NotificationSMS), _g0},
	{"Notification SMS Failed", "notificationsmsfailed", "NotificationSMSFailed", mi(NotificationSMSFailed), _g0},
	{"Notification Sync", "notificationsync", "NotificationSync", mi(NotificationSync), _g0},
	{"Notification Sync Disabled", "notificationsyncdisabled", "NotificationSyncDisabled", mi(NotificationSyncDisabled), _g0},
	{"Notification Sync Problem", "notificationsyncproblem", "NotificationSyncProblem", mi(NotificationSyncProblem), _g0},
	{"Notification System Update", "notificationsystemupdate", "NotificationSystemUpdate", mi(NotificationSystemUpdate), _g0},
	{"Notification Tap And Play", "notificationtapandplay", "NotificationTapAndPlay", mi(NotificationTapAndPlay), _g0},
	{"Notification Time To Leave", "notificationtimetoleave", "NotificationTimeToLeave", mi(NotificationTimeToLeave), _g0},
	{"Notification VPN Lock", "notificationvpnlock", "NotificationVPNLock", mi(NotificationVPNLock), _g0},
	{"Notification Vibration", "notificationvibration", "NotificationVibration", mi(NotificationVibration), _g0},
	{"Notification Voice Chat", "notificationvoicechat", "NotificationVoiceChat", mi(NotificationVoiceChat), _g0},
	{"Notification WC", "notificationwc", "NotificationWC", mi(NotificationWC), _g0},
	{"Notification Wi Fi", "notificationwifi", "NotificationWiFi", mi(NotificationWiFi), _g0},
	{"Places AC Unit", "placesacunit", "PlacesACUnit", mi(PlacesACUnit), _g0},
	{"Places Airport Shuttle", "placesairportshuttle", "PlacesAirportShuttle", mi(PlacesAirportShuttle), _g0},
	{"Places All Inclusive", "placesallinclusive", "PlacesAllInclusive", mi(PlacesAllInclusive), _g0},
	{"Places Beach Access", "placesbeachaccess", "PlacesBeachAccess", mi(PlacesBeachAccess), _g0},
	{"Places Business Center", "placesbusinesscenter", "PlacesBusinessCenter", mi(PlacesBusinessCenter), _g0},
	{"Places Casino", "placescasino", "PlacesCasino", mi(PlacesCasino), _g0},
	{"Places Child Care", "placeschildcare", "PlacesChildCare", mi(PlacesChildCare), _g0},
	{"Places Child Friendly", "placeschildfriendly", "PlacesChildFriendly", mi(PlacesChildFriendly), _g0},
	{"Places Fitness Center", "placesfitnesscenter", "PlacesFitnessCenter", mi(PlacesFitnessCenter), _g0},
	{"Places Free Breakfast", "placesfreebreakfast", "PlacesFreeBreakfast", mi(PlacesFreeBreakfast), _g0},
	{"Places Golf Course", "placesgolfcourse", "PlacesGolfCourse", mi(PlacesGolfCourse), _g0},
	{"Places Hot Tub", "placeshottub", "PlacesHotTub", mi(PlacesHotTub), _g0},
	{"Places Kitchen", "placeskitchen", "PlacesKitchen", mi(PlacesKitchen), _g0},
	{"Places Pool", "placespool", "PlacesPool", mi(PlacesPool), _g0},
	{"Places RV Hookup", "placesrvhookup", "PlacesRVHookup", mi(PlacesRVHookup), _g0},
	{"Places Room Service", "placesroomservice", "PlacesRoomService", mi(PlacesRoomService), _g0},
	{"Places Smoke Free", "placessmokefree", "PlacesSmokeFree", mi(PlacesSmokeFree), _g0},
	{"Places Smoking Rooms", "placessmokingrooms", "PlacesSmokingRooms", mi(PlacesSmokingRooms), _g0},
	{"Places Spa", "placesspa", "PlacesSpa", mi(PlacesSpa), _g0},
	{"Social Cake", "socialcake", "SocialCake", mi(SocialCake), _g0},
	{"Social Domain", "socialdomain", "SocialDomain", mi(SocialDomain), _g0},
	{"Social Group", "socialgroup", "SocialGroup", mi(SocialGroup), _g0},
	{"Social Group Add", "socialgroupadd", "SocialGroupAdd", mi(SocialGroupAdd), _g0},
	{"Social Location City", "sociallocationcity", "SocialLocationCity", mi(SocialLocationCity), _g0},
	{"Social Mood", "socialmood", "SocialMood", mi(SocialMood), _g0},
	{"Social Mood Bad", "socialmoodbad", "SocialMoodBad", mi(SocialMoodBad), _g0},
	{"Social Notifications", "socialnotifications", "SocialNotifications", mi(SocialNotifications), _g0},
	{"Social Notifications Active", "socialnotificationsactive", "SocialNotificationsActive", mi(SocialNotificationsActive), _g0},
	{"Social Notifications None", "socialnotificationsnone", "SocialNotificationsNone", mi(SocialNotificationsNone), _g0},
	{"Social Notifications Off", "socialnotificationsoff", "SocialNotificationsOff", mi(SocialNotificationsOff), _g0},
	{"Social Notifications Paused", "socialnotificationspaused", "SocialNotificationsPaused", mi(SocialNotificationsPaused), _g0},
	{"Social Pages", "socialpages", "SocialPages", mi(SocialPages), _g0},
	{"Social Party Mode", "socialpartymode", "SocialPartyMode", mi(SocialPartyMode), _g0},
	{"Social People", "socialpeople", "SocialPeople", mi(SocialPeople), _g0},
	{"Social People Outline", "socialpeopleoutline", "SocialPeopleOutline", mi(SocialPeopleOutline), _g0},
	{"Social Person", "socialperson", "SocialPerson", mi(SocialPerson), _g0},
	{"Social Person Add", "socialpersonadd", "SocialPersonAdd", mi(SocialPersonAdd), _g0},
	{"Social Person Outline", "socialpersonoutline", "SocialPersonOutline", mi(SocialPersonOutline), _g0},
	{"Social Plus One", "socialplusone", "SocialPlusOne", mi(SocialPlusOne), _g0},
	{"Social Poll", "socialpoll", "SocialPoll", mi(SocialPoll), _g0},
	{"Social Public", "socialpublic", "SocialPublic", mi(SocialPublic), _g0},
	{"Social School", "socialschool", "SocialSchool", mi(SocialSchool), _g0},
	{"Social Sentiment Dissatisfied", "socialsentimentdissatisfied", "SocialSentimentDissatisfied", mi(SocialSentimentDissatisfied), _g0},
	{"Social Sentiment Neutral", "socialsentimentneutral", "SocialSentimentNeutral", mi(SocialSentimentNeutral), _g0},
	{"Social Sentiment Satisfied", "socialsentimentsatisfied", "SocialSentimentSatisfied", mi(SocialSentimentSatisfied), _g0},
	{"Social Sentiment Very Dissatisfied", "socialsentimentverydissatisfied", "SocialSentimentVeryDissatisfied", mi(SocialSentimentVeryDissatisfied), _g0},
	{"Social Sentiment Very Satisfied", "socialsentimentverysatisfied", "SocialSentimentVerySatisfied", mi(SocialSentimentVerySatisfied), _g0},
	{"Social Share", "socialshare", "SocialShare", mi(SocialShare), _g0},
	{"Social Whats Hot", "socialwhatshot", "SocialWhatsHot", mi(SocialWhatsHot), _g0},
	{"Toggle Check Box", "togglecheckbox", "ToggleCheckBox", mi(ToggleCheckBox), _g0},
	{"Toggle Check Box Outline Blank", "togglecheckboxoutlineblank", "ToggleCheckBoxOutlineBlank", mi(ToggleCheckBoxOutlineBlank), _g0},
	{"Toggle Indeterminate Check Box", "toggleindeterminatecheckbox", "ToggleIndeterminateCheckBox", mi(ToggleIndeterminateCheckBox), _g0},
	{"Toggle Radio Button Checked", "toggleradiobuttonchecked", "ToggleRadioButtonChecked", mi(ToggleRadioButtonChecked), _g0},
	{"Toggle Radio Button Unchecked", "toggleradiobuttonunchecked", "ToggleRadioButtonUnchecked", mi(ToggleRadioButtonUnchecked), _g0},
	{"Toggle Star", "togglestar", "ToggleStar", mi(ToggleStar), _g0},
	{"Toggle Star Border", "togglestarborder", "ToggleStarBorder", mi(ToggleStarBorder), _g0},
	{"Toggle Star Half", "togglestarhalf", "ToggleStarHalf", mi(ToggleStarHalf), _g0},
}
