// This is generated code. DO NOT EDIT
package main

import (
	"gioui.org/gesture"
	. "golang.org/x/exp/shiny/materialdesign/icons"
)

var (
	allIndices  [961]int
	entryClicks [961]gesture.Click
)

func init() {
	for i := 0; i < len(allIndices); i++ {
		allIndices[i] = i
	}
}

var allEntries = [...]iconEntry{
	{"AVAV Timer", "avavtimer", "AVAVTimer", mi(AVAVTimer)},
	{"AV Add To Queue", "avaddtoqueue", "AVAddToQueue", mi(AVAddToQueue)},
	{"AV Airplay", "avairplay", "AVAirplay", mi(AVAirplay)},
	{"AV Album", "avalbum", "AVAlbum", mi(AVAlbum)},
	{"AV Art Track", "avarttrack", "AVArtTrack", mi(AVArtTrack)},
	{"AV Branding Watermark", "avbrandingwatermark", "AVBrandingWatermark", mi(AVBrandingWatermark)},
	{"AV Call To Action", "avcalltoaction", "AVCallToAction", mi(AVCallToAction)},
	{"AV Closed Caption", "avclosedcaption", "AVClosedCaption", mi(AVClosedCaption)},
	{"AV Equalizer", "avequalizer", "AVEqualizer", mi(AVEqualizer)},
	{"AV Explicit", "avexplicit", "AVExplicit", mi(AVExplicit)},
	{"AV Fast Forward", "avfastforward", "AVFastForward", mi(AVFastForward)},
	{"AV Fast Rewind", "avfastrewind", "AVFastRewind", mi(AVFastRewind)},
	{"AV Featured Play List", "avfeaturedplaylist", "AVFeaturedPlayList", mi(AVFeaturedPlayList)},
	{"AV Featured Video", "avfeaturedvideo", "AVFeaturedVideo", mi(AVFeaturedVideo)},
	{"AV Fiber DVR", "avfiberdvr", "AVFiberDVR", mi(AVFiberDVR)},
	{"AV Fiber Manual Record", "avfibermanualrecord", "AVFiberManualRecord", mi(AVFiberManualRecord)},
	{"AV Fiber New", "avfibernew", "AVFiberNew", mi(AVFiberNew)},
	{"AV Fiber Pin", "avfiberpin", "AVFiberPin", mi(AVFiberPin)},
	{"AV Fiber Smart Record", "avfibersmartrecord", "AVFiberSmartRecord", mi(AVFiberSmartRecord)},
	{"AV Forward 10", "avforward10", "AVForward10", mi(AVForward10)},
	{"AV Forward 30", "avforward30", "AVForward30", mi(AVForward30)},
	{"AV Forward 5", "avforward5", "AVForward5", mi(AVForward5)},
	{"AV Games", "avgames", "AVGames", mi(AVGames)},
	{"AVHD", "avhd", "AVHD", mi(AVHD)},
	{"AV Hearing", "avhearing", "AVHearing", mi(AVHearing)},
	{"AV High Quality", "avhighquality", "AVHighQuality", mi(AVHighQuality)},
	{"AV Library Add", "avlibraryadd", "AVLibraryAdd", mi(AVLibraryAdd)},
	{"AV Library Books", "avlibrarybooks", "AVLibraryBooks", mi(AVLibraryBooks)},
	{"AV Library Music", "avlibrarymusic", "AVLibraryMusic", mi(AVLibraryMusic)},
	{"AV Loop", "avloop", "AVLoop", mi(AVLoop)},
	{"AV Mic", "avmic", "AVMic", mi(AVMic)},
	{"AV Mic None", "avmicnone", "AVMicNone", mi(AVMicNone)},
	{"AV Mic Off", "avmicoff", "AVMicOff", mi(AVMicOff)},
	{"AV Movie", "avmovie", "AVMovie", mi(AVMovie)},
	{"AV Music Video", "avmusicvideo", "AVMusicVideo", mi(AVMusicVideo)},
	{"AV New Releases", "avnewreleases", "AVNewReleases", mi(AVNewReleases)},
	{"AV Not Interested", "avnotinterested", "AVNotInterested", mi(AVNotInterested)},
	{"AV Note", "avnote", "AVNote", mi(AVNote)},
	{"AV Pause", "avpause", "AVPause", mi(AVPause)},
	{"AV Pause Circle Filled", "avpausecirclefilled", "AVPauseCircleFilled", mi(AVPauseCircleFilled)},
	{"AV Pause Circle Outline", "avpausecircleoutline", "AVPauseCircleOutline", mi(AVPauseCircleOutline)},
	{"AV Play Arrow", "avplayarrow", "AVPlayArrow", mi(AVPlayArrow)},
	{"AV Play Circle Filled", "avplaycirclefilled", "AVPlayCircleFilled", mi(AVPlayCircleFilled)},
	{"AV Play Circle Outline", "avplaycircleoutline", "AVPlayCircleOutline", mi(AVPlayCircleOutline)},
	{"AV Playlist Add", "avplaylistadd", "AVPlaylistAdd", mi(AVPlaylistAdd)},
	{"AV Playlist Add Check", "avplaylistaddcheck", "AVPlaylistAddCheck", mi(AVPlaylistAddCheck)},
	{"AV Playlist Play", "avplaylistplay", "AVPlaylistPlay", mi(AVPlaylistPlay)},
	{"AV Queue", "avqueue", "AVQueue", mi(AVQueue)},
	{"AV Queue Music", "avqueuemusic", "AVQueueMusic", mi(AVQueueMusic)},
	{"AV Queue Play Next", "avqueueplaynext", "AVQueuePlayNext", mi(AVQueuePlayNext)},
	{"AV Radio", "avradio", "AVRadio", mi(AVRadio)},
	{"AV Recent Actors", "avrecentactors", "AVRecentActors", mi(AVRecentActors)},
	{"AV Remove From Queue", "avremovefromqueue", "AVRemoveFromQueue", mi(AVRemoveFromQueue)},
	{"AV Repeat", "avrepeat", "AVRepeat", mi(AVRepeat)},
	{"AV Repeat One", "avrepeatone", "AVRepeatOne", mi(AVRepeatOne)},
	{"AV Replay", "avreplay", "AVReplay", mi(AVReplay)},
	{"AV Replay 10", "avreplay10", "AVReplay10", mi(AVReplay10)},
	{"AV Replay 30", "avreplay30", "AVReplay30", mi(AVReplay30)},
	{"AV Replay 5", "avreplay5", "AVReplay5", mi(AVReplay5)},
	{"AV Shuffle", "avshuffle", "AVShuffle", mi(AVShuffle)},
	{"AV Skip Next", "avskipnext", "AVSkipNext", mi(AVSkipNext)},
	{"AV Skip Previous", "avskipprevious", "AVSkipPrevious", mi(AVSkipPrevious)},
	{"AV Slow Motion Video", "avslowmotionvideo", "AVSlowMotionVideo", mi(AVSlowMotionVideo)},
	{"AV Snooze", "avsnooze", "AVSnooze", mi(AVSnooze)},
	{"AV Sort By Alpha", "avsortbyalpha", "AVSortByAlpha", mi(AVSortByAlpha)},
	{"AV Stop", "avstop", "AVStop", mi(AVStop)},
	{"AV Subscriptions", "avsubscriptions", "AVSubscriptions", mi(AVSubscriptions)},
	{"AV Subtitles", "avsubtitles", "AVSubtitles", mi(AVSubtitles)},
	{"AV Surround Sound", "avsurroundsound", "AVSurroundSound", mi(AVSurroundSound)},
	{"AV Video Call", "avvideocall", "AVVideoCall", mi(AVVideoCall)},
	{"AV Video Label", "avvideolabel", "AVVideoLabel", mi(AVVideoLabel)},
	{"AV Video Library", "avvideolibrary", "AVVideoLibrary", mi(AVVideoLibrary)},
	{"AV Videocam", "avvideocam", "AVVideocam", mi(AVVideocam)},
	{"AV Videocam Off", "avvideocamoff", "AVVideocamOff", mi(AVVideocamOff)},
	{"AV Volume Down", "avvolumedown", "AVVolumeDown", mi(AVVolumeDown)},
	{"AV Volume Mute", "avvolumemute", "AVVolumeMute", mi(AVVolumeMute)},
	{"AV Volume Off", "avvolumeoff", "AVVolumeOff", mi(AVVolumeOff)},
	{"AV Volume Up", "avvolumeup", "AVVolumeUp", mi(AVVolumeUp)},
	{"AV Web", "avweb", "AVWeb", mi(AVWeb)},
	{"AV Web Asset", "avwebasset", "AVWebAsset", mi(AVWebAsset)},
	{"Action 3 D Rotation", "action3drotation", "Action3DRotation", mi(Action3DRotation)},
	{"Action Accessibility", "actionaccessibility", "ActionAccessibility", mi(ActionAccessibility)},
	{"Action Accessible", "actionaccessible", "ActionAccessible", mi(ActionAccessible)},
	{"Action Account Balance", "actionaccountbalance", "ActionAccountBalance", mi(ActionAccountBalance)},
	{"Action Account Balance Wallet", "actionaccountbalancewallet", "ActionAccountBalanceWallet", mi(ActionAccountBalanceWallet)},
	{"Action Account Box", "actionaccountbox", "ActionAccountBox", mi(ActionAccountBox)},
	{"Action Account Circle", "actionaccountcircle", "ActionAccountCircle", mi(ActionAccountCircle)},
	{"Action Add Shopping Cart", "actionaddshoppingcart", "ActionAddShoppingCart", mi(ActionAddShoppingCart)},
	{"Action Alarm", "actionalarm", "ActionAlarm", mi(ActionAlarm)},
	{"Action Alarm Add", "actionalarmadd", "ActionAlarmAdd", mi(ActionAlarmAdd)},
	{"Action Alarm Off", "actionalarmoff", "ActionAlarmOff", mi(ActionAlarmOff)},
	{"Action Alarm On", "actionalarmon", "ActionAlarmOn", mi(ActionAlarmOn)},
	{"Action All Out", "actionallout", "ActionAllOut", mi(ActionAllOut)},
	{"Action Android", "actionandroid", "ActionAndroid", mi(ActionAndroid)},
	{"Action Announcement", "actionannouncement", "ActionAnnouncement", mi(ActionAnnouncement)},
	{"Action Aspect Ratio", "actionaspectratio", "ActionAspectRatio", mi(ActionAspectRatio)},
	{"Action Assessment", "actionassessment", "ActionAssessment", mi(ActionAssessment)},
	{"Action Assignment", "actionassignment", "ActionAssignment", mi(ActionAssignment)},
	{"Action Assignment Ind", "actionassignmentind", "ActionAssignmentInd", mi(ActionAssignmentInd)},
	{"Action Assignment Late", "actionassignmentlate", "ActionAssignmentLate", mi(ActionAssignmentLate)},
	{"Action Assignment Return", "actionassignmentreturn", "ActionAssignmentReturn", mi(ActionAssignmentReturn)},
	{"Action Assignment Returned", "actionassignmentreturned", "ActionAssignmentReturned", mi(ActionAssignmentReturned)},
	{"Action Assignment Turned In", "actionassignmentturnedin", "ActionAssignmentTurnedIn", mi(ActionAssignmentTurnedIn)},
	{"Action Autorenew", "actionautorenew", "ActionAutorenew", mi(ActionAutorenew)},
	{"Action Backup", "actionbackup", "ActionBackup", mi(ActionBackup)},
	{"Action Book", "actionbook", "ActionBook", mi(ActionBook)},
	{"Action Bookmark", "actionbookmark", "ActionBookmark", mi(ActionBookmark)},
	{"Action Bookmark Border", "actionbookmarkborder", "ActionBookmarkBorder", mi(ActionBookmarkBorder)},
	{"Action Bug Report", "actionbugreport", "ActionBugReport", mi(ActionBugReport)},
	{"Action Build", "actionbuild", "ActionBuild", mi(ActionBuild)},
	{"Action Cached", "actioncached", "ActionCached", mi(ActionCached)},
	{"Action Camera Enhance", "actioncameraenhance", "ActionCameraEnhance", mi(ActionCameraEnhance)},
	{"Action Card Giftcard", "actioncardgiftcard", "ActionCardGiftcard", mi(ActionCardGiftcard)},
	{"Action Card Membership", "actioncardmembership", "ActionCardMembership", mi(ActionCardMembership)},
	{"Action Card Travel", "actioncardtravel", "ActionCardTravel", mi(ActionCardTravel)},
	{"Action Change History", "actionchangehistory", "ActionChangeHistory", mi(ActionChangeHistory)},
	{"Action Check Circle", "actioncheckcircle", "ActionCheckCircle", mi(ActionCheckCircle)},
	{"Action Chrome Reader Mode", "actionchromereadermode", "ActionChromeReaderMode", mi(ActionChromeReaderMode)},
	{"Action Class", "actionclass", "ActionClass", mi(ActionClass)},
	{"Action Code", "actioncode", "ActionCode", mi(ActionCode)},
	{"Action Compare Arrows", "actioncomparearrows", "ActionCompareArrows", mi(ActionCompareArrows)},
	{"Action Copyright", "actioncopyright", "ActionCopyright", mi(ActionCopyright)},
	{"Action Credit Card", "actioncreditcard", "ActionCreditCard", mi(ActionCreditCard)},
	{"Action DNS", "actiondns", "ActionDNS", mi(ActionDNS)},
	{"Action Dashboard", "actiondashboard", "ActionDashboard", mi(ActionDashboard)},
	{"Action Date Range", "actiondaterange", "ActionDateRange", mi(ActionDateRange)},
	{"Action Delete", "actiondelete", "ActionDelete", mi(ActionDelete)},
	{"Action Delete Forever", "actiondeleteforever", "ActionDeleteForever", mi(ActionDeleteForever)},
	{"Action Description", "actiondescription", "ActionDescription", mi(ActionDescription)},
	{"Action Done", "actiondone", "ActionDone", mi(ActionDone)},
	{"Action Done All", "actiondoneall", "ActionDoneAll", mi(ActionDoneAll)},
	{"Action Donut Large", "actiondonutlarge", "ActionDonutLarge", mi(ActionDonutLarge)},
	{"Action Donut Small", "actiondonutsmall", "ActionDonutSmall", mi(ActionDonutSmall)},
	{"Action Eject", "actioneject", "ActionEject", mi(ActionEject)},
	{"Action Euro Symbol", "actioneurosymbol", "ActionEuroSymbol", mi(ActionEuroSymbol)},
	{"Action Event", "actionevent", "ActionEvent", mi(ActionEvent)},
	{"Action Event Seat", "actioneventseat", "ActionEventSeat", mi(ActionEventSeat)},
	{"Action Exit To App", "actionexittoapp", "ActionExitToApp", mi(ActionExitToApp)},
	{"Action Explore", "actionexplore", "ActionExplore", mi(ActionExplore)},
	{"Action Extension", "actionextension", "ActionExtension", mi(ActionExtension)},
	{"Action Face", "actionface", "ActionFace", mi(ActionFace)},
	{"Action Favorite", "actionfavorite", "ActionFavorite", mi(ActionFavorite)},
	{"Action Favorite Border", "actionfavoriteborder", "ActionFavoriteBorder", mi(ActionFavoriteBorder)},
	{"Action Feedback", "actionfeedback", "ActionFeedback", mi(ActionFeedback)},
	{"Action Find In Page", "actionfindinpage", "ActionFindInPage", mi(ActionFindInPage)},
	{"Action Find Replace", "actionfindreplace", "ActionFindReplace", mi(ActionFindReplace)},
	{"Action Fingerprint", "actionfingerprint", "ActionFingerprint", mi(ActionFingerprint)},
	{"Action Flight Land", "actionflightland", "ActionFlightLand", mi(ActionFlightLand)},
	{"Action Flight Takeoff", "actionflighttakeoff", "ActionFlightTakeoff", mi(ActionFlightTakeoff)},
	{"Action Flip To Back", "actionfliptoback", "ActionFlipToBack", mi(ActionFlipToBack)},
	{"Action Flip To Front", "actionfliptofront", "ActionFlipToFront", mi(ActionFlipToFront)},
	{"Action GIF", "actiongif", "ActionGIF", mi(ActionGIF)},
	{"Action G Translate", "actiongtranslate", "ActionGTranslate", mi(ActionGTranslate)},
	{"Action Gavel", "actiongavel", "ActionGavel", mi(ActionGavel)},
	{"Action Get App", "actiongetapp", "ActionGetApp", mi(ActionGetApp)},
	{"Action Grade", "actiongrade", "ActionGrade", mi(ActionGrade)},
	{"Action Group Work", "actiongroupwork", "ActionGroupWork", mi(ActionGroupWork)},
	{"Action HTTP", "actionhttp", "ActionHTTP", mi(ActionHTTP)},
	{"Action HTTPS", "actionhttps", "ActionHTTPS", mi(ActionHTTPS)},
	{"Action Help", "actionhelp", "ActionHelp", mi(ActionHelp)},
	{"Action Help Outline", "actionhelpoutline", "ActionHelpOutline", mi(ActionHelpOutline)},
	{"Action Highlight Off", "actionhighlightoff", "ActionHighlightOff", mi(ActionHighlightOff)},
	{"Action History", "actionhistory", "ActionHistory", mi(ActionHistory)},
	{"Action Home", "actionhome", "ActionHome", mi(ActionHome)},
	{"Action Hourglass Empty", "actionhourglassempty", "ActionHourglassEmpty", mi(ActionHourglassEmpty)},
	{"Action Hourglass Full", "actionhourglassfull", "ActionHourglassFull", mi(ActionHourglassFull)},
	{"Action Important Devices", "actionimportantdevices", "ActionImportantDevices", mi(ActionImportantDevices)},
	{"Action Info", "actioninfo", "ActionInfo", mi(ActionInfo)},
	{"Action Info Outline", "actioninfooutline", "ActionInfoOutline", mi(ActionInfoOutline)},
	{"Action Input", "actioninput", "ActionInput", mi(ActionInput)},
	{"Action Invert Colors", "actioninvertcolors", "ActionInvertColors", mi(ActionInvertColors)},
	{"Action Label", "actionlabel", "ActionLabel", mi(ActionLabel)},
	{"Action Label Outline", "actionlabeloutline", "ActionLabelOutline", mi(ActionLabelOutline)},
	{"Action Language", "actionlanguage", "ActionLanguage", mi(ActionLanguage)},
	{"Action Launch", "actionlaunch", "ActionLaunch", mi(ActionLaunch)},
	{"Action Lightbulb Outline", "actionlightbulboutline", "ActionLightbulbOutline", mi(ActionLightbulbOutline)},
	{"Action Line Style", "actionlinestyle", "ActionLineStyle", mi(ActionLineStyle)},
	{"Action Line Weight", "actionlineweight", "ActionLineWeight", mi(ActionLineWeight)},
	{"Action List", "actionlist", "ActionList", mi(ActionList)},
	{"Action Lock", "actionlock", "ActionLock", mi(ActionLock)},
	{"Action Lock Open", "actionlockopen", "ActionLockOpen", mi(ActionLockOpen)},
	{"Action Lock Outline", "actionlockoutline", "ActionLockOutline", mi(ActionLockOutline)},
	{"Action Loyalty", "actionloyalty", "ActionLoyalty", mi(ActionLoyalty)},
	{"Action Mark Unread Mailbox", "actionmarkunreadmailbox", "ActionMarkUnreadMailbox", mi(ActionMarkUnreadMailbox)},
	{"Action Motorcycle", "actionmotorcycle", "ActionMotorcycle", mi(ActionMotorcycle)},
	{"Action Note Add", "actionnoteadd", "ActionNoteAdd", mi(ActionNoteAdd)},
	{"Action Offline Pin", "actionofflinepin", "ActionOfflinePin", mi(ActionOfflinePin)},
	{"Action Opacity", "actionopacity", "ActionOpacity", mi(ActionOpacity)},
	{"Action Open In Browser", "actionopeninbrowser", "ActionOpenInBrowser", mi(ActionOpenInBrowser)},
	{"Action Open In New", "actionopeninnew", "ActionOpenInNew", mi(ActionOpenInNew)},
	{"Action Open With", "actionopenwith", "ActionOpenWith", mi(ActionOpenWith)},
	{"Action Pageview", "actionpageview", "ActionPageview", mi(ActionPageview)},
	{"Action Pan Tool", "actionpantool", "ActionPanTool", mi(ActionPanTool)},
	{"Action Payment", "actionpayment", "ActionPayment", mi(ActionPayment)},
	{"Action Perm Camera Mic", "actionpermcameramic", "ActionPermCameraMic", mi(ActionPermCameraMic)},
	{"Action Perm Contact Calendar", "actionpermcontactcalendar", "ActionPermContactCalendar", mi(ActionPermContactCalendar)},
	{"Action Perm Data Setting", "actionpermdatasetting", "ActionPermDataSetting", mi(ActionPermDataSetting)},
	{"Action Perm Device Information", "actionpermdeviceinformation", "ActionPermDeviceInformation", mi(ActionPermDeviceInformation)},
	{"Action Perm Identity", "actionpermidentity", "ActionPermIdentity", mi(ActionPermIdentity)},
	{"Action Perm Media", "actionpermmedia", "ActionPermMedia", mi(ActionPermMedia)},
	{"Action Perm Phone Msg", "actionpermphonemsg", "ActionPermPhoneMsg", mi(ActionPermPhoneMsg)},
	{"Action Perm Scan Wi Fi", "actionpermscanwifi", "ActionPermScanWiFi", mi(ActionPermScanWiFi)},
	{"Action Pets", "actionpets", "ActionPets", mi(ActionPets)},
	{"Action Picture In Picture", "actionpictureinpicture", "ActionPictureInPicture", mi(ActionPictureInPicture)},
	{"Action Picture In Picture Alt", "actionpictureinpicturealt", "ActionPictureInPictureAlt", mi(ActionPictureInPictureAlt)},
	{"Action Play For Work", "actionplayforwork", "ActionPlayForWork", mi(ActionPlayForWork)},
	{"Action Polymer", "actionpolymer", "ActionPolymer", mi(ActionPolymer)},
	{"Action Power Settings New", "actionpowersettingsnew", "ActionPowerSettingsNew", mi(ActionPowerSettingsNew)},
	{"Action Pregnant Woman", "actionpregnantwoman", "ActionPregnantWoman", mi(ActionPregnantWoman)},
	{"Action Print", "actionprint", "ActionPrint", mi(ActionPrint)},
	{"Action Query Builder", "actionquerybuilder", "ActionQueryBuilder", mi(ActionQueryBuilder)},
	{"Action Question Answer", "actionquestionanswer", "ActionQuestionAnswer", mi(ActionQuestionAnswer)},
	{"Action Receipt", "actionreceipt", "ActionReceipt", mi(ActionReceipt)},
	{"Action Record Voice Over", "actionrecordvoiceover", "ActionRecordVoiceOver", mi(ActionRecordVoiceOver)},
	{"Action Redeem", "actionredeem", "ActionRedeem", mi(ActionRedeem)},
	{"Action Remove Shopping Cart", "actionremoveshoppingcart", "ActionRemoveShoppingCart", mi(ActionRemoveShoppingCart)},
	{"Action Reorder", "actionreorder", "ActionReorder", mi(ActionReorder)},
	{"Action Report Problem", "actionreportproblem", "ActionReportProblem", mi(ActionReportProblem)},
	{"Action Restore", "actionrestore", "ActionRestore", mi(ActionRestore)},
	{"Action Restore Page", "actionrestorepage", "ActionRestorePage", mi(ActionRestorePage)},
	{"Action Room", "actionroom", "ActionRoom", mi(ActionRoom)},
	{"Action Rounded Corner", "actionroundedcorner", "ActionRoundedCorner", mi(ActionRoundedCorner)},
	{"Action Rowing", "actionrowing", "ActionRowing", mi(ActionRowing)},
	{"Action Schedule", "actionschedule", "ActionSchedule", mi(ActionSchedule)},
	{"Action Search", "actionsearch", "ActionSearch", mi(ActionSearch)},
	{"Action Settings", "actionsettings", "ActionSettings", mi(ActionSettings)},
	{"Action Settings Applications", "actionsettingsapplications", "ActionSettingsApplications", mi(ActionSettingsApplications)},
	{"Action Settings Backup Restore", "actionsettingsbackuprestore", "ActionSettingsBackupRestore", mi(ActionSettingsBackupRestore)},
	{"Action Settings Bluetooth", "actionsettingsbluetooth", "ActionSettingsBluetooth", mi(ActionSettingsBluetooth)},
	{"Action Settings Brightness", "actionsettingsbrightness", "ActionSettingsBrightness", mi(ActionSettingsBrightness)},
	{"Action Settings Cell", "actionsettingscell", "ActionSettingsCell", mi(ActionSettingsCell)},
	{"Action Settings Ethernet", "actionsettingsethernet", "ActionSettingsEthernet", mi(ActionSettingsEthernet)},
	{"Action Settings Input Antenna", "actionsettingsinputantenna", "ActionSettingsInputAntenna", mi(ActionSettingsInputAntenna)},
	{"Action Settings Input Component", "actionsettingsinputcomponent", "ActionSettingsInputComponent", mi(ActionSettingsInputComponent)},
	{"Action Settings Input Composite", "actionsettingsinputcomposite", "ActionSettingsInputComposite", mi(ActionSettingsInputComposite)},
	{"Action Settings Input HDMI", "actionsettingsinputhdmi", "ActionSettingsInputHDMI", mi(ActionSettingsInputHDMI)},
	{"Action Settings Input S Video", "actionsettingsinputsvideo", "ActionSettingsInputSVideo", mi(ActionSettingsInputSVideo)},
	{"Action Settings Overscan", "actionsettingsoverscan", "ActionSettingsOverscan", mi(ActionSettingsOverscan)},
	{"Action Settings Phone", "actionsettingsphone", "ActionSettingsPhone", mi(ActionSettingsPhone)},
	{"Action Settings Power", "actionsettingspower", "ActionSettingsPower", mi(ActionSettingsPower)},
	{"Action Settings Remote", "actionsettingsremote", "ActionSettingsRemote", mi(ActionSettingsRemote)},
	{"Action Settings Voice", "actionsettingsvoice", "ActionSettingsVoice", mi(ActionSettingsVoice)},
	{"Action Shop", "actionshop", "ActionShop", mi(ActionShop)},
	{"Action Shop Two", "actionshoptwo", "ActionShopTwo", mi(ActionShopTwo)},
	{"Action Shopping Basket", "actionshoppingbasket", "ActionShoppingBasket", mi(ActionShoppingBasket)},
	{"Action Shopping Cart", "actionshoppingcart", "ActionShoppingCart", mi(ActionShoppingCart)},
	{"Action Speaker Notes", "actionspeakernotes", "ActionSpeakerNotes", mi(ActionSpeakerNotes)},
	{"Action Speaker Notes Off", "actionspeakernotesoff", "ActionSpeakerNotesOff", mi(ActionSpeakerNotesOff)},
	{"Action Spellcheck", "actionspellcheck", "ActionSpellcheck", mi(ActionSpellcheck)},
	{"Action Star Rate", "actionstarrate", "ActionStarRate", mi(ActionStarRate)},
	{"Action Stars", "actionstars", "ActionStars", mi(ActionStars)},
	{"Action Store", "actionstore", "ActionStore", mi(ActionStore)},
	{"Action Subject", "actionsubject", "ActionSubject", mi(ActionSubject)},
	{"Action Supervisor Account", "actionsupervisoraccount", "ActionSupervisorAccount", mi(ActionSupervisorAccount)},
	{"Action Swap Horiz", "actionswaphoriz", "ActionSwapHoriz", mi(ActionSwapHoriz)},
	{"Action Swap Vert", "actionswapvert", "ActionSwapVert", mi(ActionSwapVert)},
	{"Action Swap Vertical Circle", "actionswapverticalcircle", "ActionSwapVerticalCircle", mi(ActionSwapVerticalCircle)},
	{"Action System Update Alt", "actionsystemupdatealt", "ActionSystemUpdateAlt", mi(ActionSystemUpdateAlt)},
	{"Action TOC", "actiontoc", "ActionTOC", mi(ActionTOC)},
	{"Action Tab", "actiontab", "ActionTab", mi(ActionTab)},
	{"Action Tab Unselected", "actiontabunselected", "ActionTabUnselected", mi(ActionTabUnselected)},
	{"Action Theaters", "actiontheaters", "ActionTheaters", mi(ActionTheaters)},
	{"Action Thumb Down", "actionthumbdown", "ActionThumbDown", mi(ActionThumbDown)},
	{"Action Thumb Up", "actionthumbup", "ActionThumbUp", mi(ActionThumbUp)},
	{"Action Thumbs Up Down", "actionthumbsupdown", "ActionThumbsUpDown", mi(ActionThumbsUpDown)},
	{"Action Timeline", "actiontimeline", "ActionTimeline", mi(ActionTimeline)},
	{"Action Today", "actiontoday", "ActionToday", mi(ActionToday)},
	{"Action Toll", "actiontoll", "ActionToll", mi(ActionToll)},
	{"Action Touch App", "actiontouchapp", "ActionTouchApp", mi(ActionTouchApp)},
	{"Action Track Changes", "actiontrackchanges", "ActionTrackChanges", mi(ActionTrackChanges)},
	{"Action Translate", "actiontranslate", "ActionTranslate", mi(ActionTranslate)},
	{"Action Trending Down", "actiontrendingdown", "ActionTrendingDown", mi(ActionTrendingDown)},
	{"Action Trending Flat", "actiontrendingflat", "ActionTrendingFlat", mi(ActionTrendingFlat)},
	{"Action Trending Up", "actiontrendingup", "ActionTrendingUp", mi(ActionTrendingUp)},
	{"Action Turned In", "actionturnedin", "ActionTurnedIn", mi(ActionTurnedIn)},
	{"Action Turned In Not", "actionturnedinnot", "ActionTurnedInNot", mi(ActionTurnedInNot)},
	{"Action Update", "actionupdate", "ActionUpdate", mi(ActionUpdate)},
	{"Action Verified User", "actionverifieduser", "ActionVerifiedUser", mi(ActionVerifiedUser)},
	{"Action View Agenda", "actionviewagenda", "ActionViewAgenda", mi(ActionViewAgenda)},
	{"Action View Array", "actionviewarray", "ActionViewArray", mi(ActionViewArray)},
	{"Action View Carousel", "actionviewcarousel", "ActionViewCarousel", mi(ActionViewCarousel)},
	{"Action View Column", "actionviewcolumn", "ActionViewColumn", mi(ActionViewColumn)},
	{"Action View Day", "actionviewday", "ActionViewDay", mi(ActionViewDay)},
	{"Action View Headline", "actionviewheadline", "ActionViewHeadline", mi(ActionViewHeadline)},
	{"Action View List", "actionviewlist", "ActionViewList", mi(ActionViewList)},
	{"Action View Module", "actionviewmodule", "ActionViewModule", mi(ActionViewModule)},
	{"Action View Quilt", "actionviewquilt", "ActionViewQuilt", mi(ActionViewQuilt)},
	{"Action View Stream", "actionviewstream", "ActionViewStream", mi(ActionViewStream)},
	{"Action View Week", "actionviewweek", "ActionViewWeek", mi(ActionViewWeek)},
	{"Action Visibility", "actionvisibility", "ActionVisibility", mi(ActionVisibility)},
	{"Action Visibility Off", "actionvisibilityoff", "ActionVisibilityOff", mi(ActionVisibilityOff)},
	{"Action Watch Later", "actionwatchlater", "ActionWatchLater", mi(ActionWatchLater)},
	{"Action Work", "actionwork", "ActionWork", mi(ActionWork)},
	{"Action Youtube Searched For", "actionyoutubesearchedfor", "ActionYoutubeSearchedFor", mi(ActionYoutubeSearchedFor)},
	{"Action Zoom In", "actionzoomin", "ActionZoomIn", mi(ActionZoomIn)},
	{"Action Zoom Out", "actionzoomout", "ActionZoomOut", mi(ActionZoomOut)},
	{"Alert Add Alert", "alertaddalert", "AlertAddAlert", mi(AlertAddAlert)},
	{"Alert Error", "alerterror", "AlertError", mi(AlertError)},
	{"Alert Error Outline", "alerterroroutline", "AlertErrorOutline", mi(AlertErrorOutline)},
	{"Alert Warning", "alertwarning", "AlertWarning", mi(AlertWarning)},
	{"Communication Business", "communicationbusiness", "CommunicationBusiness", mi(CommunicationBusiness)},
	{"Communication Call", "communicationcall", "CommunicationCall", mi(CommunicationCall)},
	{"Communication Call End", "communicationcallend", "CommunicationCallEnd", mi(CommunicationCallEnd)},
	{"Communication Call Made", "communicationcallmade", "CommunicationCallMade", mi(CommunicationCallMade)},
	{"Communication Call Merge", "communicationcallmerge", "CommunicationCallMerge", mi(CommunicationCallMerge)},
	{"Communication Call Missed", "communicationcallmissed", "CommunicationCallMissed", mi(CommunicationCallMissed)},
	{"Communication Call Missed Outgoing", "communicationcallmissedoutgoing", "CommunicationCallMissedOutgoing", mi(CommunicationCallMissedOutgoing)},
	{"Communication Call Received", "communicationcallreceived", "CommunicationCallReceived", mi(CommunicationCallReceived)},
	{"Communication Call Split", "communicationcallsplit", "CommunicationCallSplit", mi(CommunicationCallSplit)},
	{"Communication Chat", "communicationchat", "CommunicationChat", mi(CommunicationChat)},
	{"Communication Chat Bubble", "communicationchatbubble", "CommunicationChatBubble", mi(CommunicationChatBubble)},
	{"Communication Chat Bubble Outline", "communicationchatbubbleoutline", "CommunicationChatBubbleOutline", mi(CommunicationChatBubbleOutline)},
	{"Communication Clear All", "communicationclearall", "CommunicationClearAll", mi(CommunicationClearAll)},
	{"Communication Comment", "communicationcomment", "CommunicationComment", mi(CommunicationComment)},
	{"Communication Contact Mail", "communicationcontactmail", "CommunicationContactMail", mi(CommunicationContactMail)},
	{"Communication Contact Phone", "communicationcontactphone", "CommunicationContactPhone", mi(CommunicationContactPhone)},
	{"Communication Contacts", "communicationcontacts", "CommunicationContacts", mi(CommunicationContacts)},
	{"Communication Dialer SIP", "communicationdialersip", "CommunicationDialerSIP", mi(CommunicationDialerSIP)},
	{"Communication Dialpad", "communicationdialpad", "CommunicationDialpad", mi(CommunicationDialpad)},
	{"Communication Email", "communicationemail", "CommunicationEmail", mi(CommunicationEmail)},
	{"Communication Forum", "communicationforum", "CommunicationForum", mi(CommunicationForum)},
	{"Communication Import Contacts", "communicationimportcontacts", "CommunicationImportContacts", mi(CommunicationImportContacts)},
	{"Communication Import Export", "communicationimportexport", "CommunicationImportExport", mi(CommunicationImportExport)},
	{"Communication Invert Colors Off", "communicationinvertcolorsoff", "CommunicationInvertColorsOff", mi(CommunicationInvertColorsOff)},
	{"Communication Live Help", "communicationlivehelp", "CommunicationLiveHelp", mi(CommunicationLiveHelp)},
	{"Communication Location Off", "communicationlocationoff", "CommunicationLocationOff", mi(CommunicationLocationOff)},
	{"Communication Location On", "communicationlocationon", "CommunicationLocationOn", mi(CommunicationLocationOn)},
	{"Communication Mail Outline", "communicationmailoutline", "CommunicationMailOutline", mi(CommunicationMailOutline)},
	{"Communication Message", "communicationmessage", "CommunicationMessage", mi(CommunicationMessage)},
	{"Communication No SIM", "communicationnosim", "CommunicationNoSIM", mi(CommunicationNoSIM)},
	{"Communication Phone", "communicationphone", "CommunicationPhone", mi(CommunicationPhone)},
	{"Communication Phone Link Erase", "communicationphonelinkerase", "CommunicationPhoneLinkErase", mi(CommunicationPhoneLinkErase)},
	{"Communication Phone Link Lock", "communicationphonelinklock", "CommunicationPhoneLinkLock", mi(CommunicationPhoneLinkLock)},
	{"Communication Phone Link Ring", "communicationphonelinkring", "CommunicationPhoneLinkRing", mi(CommunicationPhoneLinkRing)},
	{"Communication Phone Link Setup", "communicationphonelinksetup", "CommunicationPhoneLinkSetup", mi(CommunicationPhoneLinkSetup)},
	{"Communication Portable Wi Fi Off", "communicationportablewifioff", "CommunicationPortableWiFiOff", mi(CommunicationPortableWiFiOff)},
	{"Communication Present To All", "communicationpresenttoall", "CommunicationPresentToAll", mi(CommunicationPresentToAll)},
	{"Communication RSS Feed", "communicationrssfeed", "CommunicationRSSFeed", mi(CommunicationRSSFeed)},
	{"Communication Ring Volume", "communicationringvolume", "CommunicationRingVolume", mi(CommunicationRingVolume)},
	{"Communication Screen Share", "communicationscreenshare", "CommunicationScreenShare", mi(CommunicationScreenShare)},
	{"Communication Speaker Phone", "communicationspeakerphone", "CommunicationSpeakerPhone", mi(CommunicationSpeakerPhone)},
	{"Communication Stay Current Landscape", "communicationstaycurrentlandscape", "CommunicationStayCurrentLandscape", mi(CommunicationStayCurrentLandscape)},
	{"Communication Stay Current Portrait", "communicationstaycurrentportrait", "CommunicationStayCurrentPortrait", mi(CommunicationStayCurrentPortrait)},
	{"Communication Stay Primary Landscape", "communicationstayprimarylandscape", "CommunicationStayPrimaryLandscape", mi(CommunicationStayPrimaryLandscape)},
	{"Communication Stay Primary Portrait", "communicationstayprimaryportrait", "CommunicationStayPrimaryPortrait", mi(CommunicationStayPrimaryPortrait)},
	{"Communication Stop Screen Share", "communicationstopscreenshare", "CommunicationStopScreenShare", mi(CommunicationStopScreenShare)},
	{"Communication Swap Calls", "communicationswapcalls", "CommunicationSwapCalls", mi(CommunicationSwapCalls)},
	{"Communication Text SMS", "communicationtextsms", "CommunicationTextSMS", mi(CommunicationTextSMS)},
	{"Communication VPN Key", "communicationvpnkey", "CommunicationVPNKey", mi(CommunicationVPNKey)},
	{"Communication Voicemail", "communicationvoicemail", "CommunicationVoicemail", mi(CommunicationVoicemail)},
	{"Content Add", "contentadd", "ContentAdd", mi(ContentAdd)},
	{"Content Add Box", "contentaddbox", "ContentAddBox", mi(ContentAddBox)},
	{"Content Add Circle", "contentaddcircle", "ContentAddCircle", mi(ContentAddCircle)},
	{"Content Add Circle Outline", "contentaddcircleoutline", "ContentAddCircleOutline", mi(ContentAddCircleOutline)},
	{"Content Archive", "contentarchive", "ContentArchive", mi(ContentArchive)},
	{"Content Backspace", "contentbackspace", "ContentBackspace", mi(ContentBackspace)},
	{"Content Block", "contentblock", "ContentBlock", mi(ContentBlock)},
	{"Content Clear", "contentclear", "ContentClear", mi(ContentClear)},
	{"Content Content Copy", "contentcontentcopy", "ContentContentCopy", mi(ContentContentCopy)},
	{"Content Content Cut", "contentcontentcut", "ContentContentCut", mi(ContentContentCut)},
	{"Content Content Paste", "contentcontentpaste", "ContentContentPaste", mi(ContentContentPaste)},
	{"Content Create", "contentcreate", "ContentCreate", mi(ContentCreate)},
	{"Content Delete Sweep", "contentdeletesweep", "ContentDeleteSweep", mi(ContentDeleteSweep)},
	{"Content Drafts", "contentdrafts", "ContentDrafts", mi(ContentDrafts)},
	{"Content Filter List", "contentfilterlist", "ContentFilterList", mi(ContentFilterList)},
	{"Content Flag", "contentflag", "ContentFlag", mi(ContentFlag)},
	{"Content Font Download", "contentfontdownload", "ContentFontDownload", mi(ContentFontDownload)},
	{"Content Forward", "contentforward", "ContentForward", mi(ContentForward)},
	{"Content Gesture", "contentgesture", "ContentGesture", mi(ContentGesture)},
	{"Content Inbox", "contentinbox", "ContentInbox", mi(ContentInbox)},
	{"Content Link", "contentlink", "ContentLink", mi(ContentLink)},
	{"Content Low Priority", "contentlowpriority", "ContentLowPriority", mi(ContentLowPriority)},
	{"Content Mail", "contentmail", "ContentMail", mi(ContentMail)},
	{"Content Mark Unread", "contentmarkunread", "ContentMarkUnread", mi(ContentMarkUnread)},
	{"Content Move To Inbox", "contentmovetoinbox", "ContentMoveToInbox", mi(ContentMoveToInbox)},
	{"Content Next Week", "contentnextweek", "ContentNextWeek", mi(ContentNextWeek)},
	{"Content Redo", "contentredo", "ContentRedo", mi(ContentRedo)},
	{"Content Remove", "contentremove", "ContentRemove", mi(ContentRemove)},
	{"Content Remove Circle", "contentremovecircle", "ContentRemoveCircle", mi(ContentRemoveCircle)},
	{"Content Remove Circle Outline", "contentremovecircleoutline", "ContentRemoveCircleOutline", mi(ContentRemoveCircleOutline)},
	{"Content Reply", "contentreply", "ContentReply", mi(ContentReply)},
	{"Content Reply All", "contentreplyall", "ContentReplyAll", mi(ContentReplyAll)},
	{"Content Report", "contentreport", "ContentReport", mi(ContentReport)},
	{"Content Save", "contentsave", "ContentSave", mi(ContentSave)},
	{"Content Select All", "contentselectall", "ContentSelectAll", mi(ContentSelectAll)},
	{"Content Send", "contentsend", "ContentSend", mi(ContentSend)},
	{"Content Sort", "contentsort", "ContentSort", mi(ContentSort)},
	{"Content Text Format", "contenttextformat", "ContentTextFormat", mi(ContentTextFormat)},
	{"Content Unarchive", "contentunarchive", "ContentUnarchive", mi(ContentUnarchive)},
	{"Content Undo", "contentundo", "ContentUndo", mi(ContentUndo)},
	{"Content Weekend", "contentweekend", "ContentWeekend", mi(ContentWeekend)},
	{"Device Access Alarm", "deviceaccessalarm", "DeviceAccessAlarm", mi(DeviceAccessAlarm)},
	{"Device Access Alarms", "deviceaccessalarms", "DeviceAccessAlarms", mi(DeviceAccessAlarms)},
	{"Device Access Time", "deviceaccesstime", "DeviceAccessTime", mi(DeviceAccessTime)},
	{"Device Add Alarm", "deviceaddalarm", "DeviceAddAlarm", mi(DeviceAddAlarm)},
	{"Device Airplane Mode Active", "deviceairplanemodeactive", "DeviceAirplaneModeActive", mi(DeviceAirplaneModeActive)},
	{"Device Airplane Mode Inactive", "deviceairplanemodeinactive", "DeviceAirplaneModeInactive", mi(DeviceAirplaneModeInactive)},
	{"Device Battery 20", "devicebattery20", "DeviceBattery20", mi(DeviceBattery20)},
	{"Device Battery 30", "devicebattery30", "DeviceBattery30", mi(DeviceBattery30)},
	{"Device Battery 50", "devicebattery50", "DeviceBattery50", mi(DeviceBattery50)},
	{"Device Battery 60", "devicebattery60", "DeviceBattery60", mi(DeviceBattery60)},
	{"Device Battery 80", "devicebattery80", "DeviceBattery80", mi(DeviceBattery80)},
	{"Device Battery 90", "devicebattery90", "DeviceBattery90", mi(DeviceBattery90)},
	{"Device Battery Alert", "devicebatteryalert", "DeviceBatteryAlert", mi(DeviceBatteryAlert)},
	{"Device Battery Charging 20", "devicebatterycharging20", "DeviceBatteryCharging20", mi(DeviceBatteryCharging20)},
	{"Device Battery Charging 30", "devicebatterycharging30", "DeviceBatteryCharging30", mi(DeviceBatteryCharging30)},
	{"Device Battery Charging 50", "devicebatterycharging50", "DeviceBatteryCharging50", mi(DeviceBatteryCharging50)},
	{"Device Battery Charging 60", "devicebatterycharging60", "DeviceBatteryCharging60", mi(DeviceBatteryCharging60)},
	{"Device Battery Charging 80", "devicebatterycharging80", "DeviceBatteryCharging80", mi(DeviceBatteryCharging80)},
	{"Device Battery Charging 90", "devicebatterycharging90", "DeviceBatteryCharging90", mi(DeviceBatteryCharging90)},
	{"Device Battery Charging Full", "devicebatterychargingfull", "DeviceBatteryChargingFull", mi(DeviceBatteryChargingFull)},
	{"Device Battery Full", "devicebatteryfull", "DeviceBatteryFull", mi(DeviceBatteryFull)},
	{"Device Battery Std", "devicebatterystd", "DeviceBatteryStd", mi(DeviceBatteryStd)},
	{"Device Battery Unknown", "devicebatteryunknown", "DeviceBatteryUnknown", mi(DeviceBatteryUnknown)},
	{"Device Bluetooth", "devicebluetooth", "DeviceBluetooth", mi(DeviceBluetooth)},
	{"Device Bluetooth Connected", "devicebluetoothconnected", "DeviceBluetoothConnected", mi(DeviceBluetoothConnected)},
	{"Device Bluetooth Disabled", "devicebluetoothdisabled", "DeviceBluetoothDisabled", mi(DeviceBluetoothDisabled)},
	{"Device Bluetooth Searching", "devicebluetoothsearching", "DeviceBluetoothSearching", mi(DeviceBluetoothSearching)},
	{"Device Brightness Auto", "devicebrightnessauto", "DeviceBrightnessAuto", mi(DeviceBrightnessAuto)},
	{"Device Brightness High", "devicebrightnesshigh", "DeviceBrightnessHigh", mi(DeviceBrightnessHigh)},
	{"Device Brightness Low", "devicebrightnesslow", "DeviceBrightnessLow", mi(DeviceBrightnessLow)},
	{"Device Brightness Medium", "devicebrightnessmedium", "DeviceBrightnessMedium", mi(DeviceBrightnessMedium)},
	{"Device DVR", "devicedvr", "DeviceDVR", mi(DeviceDVR)},
	{"Device Data Usage", "devicedatausage", "DeviceDataUsage", mi(DeviceDataUsage)},
	{"Device Developer Mode", "devicedevelopermode", "DeviceDeveloperMode", mi(DeviceDeveloperMode)},
	{"Device Devices", "devicedevices", "DeviceDevices", mi(DeviceDevices)},
	{"Device GPS Fixed", "devicegpsfixed", "DeviceGPSFixed", mi(DeviceGPSFixed)},
	{"Device GPS Not Fixed", "devicegpsnotfixed", "DeviceGPSNotFixed", mi(DeviceGPSNotFixed)},
	{"Device GPS Off", "devicegpsoff", "DeviceGPSOff", mi(DeviceGPSOff)},
	{"Device Graphic Eq", "devicegraphiceq", "DeviceGraphicEq", mi(DeviceGraphicEq)},
	{"Device Location Disabled", "devicelocationdisabled", "DeviceLocationDisabled", mi(DeviceLocationDisabled)},
	{"Device Location Searching", "devicelocationsearching", "DeviceLocationSearching", mi(DeviceLocationSearching)},
	{"Device NFC", "devicenfc", "DeviceNFC", mi(DeviceNFC)},
	{"Device Network Cell", "devicenetworkcell", "DeviceNetworkCell", mi(DeviceNetworkCell)},
	{"Device Network Wi Fi", "devicenetworkwifi", "DeviceNetworkWiFi", mi(DeviceNetworkWiFi)},
	{"Device SD Storage", "devicesdstorage", "DeviceSDStorage", mi(DeviceSDStorage)},
	{"Device Screen Lock Landscape", "devicescreenlocklandscape", "DeviceScreenLockLandscape", mi(DeviceScreenLockLandscape)},
	{"Device Screen Lock Portrait", "devicescreenlockportrait", "DeviceScreenLockPortrait", mi(DeviceScreenLockPortrait)},
	{"Device Screen Lock Rotation", "devicescreenlockrotation", "DeviceScreenLockRotation", mi(DeviceScreenLockRotation)},
	{"Device Screen Rotation", "devicescreenrotation", "DeviceScreenRotation", mi(DeviceScreenRotation)},
	{"Device Settings System Daydream", "devicesettingssystemdaydream", "DeviceSettingsSystemDaydream", mi(DeviceSettingsSystemDaydream)},
	{"Device Signal Cellular 0 Bar", "devicesignalcellular0bar", "DeviceSignalCellular0Bar", mi(DeviceSignalCellular0Bar)},
	{"Device Signal Cellular 1 Bar", "devicesignalcellular1bar", "DeviceSignalCellular1Bar", mi(DeviceSignalCellular1Bar)},
	{"Device Signal Cellular 2 Bar", "devicesignalcellular2bar", "DeviceSignalCellular2Bar", mi(DeviceSignalCellular2Bar)},
	{"Device Signal Cellular 3 Bar", "devicesignalcellular3bar", "DeviceSignalCellular3Bar", mi(DeviceSignalCellular3Bar)},
	{"Device Signal Cellular 4 Bar", "devicesignalcellular4bar", "DeviceSignalCellular4Bar", mi(DeviceSignalCellular4Bar)},
	{"Device Signal Cellular Connected No Internet 0 Bar", "devicesignalcellularconnectednointernet0bar", "DeviceSignalCellularConnectedNoInternet0Bar", mi(DeviceSignalCellularConnectedNoInternet0Bar)},
	{"Device Signal Cellular Connected No Internet 1 Bar", "devicesignalcellularconnectednointernet1bar", "DeviceSignalCellularConnectedNoInternet1Bar", mi(DeviceSignalCellularConnectedNoInternet1Bar)},
	{"Device Signal Cellular Connected No Internet 2 Bar", "devicesignalcellularconnectednointernet2bar", "DeviceSignalCellularConnectedNoInternet2Bar", mi(DeviceSignalCellularConnectedNoInternet2Bar)},
	{"Device Signal Cellular Connected No Internet 3 Bar", "devicesignalcellularconnectednointernet3bar", "DeviceSignalCellularConnectedNoInternet3Bar", mi(DeviceSignalCellularConnectedNoInternet3Bar)},
	{"Device Signal Cellular Connected No Internet 4 Bar", "devicesignalcellularconnectednointernet4bar", "DeviceSignalCellularConnectedNoInternet4Bar", mi(DeviceSignalCellularConnectedNoInternet4Bar)},
	{"Device Signal Cellular No SIM", "devicesignalcellularnosim", "DeviceSignalCellularNoSIM", mi(DeviceSignalCellularNoSIM)},
	{"Device Signal Cellular Null", "devicesignalcellularnull", "DeviceSignalCellularNull", mi(DeviceSignalCellularNull)},
	{"Device Signal Cellular Off", "devicesignalcellularoff", "DeviceSignalCellularOff", mi(DeviceSignalCellularOff)},
	{"Device Signal Wi Fi 0 Bar", "devicesignalwifi0bar", "DeviceSignalWiFi0Bar", mi(DeviceSignalWiFi0Bar)},
	{"Device Signal Wi Fi 1 Bar", "devicesignalwifi1bar", "DeviceSignalWiFi1Bar", mi(DeviceSignalWiFi1Bar)},
	{"Device Signal Wi Fi 1 Bar Lock", "devicesignalwifi1barlock", "DeviceSignalWiFi1BarLock", mi(DeviceSignalWiFi1BarLock)},
	{"Device Signal Wi Fi 2 Bar", "devicesignalwifi2bar", "DeviceSignalWiFi2Bar", mi(DeviceSignalWiFi2Bar)},
	{"Device Signal Wi Fi 2 Bar Lock", "devicesignalwifi2barlock", "DeviceSignalWiFi2BarLock", mi(DeviceSignalWiFi2BarLock)},
	{"Device Signal Wi Fi 3 Bar", "devicesignalwifi3bar", "DeviceSignalWiFi3Bar", mi(DeviceSignalWiFi3Bar)},
	{"Device Signal Wi Fi 3 Bar Lock", "devicesignalwifi3barlock", "DeviceSignalWiFi3BarLock", mi(DeviceSignalWiFi3BarLock)},
	{"Device Signal Wi Fi 4 Bar", "devicesignalwifi4bar", "DeviceSignalWiFi4Bar", mi(DeviceSignalWiFi4Bar)},
	{"Device Signal Wi Fi 4 Bar Lock", "devicesignalwifi4barlock", "DeviceSignalWiFi4BarLock", mi(DeviceSignalWiFi4BarLock)},
	{"Device Signal Wi Fi Off", "devicesignalwifioff", "DeviceSignalWiFiOff", mi(DeviceSignalWiFiOff)},
	{"Device Storage", "devicestorage", "DeviceStorage", mi(DeviceStorage)},
	{"Device USB", "deviceusb", "DeviceUSB", mi(DeviceUSB)},
	{"Device Wallpaper", "devicewallpaper", "DeviceWallpaper", mi(DeviceWallpaper)},
	{"Device Wi Fi Lock", "devicewifilock", "DeviceWiFiLock", mi(DeviceWiFiLock)},
	{"Device Wi Fi Tethering", "devicewifitethering", "DeviceWiFiTethering", mi(DeviceWiFiTethering)},
	{"Device Widgets", "devicewidgets", "DeviceWidgets", mi(DeviceWidgets)},
	{"Editor Attach File", "editorattachfile", "EditorAttachFile", mi(EditorAttachFile)},
	{"Editor Attach Money", "editorattachmoney", "EditorAttachMoney", mi(EditorAttachMoney)},
	{"Editor Border All", "editorborderall", "EditorBorderAll", mi(EditorBorderAll)},
	{"Editor Border Bottom", "editorborderbottom", "EditorBorderBottom", mi(EditorBorderBottom)},
	{"Editor Border Clear", "editorborderclear", "EditorBorderClear", mi(EditorBorderClear)},
	{"Editor Border Color", "editorbordercolor", "EditorBorderColor", mi(EditorBorderColor)},
	{"Editor Border Horizontal", "editorborderhorizontal", "EditorBorderHorizontal", mi(EditorBorderHorizontal)},
	{"Editor Border Inner", "editorborderinner", "EditorBorderInner", mi(EditorBorderInner)},
	{"Editor Border Left", "editorborderleft", "EditorBorderLeft", mi(EditorBorderLeft)},
	{"Editor Border Outer", "editorborderouter", "EditorBorderOuter", mi(EditorBorderOuter)},
	{"Editor Border Right", "editorborderright", "EditorBorderRight", mi(EditorBorderRight)},
	{"Editor Border Style", "editorborderstyle", "EditorBorderStyle", mi(EditorBorderStyle)},
	{"Editor Border Top", "editorbordertop", "EditorBorderTop", mi(EditorBorderTop)},
	{"Editor Border Vertical", "editorbordervertical", "EditorBorderVertical", mi(EditorBorderVertical)},
	{"Editor Bubble Chart", "editorbubblechart", "EditorBubbleChart", mi(EditorBubbleChart)},
	{"Editor Drag Handle", "editordraghandle", "EditorDragHandle", mi(EditorDragHandle)},
	{"Editor Format Align Center", "editorformataligncenter", "EditorFormatAlignCenter", mi(EditorFormatAlignCenter)},
	{"Editor Format Align Justify", "editorformatalignjustify", "EditorFormatAlignJustify", mi(EditorFormatAlignJustify)},
	{"Editor Format Align Left", "editorformatalignleft", "EditorFormatAlignLeft", mi(EditorFormatAlignLeft)},
	{"Editor Format Align Right", "editorformatalignright", "EditorFormatAlignRight", mi(EditorFormatAlignRight)},
	{"Editor Format Bold", "editorformatbold", "EditorFormatBold", mi(EditorFormatBold)},
	{"Editor Format Clear", "editorformatclear", "EditorFormatClear", mi(EditorFormatClear)},
	{"Editor Format Color Fill", "editorformatcolorfill", "EditorFormatColorFill", mi(EditorFormatColorFill)},
	{"Editor Format Color Reset", "editorformatcolorreset", "EditorFormatColorReset", mi(EditorFormatColorReset)},
	{"Editor Format Color Text", "editorformatcolortext", "EditorFormatColorText", mi(EditorFormatColorText)},
	{"Editor Format Indent Decrease", "editorformatindentdecrease", "EditorFormatIndentDecrease", mi(EditorFormatIndentDecrease)},
	{"Editor Format Indent Increase", "editorformatindentincrease", "EditorFormatIndentIncrease", mi(EditorFormatIndentIncrease)},
	{"Editor Format Italic", "editorformatitalic", "EditorFormatItalic", mi(EditorFormatItalic)},
	{"Editor Format Line Spacing", "editorformatlinespacing", "EditorFormatLineSpacing", mi(EditorFormatLineSpacing)},
	{"Editor Format List Bulleted", "editorformatlistbulleted", "EditorFormatListBulleted", mi(EditorFormatListBulleted)},
	{"Editor Format List Numbered", "editorformatlistnumbered", "EditorFormatListNumbered", mi(EditorFormatListNumbered)},
	{"Editor Format Paint", "editorformatpaint", "EditorFormatPaint", mi(EditorFormatPaint)},
	{"Editor Format Quote", "editorformatquote", "EditorFormatQuote", mi(EditorFormatQuote)},
	{"Editor Format Shapes", "editorformatshapes", "EditorFormatShapes", mi(EditorFormatShapes)},
	{"Editor Format Size", "editorformatsize", "EditorFormatSize", mi(EditorFormatSize)},
	{"Editor Format Strikethrough", "editorformatstrikethrough", "EditorFormatStrikethrough", mi(EditorFormatStrikethrough)},
	{"Editor Format Text Direction L To R", "editorformattextdirectionltor", "EditorFormatTextDirectionLToR", mi(EditorFormatTextDirectionLToR)},
	{"Editor Format Text Direction R To L", "editorformattextdirectionrtol", "EditorFormatTextDirectionRToL", mi(EditorFormatTextDirectionRToL)},
	{"Editor Format Underlined", "editorformatunderlined", "EditorFormatUnderlined", mi(EditorFormatUnderlined)},
	{"Editor Functions", "editorfunctions", "EditorFunctions", mi(EditorFunctions)},
	{"Editor Highlight", "editorhighlight", "EditorHighlight", mi(EditorHighlight)},
	{"Editor Insert Chart", "editorinsertchart", "EditorInsertChart", mi(EditorInsertChart)},
	{"Editor Insert Comment", "editorinsertcomment", "EditorInsertComment", mi(EditorInsertComment)},
	{"Editor Insert Drive File", "editorinsertdrivefile", "EditorInsertDriveFile", mi(EditorInsertDriveFile)},
	{"Editor Insert Emoticon", "editorinsertemoticon", "EditorInsertEmoticon", mi(EditorInsertEmoticon)},
	{"Editor Insert Invitation", "editorinsertinvitation", "EditorInsertInvitation", mi(EditorInsertInvitation)},
	{"Editor Insert Link", "editorinsertlink", "EditorInsertLink", mi(EditorInsertLink)},
	{"Editor Insert Photo", "editorinsertphoto", "EditorInsertPhoto", mi(EditorInsertPhoto)},
	{"Editor Linear Scale", "editorlinearscale", "EditorLinearScale", mi(EditorLinearScale)},
	{"Editor Merge Type", "editormergetype", "EditorMergeType", mi(EditorMergeType)},
	{"Editor Mode Comment", "editormodecomment", "EditorModeComment", mi(EditorModeComment)},
	{"Editor Mode Edit", "editormodeedit", "EditorModeEdit", mi(EditorModeEdit)},
	{"Editor Monetization On", "editormonetizationon", "EditorMonetizationOn", mi(EditorMonetizationOn)},
	{"Editor Money Off", "editormoneyoff", "EditorMoneyOff", mi(EditorMoneyOff)},
	{"Editor Multiline Chart", "editormultilinechart", "EditorMultilineChart", mi(EditorMultilineChart)},
	{"Editor Pie Chart", "editorpiechart", "EditorPieChart", mi(EditorPieChart)},
	{"Editor Pie Chart Outlined", "editorpiechartoutlined", "EditorPieChartOutlined", mi(EditorPieChartOutlined)},
	{"Editor Publish", "editorpublish", "EditorPublish", mi(EditorPublish)},
	{"Editor Short Text", "editorshorttext", "EditorShortText", mi(EditorShortText)},
	{"Editor Show Chart", "editorshowchart", "EditorShowChart", mi(EditorShowChart)},
	{"Editor Space Bar", "editorspacebar", "EditorSpaceBar", mi(EditorSpaceBar)},
	{"Editor Strikethrough S", "editorstrikethroughs", "EditorStrikethroughS", mi(EditorStrikethroughS)},
	{"Editor Text Fields", "editortextfields", "EditorTextFields", mi(EditorTextFields)},
	{"Editor Title", "editortitle", "EditorTitle", mi(EditorTitle)},
	{"Editor Vertical Align Bottom", "editorverticalalignbottom", "EditorVerticalAlignBottom", mi(EditorVerticalAlignBottom)},
	{"Editor Vertical Align Center", "editorverticalaligncenter", "EditorVerticalAlignCenter", mi(EditorVerticalAlignCenter)},
	{"Editor Vertical Align Top", "editorverticalaligntop", "EditorVerticalAlignTop", mi(EditorVerticalAlignTop)},
	{"Editor Wrap Text", "editorwraptext", "EditorWrapText", mi(EditorWrapText)},
	{"File Attachment", "fileattachment", "FileAttachment", mi(FileAttachment)},
	{"File Cloud", "filecloud", "FileCloud", mi(FileCloud)},
	{"File Cloud Circle", "filecloudcircle", "FileCloudCircle", mi(FileCloudCircle)},
	{"File Cloud Done", "fileclouddone", "FileCloudDone", mi(FileCloudDone)},
	{"File Cloud Download", "fileclouddownload", "FileCloudDownload", mi(FileCloudDownload)},
	{"File Cloud Off", "filecloudoff", "FileCloudOff", mi(FileCloudOff)},
	{"File Cloud Queue", "filecloudqueue", "FileCloudQueue", mi(FileCloudQueue)},
	{"File Cloud Upload", "filecloudupload", "FileCloudUpload", mi(FileCloudUpload)},
	{"File Create New Folder", "filecreatenewfolder", "FileCreateNewFolder", mi(FileCreateNewFolder)},
	{"File File Download", "filefiledownload", "FileFileDownload", mi(FileFileDownload)},
	{"File File Upload", "filefileupload", "FileFileUpload", mi(FileFileUpload)},
	{"File Folder", "filefolder", "FileFolder", mi(FileFolder)},
	{"File Folder Open", "filefolderopen", "FileFolderOpen", mi(FileFolderOpen)},
	{"File Folder Shared", "filefoldershared", "FileFolderShared", mi(FileFolderShared)},
	{"Hardware Cast", "hardwarecast", "HardwareCast", mi(HardwareCast)},
	{"Hardware Cast Connected", "hardwarecastconnected", "HardwareCastConnected", mi(HardwareCastConnected)},
	{"Hardware Computer", "hardwarecomputer", "HardwareComputer", mi(HardwareComputer)},
	{"Hardware Desktop Mac", "hardwaredesktopmac", "HardwareDesktopMac", mi(HardwareDesktopMac)},
	{"Hardware Desktop Windows", "hardwaredesktopwindows", "HardwareDesktopWindows", mi(HardwareDesktopWindows)},
	{"Hardware Developer Board", "hardwaredeveloperboard", "HardwareDeveloperBoard", mi(HardwareDeveloperBoard)},
	{"Hardware Device Hub", "hardwaredevicehub", "HardwareDeviceHub", mi(HardwareDeviceHub)},
	{"Hardware Devices Other", "hardwaredevicesother", "HardwareDevicesOther", mi(HardwareDevicesOther)},
	{"Hardware Dock", "hardwaredock", "HardwareDock", mi(HardwareDock)},
	{"Hardware Gamepad", "hardwaregamepad", "HardwareGamepad", mi(HardwareGamepad)},
	{"Hardware Headset", "hardwareheadset", "HardwareHeadset", mi(HardwareHeadset)},
	{"Hardware Headset Mic", "hardwareheadsetmic", "HardwareHeadsetMic", mi(HardwareHeadsetMic)},
	{"Hardware Keyboard", "hardwarekeyboard", "HardwareKeyboard", mi(HardwareKeyboard)},
	{"Hardware Keyboard Arrow Down", "hardwarekeyboardarrowdown", "HardwareKeyboardArrowDown", mi(HardwareKeyboardArrowDown)},
	{"Hardware Keyboard Arrow Left", "hardwarekeyboardarrowleft", "HardwareKeyboardArrowLeft", mi(HardwareKeyboardArrowLeft)},
	{"Hardware Keyboard Arrow Right", "hardwarekeyboardarrowright", "HardwareKeyboardArrowRight", mi(HardwareKeyboardArrowRight)},
	{"Hardware Keyboard Arrow Up", "hardwarekeyboardarrowup", "HardwareKeyboardArrowUp", mi(HardwareKeyboardArrowUp)},
	{"Hardware Keyboard Backspace", "hardwarekeyboardbackspace", "HardwareKeyboardBackspace", mi(HardwareKeyboardBackspace)},
	{"Hardware Keyboard Capslock", "hardwarekeyboardcapslock", "HardwareKeyboardCapslock", mi(HardwareKeyboardCapslock)},
	{"Hardware Keyboard Hide", "hardwarekeyboardhide", "HardwareKeyboardHide", mi(HardwareKeyboardHide)},
	{"Hardware Keyboard Return", "hardwarekeyboardreturn", "HardwareKeyboardReturn", mi(HardwareKeyboardReturn)},
	{"Hardware Keyboard Tab", "hardwarekeyboardtab", "HardwareKeyboardTab", mi(HardwareKeyboardTab)},
	{"Hardware Keyboard Voice", "hardwarekeyboardvoice", "HardwareKeyboardVoice", mi(HardwareKeyboardVoice)},
	{"Hardware Laptop", "hardwarelaptop", "HardwareLaptop", mi(HardwareLaptop)},
	{"Hardware Laptop Chromebook", "hardwarelaptopchromebook", "HardwareLaptopChromebook", mi(HardwareLaptopChromebook)},
	{"Hardware Laptop Mac", "hardwarelaptopmac", "HardwareLaptopMac", mi(HardwareLaptopMac)},
	{"Hardware Laptop Windows", "hardwarelaptopwindows", "HardwareLaptopWindows", mi(HardwareLaptopWindows)},
	{"Hardware Memory", "hardwarememory", "HardwareMemory", mi(HardwareMemory)},
	{"Hardware Mouse", "hardwaremouse", "HardwareMouse", mi(HardwareMouse)},
	{"Hardware Phone Android", "hardwarephoneandroid", "HardwarePhoneAndroid", mi(HardwarePhoneAndroid)},
	{"Hardware Phone I Phone", "hardwarephoneiphone", "HardwarePhoneIPhone", mi(HardwarePhoneIPhone)},
	{"Hardware Phone Link", "hardwarephonelink", "HardwarePhoneLink", mi(HardwarePhoneLink)},
	{"Hardware Phone Link Off", "hardwarephonelinkoff", "HardwarePhoneLinkOff", mi(HardwarePhoneLinkOff)},
	{"Hardware Power Input", "hardwarepowerinput", "HardwarePowerInput", mi(HardwarePowerInput)},
	{"Hardware Router", "hardwarerouter", "HardwareRouter", mi(HardwareRouter)},
	{"Hardware SIM Card", "hardwaresimcard", "HardwareSIMCard", mi(HardwareSIMCard)},
	{"Hardware Scanner", "hardwarescanner", "HardwareScanner", mi(HardwareScanner)},
	{"Hardware Security", "hardwaresecurity", "HardwareSecurity", mi(HardwareSecurity)},
	{"Hardware Smartphone", "hardwaresmartphone", "HardwareSmartphone", mi(HardwareSmartphone)},
	{"Hardware Speaker", "hardwarespeaker", "HardwareSpeaker", mi(HardwareSpeaker)},
	{"Hardware Speaker Group", "hardwarespeakergroup", "HardwareSpeakerGroup", mi(HardwareSpeakerGroup)},
	{"Hardware TV", "hardwaretv", "HardwareTV", mi(HardwareTV)},
	{"Hardware Tablet", "hardwaretablet", "HardwareTablet", mi(HardwareTablet)},
	{"Hardware Tablet Android", "hardwaretabletandroid", "HardwareTabletAndroid", mi(HardwareTabletAndroid)},
	{"Hardware Tablet Mac", "hardwaretabletmac", "HardwareTabletMac", mi(HardwareTabletMac)},
	{"Hardware Toys", "hardwaretoys", "HardwareToys", mi(HardwareToys)},
	{"Hardware Videogame Asset", "hardwarevideogameasset", "HardwareVideogameAsset", mi(HardwareVideogameAsset)},
	{"Hardware Watch", "hardwarewatch", "HardwareWatch", mi(HardwareWatch)},
	{"Image Add A Photo", "imageaddaphoto", "ImageAddAPhoto", mi(ImageAddAPhoto)},
	{"Image Add To Photos", "imageaddtophotos", "ImageAddToPhotos", mi(ImageAddToPhotos)},
	{"Image Adjust", "imageadjust", "ImageAdjust", mi(ImageAdjust)},
	{"Image Assistant", "imageassistant", "ImageAssistant", mi(ImageAssistant)},
	{"Image Assistant Photo", "imageassistantphoto", "ImageAssistantPhoto", mi(ImageAssistantPhoto)},
	{"Image Audiotrack", "imageaudiotrack", "ImageAudiotrack", mi(ImageAudiotrack)},
	{"Image Blur Circular", "imageblurcircular", "ImageBlurCircular", mi(ImageBlurCircular)},
	{"Image Blur Linear", "imageblurlinear", "ImageBlurLinear", mi(ImageBlurLinear)},
	{"Image Blur Off", "imagebluroff", "ImageBlurOff", mi(ImageBlurOff)},
	{"Image Blur On", "imagebluron", "ImageBlurOn", mi(ImageBlurOn)},
	{"Image Brightness 1", "imagebrightness1", "ImageBrightness1", mi(ImageBrightness1)},
	{"Image Brightness 2", "imagebrightness2", "ImageBrightness2", mi(ImageBrightness2)},
	{"Image Brightness 3", "imagebrightness3", "ImageBrightness3", mi(ImageBrightness3)},
	{"Image Brightness 4", "imagebrightness4", "ImageBrightness4", mi(ImageBrightness4)},
	{"Image Brightness 5", "imagebrightness5", "ImageBrightness5", mi(ImageBrightness5)},
	{"Image Brightness 6", "imagebrightness6", "ImageBrightness6", mi(ImageBrightness6)},
	{"Image Brightness 7", "imagebrightness7", "ImageBrightness7", mi(ImageBrightness7)},
	{"Image Broken Image", "imagebrokenimage", "ImageBrokenImage", mi(ImageBrokenImage)},
	{"Image Brush", "imagebrush", "ImageBrush", mi(ImageBrush)},
	{"Image Burst Mode", "imageburstmode", "ImageBurstMode", mi(ImageBurstMode)},
	{"Image Camera", "imagecamera", "ImageCamera", mi(ImageCamera)},
	{"Image Camera Alt", "imagecameraalt", "ImageCameraAlt", mi(ImageCameraAlt)},
	{"Image Camera Front", "imagecamerafront", "ImageCameraFront", mi(ImageCameraFront)},
	{"Image Camera Rear", "imagecamerarear", "ImageCameraRear", mi(ImageCameraRear)},
	{"Image Camera Roll", "imagecameraroll", "ImageCameraRoll", mi(ImageCameraRoll)},
	{"Image Center Focus Strong", "imagecenterfocusstrong", "ImageCenterFocusStrong", mi(ImageCenterFocusStrong)},
	{"Image Center Focus Weak", "imagecenterfocusweak", "ImageCenterFocusWeak", mi(ImageCenterFocusWeak)},
	{"Image Collections", "imagecollections", "ImageCollections", mi(ImageCollections)},
	{"Image Collections Bookmark", "imagecollectionsbookmark", "ImageCollectionsBookmark", mi(ImageCollectionsBookmark)},
	{"Image Color Lens", "imagecolorlens", "ImageColorLens", mi(ImageColorLens)},
	{"Image Colorize", "imagecolorize", "ImageColorize", mi(ImageColorize)},
	{"Image Compare", "imagecompare", "ImageCompare", mi(ImageCompare)},
	{"Image Control Point", "imagecontrolpoint", "ImageControlPoint", mi(ImageControlPoint)},
	{"Image Control Point Duplicate", "imagecontrolpointduplicate", "ImageControlPointDuplicate", mi(ImageControlPointDuplicate)},
	{"Image Crop", "imagecrop", "ImageCrop", mi(ImageCrop)},
	{"Image Crop 169", "imagecrop169", "ImageCrop169", mi(ImageCrop169)},
	{"Image Crop 32", "imagecrop32", "ImageCrop32", mi(ImageCrop32)},
	{"Image Crop 54", "imagecrop54", "ImageCrop54", mi(ImageCrop54)},
	{"Image Crop 75", "imagecrop75", "ImageCrop75", mi(ImageCrop75)},
	{"Image Crop DIN", "imagecropdin", "ImageCropDIN", mi(ImageCropDIN)},
	{"Image Crop Free", "imagecropfree", "ImageCropFree", mi(ImageCropFree)},
	{"Image Crop Landscape", "imagecroplandscape", "ImageCropLandscape", mi(ImageCropLandscape)},
	{"Image Crop Original", "imagecroporiginal", "ImageCropOriginal", mi(ImageCropOriginal)},
	{"Image Crop Portrait", "imagecropportrait", "ImageCropPortrait", mi(ImageCropPortrait)},
	{"Image Crop Rotate", "imagecroprotate", "ImageCropRotate", mi(ImageCropRotate)},
	{"Image Crop Square", "imagecropsquare", "ImageCropSquare", mi(ImageCropSquare)},
	{"Image Dehaze", "imagedehaze", "ImageDehaze", mi(ImageDehaze)},
	{"Image Details", "imagedetails", "ImageDetails", mi(ImageDetails)},
	{"Image Edit", "imageedit", "ImageEdit", mi(ImageEdit)},
	{"Image Exposure", "imageexposure", "ImageExposure", mi(ImageExposure)},
	{"Image Exposure Neg 1", "imageexposureneg1", "ImageExposureNeg1", mi(ImageExposureNeg1)},
	{"Image Exposure Neg 2", "imageexposureneg2", "ImageExposureNeg2", mi(ImageExposureNeg2)},
	{"Image Exposure Plus 1", "imageexposureplus1", "ImageExposurePlus1", mi(ImageExposurePlus1)},
	{"Image Exposure Plus 2", "imageexposureplus2", "ImageExposurePlus2", mi(ImageExposurePlus2)},
	{"Image Exposure Zero", "imageexposurezero", "ImageExposureZero", mi(ImageExposureZero)},
	{"Image Filter", "imagefilter", "ImageFilter", mi(ImageFilter)},
	{"Image Filter 1", "imagefilter1", "ImageFilter1", mi(ImageFilter1)},
	{"Image Filter 2", "imagefilter2", "ImageFilter2", mi(ImageFilter2)},
	{"Image Filter 3", "imagefilter3", "ImageFilter3", mi(ImageFilter3)},
	{"Image Filter 4", "imagefilter4", "ImageFilter4", mi(ImageFilter4)},
	{"Image Filter 5", "imagefilter5", "ImageFilter5", mi(ImageFilter5)},
	{"Image Filter 6", "imagefilter6", "ImageFilter6", mi(ImageFilter6)},
	{"Image Filter 7", "imagefilter7", "ImageFilter7", mi(ImageFilter7)},
	{"Image Filter 8", "imagefilter8", "ImageFilter8", mi(ImageFilter8)},
	{"Image Filter 9", "imagefilter9", "ImageFilter9", mi(ImageFilter9)},
	{"Image Filter 9 Plus", "imagefilter9plus", "ImageFilter9Plus", mi(ImageFilter9Plus)},
	{"Image Filter B And W", "imagefilterbandw", "ImageFilterBAndW", mi(ImageFilterBAndW)},
	{"Image Filter Center Focus", "imagefiltercenterfocus", "ImageFilterCenterFocus", mi(ImageFilterCenterFocus)},
	{"Image Filter Drama", "imagefilterdrama", "ImageFilterDrama", mi(ImageFilterDrama)},
	{"Image Filter Frames", "imagefilterframes", "ImageFilterFrames", mi(ImageFilterFrames)},
	{"Image Filter HDR", "imagefilterhdr", "ImageFilterHDR", mi(ImageFilterHDR)},
	{"Image Filter None", "imagefilternone", "ImageFilterNone", mi(ImageFilterNone)},
	{"Image Filter Tilt Shift", "imagefiltertiltshift", "ImageFilterTiltShift", mi(ImageFilterTiltShift)},
	{"Image Filter Vintage", "imagefiltervintage", "ImageFilterVintage", mi(ImageFilterVintage)},
	{"Image Flare", "imageflare", "ImageFlare", mi(ImageFlare)},
	{"Image Flash Auto", "imageflashauto", "ImageFlashAuto", mi(ImageFlashAuto)},
	{"Image Flash Off", "imageflashoff", "ImageFlashOff", mi(ImageFlashOff)},
	{"Image Flash On", "imageflashon", "ImageFlashOn", mi(ImageFlashOn)},
	{"Image Flip", "imageflip", "ImageFlip", mi(ImageFlip)},
	{"Image Gradient", "imagegradient", "ImageGradient", mi(ImageGradient)},
	{"Image Grain", "imagegrain", "ImageGrain", mi(ImageGrain)},
	{"Image Grid Off", "imagegridoff", "ImageGridOff", mi(ImageGridOff)},
	{"Image Grid On", "imagegridon", "ImageGridOn", mi(ImageGridOn)},
	{"Image HDR Off", "imagehdroff", "ImageHDROff", mi(ImageHDROff)},
	{"Image HDR On", "imagehdron", "ImageHDROn", mi(ImageHDROn)},
	{"Image HDR Strong", "imagehdrstrong", "ImageHDRStrong", mi(ImageHDRStrong)},
	{"Image HDR Weak", "imagehdrweak", "ImageHDRWeak", mi(ImageHDRWeak)},
	{"Image Healing", "imagehealing", "ImageHealing", mi(ImageHealing)},
	{"Image ISO", "imageiso", "ImageISO", mi(ImageISO)},
	{"Image Image", "imageimage", "ImageImage", mi(ImageImage)},
	{"Image Image Aspect Ratio", "imageimageaspectratio", "ImageImageAspectRatio", mi(ImageImageAspectRatio)},
	{"Image Landscape", "imagelandscape", "ImageLandscape", mi(ImageLandscape)},
	{"Image Leak Add", "imageleakadd", "ImageLeakAdd", mi(ImageLeakAdd)},
	{"Image Leak Remove", "imageleakremove", "ImageLeakRemove", mi(ImageLeakRemove)},
	{"Image Lens", "imagelens", "ImageLens", mi(ImageLens)},
	{"Image Linked Camera", "imagelinkedcamera", "ImageLinkedCamera", mi(ImageLinkedCamera)},
	{"Image Looks", "imagelooks", "ImageLooks", mi(ImageLooks)},
	{"Image Looks 3", "imagelooks3", "ImageLooks3", mi(ImageLooks3)},
	{"Image Looks 4", "imagelooks4", "ImageLooks4", mi(ImageLooks4)},
	{"Image Looks 5", "imagelooks5", "ImageLooks5", mi(ImageLooks5)},
	{"Image Looks 6", "imagelooks6", "ImageLooks6", mi(ImageLooks6)},
	{"Image Looks One", "imagelooksone", "ImageLooksOne", mi(ImageLooksOne)},
	{"Image Looks Two", "imagelookstwo", "ImageLooksTwo", mi(ImageLooksTwo)},
	{"Image Loupe", "imageloupe", "ImageLoupe", mi(ImageLoupe)},
	{"Image Monochrome Photos", "imagemonochromephotos", "ImageMonochromePhotos", mi(ImageMonochromePhotos)},
	{"Image Movie Creation", "imagemoviecreation", "ImageMovieCreation", mi(ImageMovieCreation)},
	{"Image Movie Filter", "imagemoviefilter", "ImageMovieFilter", mi(ImageMovieFilter)},
	{"Image Music Note", "imagemusicnote", "ImageMusicNote", mi(ImageMusicNote)},
	{"Image Nature", "imagenature", "ImageNature", mi(ImageNature)},
	{"Image Nature People", "imagenaturepeople", "ImageNaturePeople", mi(ImageNaturePeople)},
	{"Image Navigate Before", "imagenavigatebefore", "ImageNavigateBefore", mi(ImageNavigateBefore)},
	{"Image Navigate Next", "imagenavigatenext", "ImageNavigateNext", mi(ImageNavigateNext)},
	{"Image Palette", "imagepalette", "ImagePalette", mi(ImagePalette)},
	{"Image Panorama", "imagepanorama", "ImagePanorama", mi(ImagePanorama)},
	{"Image Panorama Fish Eye", "imagepanoramafisheye", "ImagePanoramaFishEye", mi(ImagePanoramaFishEye)},
	{"Image Panorama Horizontal", "imagepanoramahorizontal", "ImagePanoramaHorizontal", mi(ImagePanoramaHorizontal)},
	{"Image Panorama Vertical", "imagepanoramavertical", "ImagePanoramaVertical", mi(ImagePanoramaVertical)},
	{"Image Panorama Wide Angle", "imagepanoramawideangle", "ImagePanoramaWideAngle", mi(ImagePanoramaWideAngle)},
	{"Image Photo", "imagephoto", "ImagePhoto", mi(ImagePhoto)},
	{"Image Photo Album", "imagephotoalbum", "ImagePhotoAlbum", mi(ImagePhotoAlbum)},
	{"Image Photo Camera", "imagephotocamera", "ImagePhotoCamera", mi(ImagePhotoCamera)},
	{"Image Photo Filter", "imagephotofilter", "ImagePhotoFilter", mi(ImagePhotoFilter)},
	{"Image Photo Library", "imagephotolibrary", "ImagePhotoLibrary", mi(ImagePhotoLibrary)},
	{"Image Photo Size Select Actual", "imagephotosizeselectactual", "ImagePhotoSizeSelectActual", mi(ImagePhotoSizeSelectActual)},
	{"Image Photo Size Select Large", "imagephotosizeselectlarge", "ImagePhotoSizeSelectLarge", mi(ImagePhotoSizeSelectLarge)},
	{"Image Photo Size Select Small", "imagephotosizeselectsmall", "ImagePhotoSizeSelectSmall", mi(ImagePhotoSizeSelectSmall)},
	{"Image Picture As PDF", "imagepictureaspdf", "ImagePictureAsPDF", mi(ImagePictureAsPDF)},
	{"Image Portrait", "imageportrait", "ImagePortrait", mi(ImagePortrait)},
	{"Image Remove Red Eye", "imageremoveredeye", "ImageRemoveRedEye", mi(ImageRemoveRedEye)},
	{"Image Rotate 90 Degrees CCW", "imagerotate90degreesccw", "ImageRotate90DegreesCCW", mi(ImageRotate90DegreesCCW)},
	{"Image Rotate Left", "imagerotateleft", "ImageRotateLeft", mi(ImageRotateLeft)},
	{"Image Rotate Right", "imagerotateright", "ImageRotateRight", mi(ImageRotateRight)},
	{"Image Slideshow", "imageslideshow", "ImageSlideshow", mi(ImageSlideshow)},
	{"Image Straighten", "imagestraighten", "ImageStraighten", mi(ImageStraighten)},
	{"Image Style", "imagestyle", "ImageStyle", mi(ImageStyle)},
	{"Image Switch Camera", "imageswitchcamera", "ImageSwitchCamera", mi(ImageSwitchCamera)},
	{"Image Switch Video", "imageswitchvideo", "ImageSwitchVideo", mi(ImageSwitchVideo)},
	{"Image Tag Faces", "imagetagfaces", "ImageTagFaces", mi(ImageTagFaces)},
	{"Image Texture", "imagetexture", "ImageTexture", mi(ImageTexture)},
	{"Image Time Lapse", "imagetimelapse", "ImageTimeLapse", mi(ImageTimeLapse)},
	{"Image Timer", "imagetimer", "ImageTimer", mi(ImageTimer)},
	{"Image Timer 10", "imagetimer10", "ImageTimer10", mi(ImageTimer10)},
	{"Image Timer 3", "imagetimer3", "ImageTimer3", mi(ImageTimer3)},
	{"Image Timer Off", "imagetimeroff", "ImageTimerOff", mi(ImageTimerOff)},
	{"Image Tonality", "imagetonality", "ImageTonality", mi(ImageTonality)},
	{"Image Transform", "imagetransform", "ImageTransform", mi(ImageTransform)},
	{"Image Tune", "imagetune", "ImageTune", mi(ImageTune)},
	{"Image View Comfy", "imageviewcomfy", "ImageViewComfy", mi(ImageViewComfy)},
	{"Image View Compact", "imageviewcompact", "ImageViewCompact", mi(ImageViewCompact)},
	{"Image Vignette", "imagevignette", "ImageVignette", mi(ImageVignette)},
	{"Image WB Auto", "imagewbauto", "ImageWBAuto", mi(ImageWBAuto)},
	{"Image WB Cloudy", "imagewbcloudy", "ImageWBCloudy", mi(ImageWBCloudy)},
	{"Image WB Incandescent", "imagewbincandescent", "ImageWBIncandescent", mi(ImageWBIncandescent)},
	{"Image WB Iridescent", "imagewbiridescent", "ImageWBIridescent", mi(ImageWBIridescent)},
	{"Image WB Sunny", "imagewbsunny", "ImageWBSunny", mi(ImageWBSunny)},
	{"Maps Add Location", "mapsaddlocation", "MapsAddLocation", mi(MapsAddLocation)},
	{"Maps Beenhere", "mapsbeenhere", "MapsBeenhere", mi(MapsBeenhere)},
	{"Maps Directions", "mapsdirections", "MapsDirections", mi(MapsDirections)},
	{"Maps Directions Bike", "mapsdirectionsbike", "MapsDirectionsBike", mi(MapsDirectionsBike)},
	{"Maps Directions Boat", "mapsdirectionsboat", "MapsDirectionsBoat", mi(MapsDirectionsBoat)},
	{"Maps Directions Bus", "mapsdirectionsbus", "MapsDirectionsBus", mi(MapsDirectionsBus)},
	{"Maps Directions Car", "mapsdirectionscar", "MapsDirectionsCar", mi(MapsDirectionsCar)},
	{"Maps Directions Railway", "mapsdirectionsrailway", "MapsDirectionsRailway", mi(MapsDirectionsRailway)},
	{"Maps Directions Run", "mapsdirectionsrun", "MapsDirectionsRun", mi(MapsDirectionsRun)},
	{"Maps Directions Subway", "mapsdirectionssubway", "MapsDirectionsSubway", mi(MapsDirectionsSubway)},
	{"Maps Directions Transit", "mapsdirectionstransit", "MapsDirectionsTransit", mi(MapsDirectionsTransit)},
	{"Maps Directions Walk", "mapsdirectionswalk", "MapsDirectionsWalk", mi(MapsDirectionsWalk)},
	{"Maps EV Station", "mapsevstation", "MapsEVStation", mi(MapsEVStation)},
	{"Maps Edit Location", "mapseditlocation", "MapsEditLocation", mi(MapsEditLocation)},
	{"Maps Flight", "mapsflight", "MapsFlight", mi(MapsFlight)},
	{"Maps Hotel", "mapshotel", "MapsHotel", mi(MapsHotel)},
	{"Maps Layers", "mapslayers", "MapsLayers", mi(MapsLayers)},
	{"Maps Layers Clear", "mapslayersclear", "MapsLayersClear", mi(MapsLayersClear)},
	{"Maps Local ATM", "mapslocalatm", "MapsLocalATM", mi(MapsLocalATM)},
	{"Maps Local Activity", "mapslocalactivity", "MapsLocalActivity", mi(MapsLocalActivity)},
	{"Maps Local Airport", "mapslocalairport", "MapsLocalAirport", mi(MapsLocalAirport)},
	{"Maps Local Bar", "mapslocalbar", "MapsLocalBar", mi(MapsLocalBar)},
	{"Maps Local Cafe", "mapslocalcafe", "MapsLocalCafe", mi(MapsLocalCafe)},
	{"Maps Local Car Wash", "mapslocalcarwash", "MapsLocalCarWash", mi(MapsLocalCarWash)},
	{"Maps Local Convenience Store", "mapslocalconveniencestore", "MapsLocalConvenienceStore", mi(MapsLocalConvenienceStore)},
	{"Maps Local Dining", "mapslocaldining", "MapsLocalDining", mi(MapsLocalDining)},
	{"Maps Local Drink", "mapslocaldrink", "MapsLocalDrink", mi(MapsLocalDrink)},
	{"Maps Local Florist", "mapslocalflorist", "MapsLocalFlorist", mi(MapsLocalFlorist)},
	{"Maps Local Gas Station", "mapslocalgasstation", "MapsLocalGasStation", mi(MapsLocalGasStation)},
	{"Maps Local Grocery Store", "mapslocalgrocerystore", "MapsLocalGroceryStore", mi(MapsLocalGroceryStore)},
	{"Maps Local Hospital", "mapslocalhospital", "MapsLocalHospital", mi(MapsLocalHospital)},
	{"Maps Local Hotel", "mapslocalhotel", "MapsLocalHotel", mi(MapsLocalHotel)},
	{"Maps Local Laundry Service", "mapslocallaundryservice", "MapsLocalLaundryService", mi(MapsLocalLaundryService)},
	{"Maps Local Library", "mapslocallibrary", "MapsLocalLibrary", mi(MapsLocalLibrary)},
	{"Maps Local Mall", "mapslocalmall", "MapsLocalMall", mi(MapsLocalMall)},
	{"Maps Local Movies", "mapslocalmovies", "MapsLocalMovies", mi(MapsLocalMovies)},
	{"Maps Local Offer", "mapslocaloffer", "MapsLocalOffer", mi(MapsLocalOffer)},
	{"Maps Local Parking", "mapslocalparking", "MapsLocalParking", mi(MapsLocalParking)},
	{"Maps Local Pharmacy", "mapslocalpharmacy", "MapsLocalPharmacy", mi(MapsLocalPharmacy)},
	{"Maps Local Phone", "mapslocalphone", "MapsLocalPhone", mi(MapsLocalPhone)},
	{"Maps Local Pizza", "mapslocalpizza", "MapsLocalPizza", mi(MapsLocalPizza)},
	{"Maps Local Play", "mapslocalplay", "MapsLocalPlay", mi(MapsLocalPlay)},
	{"Maps Local Post Office", "mapslocalpostoffice", "MapsLocalPostOffice", mi(MapsLocalPostOffice)},
	{"Maps Local Printshop", "mapslocalprintshop", "MapsLocalPrintshop", mi(MapsLocalPrintshop)},
	{"Maps Local See", "mapslocalsee", "MapsLocalSee", mi(MapsLocalSee)},
	{"Maps Local Shipping", "mapslocalshipping", "MapsLocalShipping", mi(MapsLocalShipping)},
	{"Maps Local Taxi", "mapslocaltaxi", "MapsLocalTaxi", mi(MapsLocalTaxi)},
	{"Maps Map", "mapsmap", "MapsMap", mi(MapsMap)},
	{"Maps My Location", "mapsmylocation", "MapsMyLocation", mi(MapsMyLocation)},
	{"Maps Navigation", "mapsnavigation", "MapsNavigation", mi(MapsNavigation)},
	{"Maps Near Me", "mapsnearme", "MapsNearMe", mi(MapsNearMe)},
	{"Maps Person Pin", "mapspersonpin", "MapsPersonPin", mi(MapsPersonPin)},
	{"Maps Person Pin Circle", "mapspersonpincircle", "MapsPersonPinCircle", mi(MapsPersonPinCircle)},
	{"Maps Pin Drop", "mapspindrop", "MapsPinDrop", mi(MapsPinDrop)},
	{"Maps Place", "mapsplace", "MapsPlace", mi(MapsPlace)},
	{"Maps Rate Review", "mapsratereview", "MapsRateReview", mi(MapsRateReview)},
	{"Maps Restaurant", "mapsrestaurant", "MapsRestaurant", mi(MapsRestaurant)},
	{"Maps Restaurant Menu", "mapsrestaurantmenu", "MapsRestaurantMenu", mi(MapsRestaurantMenu)},
	{"Maps Satellite", "mapssatellite", "MapsSatellite", mi(MapsSatellite)},
	{"Maps Store Mall Directory", "mapsstoremalldirectory", "MapsStoreMallDirectory", mi(MapsStoreMallDirectory)},
	{"Maps Street View", "mapsstreetview", "MapsStreetView", mi(MapsStreetView)},
	{"Maps Subway", "mapssubway", "MapsSubway", mi(MapsSubway)},
	{"Maps Terrain", "mapsterrain", "MapsTerrain", mi(MapsTerrain)},
	{"Maps Traffic", "mapstraffic", "MapsTraffic", mi(MapsTraffic)},
	{"Maps Train", "mapstrain", "MapsTrain", mi(MapsTrain)},
	{"Maps Tram", "mapstram", "MapsTram", mi(MapsTram)},
	{"Maps Transfer Within A Station", "mapstransferwithinastation", "MapsTransferWithinAStation", mi(MapsTransferWithinAStation)},
	{"Maps Zoom Out Map", "mapszoomoutmap", "MapsZoomOutMap", mi(MapsZoomOutMap)},
	{"Navigation Apps", "navigationapps", "NavigationApps", mi(NavigationApps)},
	{"Navigation Arrow Back", "navigationarrowback", "NavigationArrowBack", mi(NavigationArrowBack)},
	{"Navigation Arrow Downward", "navigationarrowdownward", "NavigationArrowDownward", mi(NavigationArrowDownward)},
	{"Navigation Arrow Drop Down", "navigationarrowdropdown", "NavigationArrowDropDown", mi(NavigationArrowDropDown)},
	{"Navigation Arrow Drop Down Circle", "navigationarrowdropdowncircle", "NavigationArrowDropDownCircle", mi(NavigationArrowDropDownCircle)},
	{"Navigation Arrow Drop Up", "navigationarrowdropup", "NavigationArrowDropUp", mi(NavigationArrowDropUp)},
	{"Navigation Arrow Forward", "navigationarrowforward", "NavigationArrowForward", mi(NavigationArrowForward)},
	{"Navigation Arrow Upward", "navigationarrowupward", "NavigationArrowUpward", mi(NavigationArrowUpward)},
	{"Navigation Cancel", "navigationcancel", "NavigationCancel", mi(NavigationCancel)},
	{"Navigation Check", "navigationcheck", "NavigationCheck", mi(NavigationCheck)},
	{"Navigation Chevron Left", "navigationchevronleft", "NavigationChevronLeft", mi(NavigationChevronLeft)},
	{"Navigation Chevron Right", "navigationchevronright", "NavigationChevronRight", mi(NavigationChevronRight)},
	{"Navigation Close", "navigationclose", "NavigationClose", mi(NavigationClose)},
	{"Navigation Expand Less", "navigationexpandless", "NavigationExpandLess", mi(NavigationExpandLess)},
	{"Navigation Expand More", "navigationexpandmore", "NavigationExpandMore", mi(NavigationExpandMore)},
	{"Navigation First Page", "navigationfirstpage", "NavigationFirstPage", mi(NavigationFirstPage)},
	{"Navigation Fullscreen", "navigationfullscreen", "NavigationFullscreen", mi(NavigationFullscreen)},
	{"Navigation Fullscreen Exit", "navigationfullscreenexit", "NavigationFullscreenExit", mi(NavigationFullscreenExit)},
	{"Navigation Last Page", "navigationlastpage", "NavigationLastPage", mi(NavigationLastPage)},
	{"Navigation Menu", "navigationmenu", "NavigationMenu", mi(NavigationMenu)},
	{"Navigation More Horiz", "navigationmorehoriz", "NavigationMoreHoriz", mi(NavigationMoreHoriz)},
	{"Navigation More Vert", "navigationmorevert", "NavigationMoreVert", mi(NavigationMoreVert)},
	{"Navigation Refresh", "navigationrefresh", "NavigationRefresh", mi(NavigationRefresh)},
	{"Navigation Subdirectory Arrow Left", "navigationsubdirectoryarrowleft", "NavigationSubdirectoryArrowLeft", mi(NavigationSubdirectoryArrowLeft)},
	{"Navigation Subdirectory Arrow Right", "navigationsubdirectoryarrowright", "NavigationSubdirectoryArrowRight", mi(NavigationSubdirectoryArrowRight)},
	{"Navigation Unfold Less", "navigationunfoldless", "NavigationUnfoldLess", mi(NavigationUnfoldLess)},
	{"Navigation Unfold More", "navigationunfoldmore", "NavigationUnfoldMore", mi(NavigationUnfoldMore)},
	{"Notification ADB", "notificationadb", "NotificationADB", mi(NotificationADB)},
	{"Notification Airline Seat Flat", "notificationairlineseatflat", "NotificationAirlineSeatFlat", mi(NotificationAirlineSeatFlat)},
	{"Notification Airline Seat Flat Angled", "notificationairlineseatflatangled", "NotificationAirlineSeatFlatAngled", mi(NotificationAirlineSeatFlatAngled)},
	{"Notification Airline Seat Individual Suite", "notificationairlineseatindividualsuite", "NotificationAirlineSeatIndividualSuite", mi(NotificationAirlineSeatIndividualSuite)},
	{"Notification Airline Seat Legroom Extra", "notificationairlineseatlegroomextra", "NotificationAirlineSeatLegroomExtra", mi(NotificationAirlineSeatLegroomExtra)},
	{"Notification Airline Seat Legroom Normal", "notificationairlineseatlegroomnormal", "NotificationAirlineSeatLegroomNormal", mi(NotificationAirlineSeatLegroomNormal)},
	{"Notification Airline Seat Legroom Reduced", "notificationairlineseatlegroomreduced", "NotificationAirlineSeatLegroomReduced", mi(NotificationAirlineSeatLegroomReduced)},
	{"Notification Airline Seat Recline Extra", "notificationairlineseatreclineextra", "NotificationAirlineSeatReclineExtra", mi(NotificationAirlineSeatReclineExtra)},
	{"Notification Airline Seat Recline Normal", "notificationairlineseatreclinenormal", "NotificationAirlineSeatReclineNormal", mi(NotificationAirlineSeatReclineNormal)},
	{"Notification Bluetooth Audio", "notificationbluetoothaudio", "NotificationBluetoothAudio", mi(NotificationBluetoothAudio)},
	{"Notification Confirmation Number", "notificationconfirmationnumber", "NotificationConfirmationNumber", mi(NotificationConfirmationNumber)},
	{"Notification Disc Full", "notificationdiscfull", "NotificationDiscFull", mi(NotificationDiscFull)},
	{"Notification Do Not Disturb", "notificationdonotdisturb", "NotificationDoNotDisturb", mi(NotificationDoNotDisturb)},
	{"Notification Do Not Disturb Alt", "notificationdonotdisturbalt", "NotificationDoNotDisturbAlt", mi(NotificationDoNotDisturbAlt)},
	{"Notification Do Not Disturb Off", "notificationdonotdisturboff", "NotificationDoNotDisturbOff", mi(NotificationDoNotDisturbOff)},
	{"Notification Do Not Disturb On", "notificationdonotdisturbon", "NotificationDoNotDisturbOn", mi(NotificationDoNotDisturbOn)},
	{"Notification Drive ETA", "notificationdriveeta", "NotificationDriveETA", mi(NotificationDriveETA)},
	{"Notification Enhanced Encryption", "notificationenhancedencryption", "NotificationEnhancedEncryption", mi(NotificationEnhancedEncryption)},
	{"Notification Event Available", "notificationeventavailable", "NotificationEventAvailable", mi(NotificationEventAvailable)},
	{"Notification Event Busy", "notificationeventbusy", "NotificationEventBusy", mi(NotificationEventBusy)},
	{"Notification Event Note", "notificationeventnote", "NotificationEventNote", mi(NotificationEventNote)},
	{"Notification Folder Special", "notificationfolderspecial", "NotificationFolderSpecial", mi(NotificationFolderSpecial)},
	{"Notification Live TV", "notificationlivetv", "NotificationLiveTV", mi(NotificationLiveTV)},
	{"Notification MMS", "notificationmms", "NotificationMMS", mi(NotificationMMS)},
	{"Notification More", "notificationmore", "NotificationMore", mi(NotificationMore)},
	{"Notification Network Check", "notificationnetworkcheck", "NotificationNetworkCheck", mi(NotificationNetworkCheck)},
	{"Notification Network Locked", "notificationnetworklocked", "NotificationNetworkLocked", mi(NotificationNetworkLocked)},
	{"Notification No Encryption", "notificationnoencryption", "NotificationNoEncryption", mi(NotificationNoEncryption)},
	{"Notification On Demand Video", "notificationondemandvideo", "NotificationOnDemandVideo", mi(NotificationOnDemandVideo)},
	{"Notification Personal Video", "notificationpersonalvideo", "NotificationPersonalVideo", mi(NotificationPersonalVideo)},
	{"Notification Phone Bluetooth Speaker", "notificationphonebluetoothspeaker", "NotificationPhoneBluetoothSpeaker", mi(NotificationPhoneBluetoothSpeaker)},
	{"Notification Phone Forwarded", "notificationphoneforwarded", "NotificationPhoneForwarded", mi(NotificationPhoneForwarded)},
	{"Notification Phone In Talk", "notificationphoneintalk", "NotificationPhoneInTalk", mi(NotificationPhoneInTalk)},
	{"Notification Phone Locked", "notificationphonelocked", "NotificationPhoneLocked", mi(NotificationPhoneLocked)},
	{"Notification Phone Missed", "notificationphonemissed", "NotificationPhoneMissed", mi(NotificationPhoneMissed)},
	{"Notification Phone Paused", "notificationphonepaused", "NotificationPhonePaused", mi(NotificationPhonePaused)},
	{"Notification Power", "notificationpower", "NotificationPower", mi(NotificationPower)},
	{"Notification Priority High", "notificationpriorityhigh", "NotificationPriorityHigh", mi(NotificationPriorityHigh)},
	{"Notification RV Hookup", "notificationrvhookup", "NotificationRVHookup", mi(NotificationRVHookup)},
	{"Notification SD Card", "notificationsdcard", "NotificationSDCard", mi(NotificationSDCard)},
	{"Notification SIM Card Alert", "notificationsimcardalert", "NotificationSIMCardAlert", mi(NotificationSIMCardAlert)},
	{"Notification SMS", "notificationsms", "NotificationSMS", mi(NotificationSMS)},
	{"Notification SMS Failed", "notificationsmsfailed", "NotificationSMSFailed", mi(NotificationSMSFailed)},
	{"Notification Sync", "notificationsync", "NotificationSync", mi(NotificationSync)},
	{"Notification Sync Disabled", "notificationsyncdisabled", "NotificationSyncDisabled", mi(NotificationSyncDisabled)},
	{"Notification Sync Problem", "notificationsyncproblem", "NotificationSyncProblem", mi(NotificationSyncProblem)},
	{"Notification System Update", "notificationsystemupdate", "NotificationSystemUpdate", mi(NotificationSystemUpdate)},
	{"Notification Tap And Play", "notificationtapandplay", "NotificationTapAndPlay", mi(NotificationTapAndPlay)},
	{"Notification Time To Leave", "notificationtimetoleave", "NotificationTimeToLeave", mi(NotificationTimeToLeave)},
	{"Notification VPN Lock", "notificationvpnlock", "NotificationVPNLock", mi(NotificationVPNLock)},
	{"Notification Vibration", "notificationvibration", "NotificationVibration", mi(NotificationVibration)},
	{"Notification Voice Chat", "notificationvoicechat", "NotificationVoiceChat", mi(NotificationVoiceChat)},
	{"Notification WC", "notificationwc", "NotificationWC", mi(NotificationWC)},
	{"Notification Wi Fi", "notificationwifi", "NotificationWiFi", mi(NotificationWiFi)},
	{"Places AC Unit", "placesacunit", "PlacesACUnit", mi(PlacesACUnit)},
	{"Places Airport Shuttle", "placesairportshuttle", "PlacesAirportShuttle", mi(PlacesAirportShuttle)},
	{"Places All Inclusive", "placesallinclusive", "PlacesAllInclusive", mi(PlacesAllInclusive)},
	{"Places Beach Access", "placesbeachaccess", "PlacesBeachAccess", mi(PlacesBeachAccess)},
	{"Places Business Center", "placesbusinesscenter", "PlacesBusinessCenter", mi(PlacesBusinessCenter)},
	{"Places Casino", "placescasino", "PlacesCasino", mi(PlacesCasino)},
	{"Places Child Care", "placeschildcare", "PlacesChildCare", mi(PlacesChildCare)},
	{"Places Child Friendly", "placeschildfriendly", "PlacesChildFriendly", mi(PlacesChildFriendly)},
	{"Places Fitness Center", "placesfitnesscenter", "PlacesFitnessCenter", mi(PlacesFitnessCenter)},
	{"Places Free Breakfast", "placesfreebreakfast", "PlacesFreeBreakfast", mi(PlacesFreeBreakfast)},
	{"Places Golf Course", "placesgolfcourse", "PlacesGolfCourse", mi(PlacesGolfCourse)},
	{"Places Hot Tub", "placeshottub", "PlacesHotTub", mi(PlacesHotTub)},
	{"Places Kitchen", "placeskitchen", "PlacesKitchen", mi(PlacesKitchen)},
	{"Places Pool", "placespool", "PlacesPool", mi(PlacesPool)},
	{"Places RV Hookup", "placesrvhookup", "PlacesRVHookup", mi(PlacesRVHookup)},
	{"Places Room Service", "placesroomservice", "PlacesRoomService", mi(PlacesRoomService)},
	{"Places Smoke Free", "placessmokefree", "PlacesSmokeFree", mi(PlacesSmokeFree)},
	{"Places Smoking Rooms", "placessmokingrooms", "PlacesSmokingRooms", mi(PlacesSmokingRooms)},
	{"Places Spa", "placesspa", "PlacesSpa", mi(PlacesSpa)},
	{"Social Cake", "socialcake", "SocialCake", mi(SocialCake)},
	{"Social Domain", "socialdomain", "SocialDomain", mi(SocialDomain)},
	{"Social Group", "socialgroup", "SocialGroup", mi(SocialGroup)},
	{"Social Group Add", "socialgroupadd", "SocialGroupAdd", mi(SocialGroupAdd)},
	{"Social Location City", "sociallocationcity", "SocialLocationCity", mi(SocialLocationCity)},
	{"Social Mood", "socialmood", "SocialMood", mi(SocialMood)},
	{"Social Mood Bad", "socialmoodbad", "SocialMoodBad", mi(SocialMoodBad)},
	{"Social Notifications", "socialnotifications", "SocialNotifications", mi(SocialNotifications)},
	{"Social Notifications Active", "socialnotificationsactive", "SocialNotificationsActive", mi(SocialNotificationsActive)},
	{"Social Notifications None", "socialnotificationsnone", "SocialNotificationsNone", mi(SocialNotificationsNone)},
	{"Social Notifications Off", "socialnotificationsoff", "SocialNotificationsOff", mi(SocialNotificationsOff)},
	{"Social Notifications Paused", "socialnotificationspaused", "SocialNotificationsPaused", mi(SocialNotificationsPaused)},
	{"Social Pages", "socialpages", "SocialPages", mi(SocialPages)},
	{"Social Party Mode", "socialpartymode", "SocialPartyMode", mi(SocialPartyMode)},
	{"Social People", "socialpeople", "SocialPeople", mi(SocialPeople)},
	{"Social People Outline", "socialpeopleoutline", "SocialPeopleOutline", mi(SocialPeopleOutline)},
	{"Social Person", "socialperson", "SocialPerson", mi(SocialPerson)},
	{"Social Person Add", "socialpersonadd", "SocialPersonAdd", mi(SocialPersonAdd)},
	{"Social Person Outline", "socialpersonoutline", "SocialPersonOutline", mi(SocialPersonOutline)},
	{"Social Plus One", "socialplusone", "SocialPlusOne", mi(SocialPlusOne)},
	{"Social Poll", "socialpoll", "SocialPoll", mi(SocialPoll)},
	{"Social Public", "socialpublic", "SocialPublic", mi(SocialPublic)},
	{"Social School", "socialschool", "SocialSchool", mi(SocialSchool)},
	{"Social Sentiment Dissatisfied", "socialsentimentdissatisfied", "SocialSentimentDissatisfied", mi(SocialSentimentDissatisfied)},
	{"Social Sentiment Neutral", "socialsentimentneutral", "SocialSentimentNeutral", mi(SocialSentimentNeutral)},
	{"Social Sentiment Satisfied", "socialsentimentsatisfied", "SocialSentimentSatisfied", mi(SocialSentimentSatisfied)},
	{"Social Sentiment Very Dissatisfied", "socialsentimentverydissatisfied", "SocialSentimentVeryDissatisfied", mi(SocialSentimentVeryDissatisfied)},
	{"Social Sentiment Very Satisfied", "socialsentimentverysatisfied", "SocialSentimentVerySatisfied", mi(SocialSentimentVerySatisfied)},
	{"Social Share", "socialshare", "SocialShare", mi(SocialShare)},
	{"Social Whats Hot", "socialwhatshot", "SocialWhatsHot", mi(SocialWhatsHot)},
	{"Toggle Check Box", "togglecheckbox", "ToggleCheckBox", mi(ToggleCheckBox)},
	{"Toggle Check Box Outline Blank", "togglecheckboxoutlineblank", "ToggleCheckBoxOutlineBlank", mi(ToggleCheckBoxOutlineBlank)},
	{"Toggle Indeterminate Check Box", "toggleindeterminatecheckbox", "ToggleIndeterminateCheckBox", mi(ToggleIndeterminateCheckBox)},
	{"Toggle Radio Button Checked", "toggleradiobuttonchecked", "ToggleRadioButtonChecked", mi(ToggleRadioButtonChecked)},
	{"Toggle Radio Button Unchecked", "toggleradiobuttonunchecked", "ToggleRadioButtonUnchecked", mi(ToggleRadioButtonUnchecked)},
	{"Toggle Star", "togglestar", "ToggleStar", mi(ToggleStar)},
	{"Toggle Star Border", "togglestarborder", "ToggleStarBorder", mi(ToggleStarBorder)},
	{"Toggle Star Half", "togglestarhalf", "ToggleStarHalf", mi(ToggleStarHalf)},
}
