// This is generated code. DO NOT EDIT
package main

import (
	. "golang.org/x/exp/shiny/materialdesign/icons"
)

const numEntries = 961

var allEntries = [961]iconEntry{
	{"AVAV Timer", "AVAVTimer", "avavtimer", mi(AVAVTimer)},
	{"AV Add To Queue", "AVAddToQueue", "avaddtoqueue", mi(AVAddToQueue)},
	{"AV Airplay", "AVAirplay", "avairplay", mi(AVAirplay)},
	{"AV Album", "AVAlbum", "avalbum", mi(AVAlbum)},
	{"AV Art Track", "AVArtTrack", "avarttrack", mi(AVArtTrack)},
	{"AV Branding Watermark", "AVBrandingWatermark", "avbrandingwatermark", mi(AVBrandingWatermark)},
	{"AV Call To Action", "AVCallToAction", "avcalltoaction", mi(AVCallToAction)},
	{"AV Closed Caption", "AVClosedCaption", "avclosedcaption", mi(AVClosedCaption)},
	{"AV Equalizer", "AVEqualizer", "avequalizer", mi(AVEqualizer)},
	{"AV Explicit", "AVExplicit", "avexplicit", mi(AVExplicit)},
	{"AV Fast Forward", "AVFastForward", "avfastforward", mi(AVFastForward)},
	{"AV Fast Rewind", "AVFastRewind", "avfastrewind", mi(AVFastRewind)},
	{"AV Featured Play List", "AVFeaturedPlayList", "avfeaturedplaylist", mi(AVFeaturedPlayList)},
	{"AV Featured Video", "AVFeaturedVideo", "avfeaturedvideo", mi(AVFeaturedVideo)},
	{"AV Fiber DVR", "AVFiberDVR", "avfiberdvr", mi(AVFiberDVR)},
	{"AV Fiber Manual Record", "AVFiberManualRecord", "avfibermanualrecord", mi(AVFiberManualRecord)},
	{"AV Fiber New", "AVFiberNew", "avfibernew", mi(AVFiberNew)},
	{"AV Fiber Pin", "AVFiberPin", "avfiberpin", mi(AVFiberPin)},
	{"AV Fiber Smart Record", "AVFiberSmartRecord", "avfibersmartrecord", mi(AVFiberSmartRecord)},
	{"AV Forward 10", "AVForward10", "avforward10", mi(AVForward10)},
	{"AV Forward 30", "AVForward30", "avforward30", mi(AVForward30)},
	{"AV Forward 5", "AVForward5", "avforward5", mi(AVForward5)},
	{"AV Games", "AVGames", "avgames", mi(AVGames)},
	{"AVHD", "AVHD", "avhd", mi(AVHD)},
	{"AV Hearing", "AVHearing", "avhearing", mi(AVHearing)},
	{"AV High Quality", "AVHighQuality", "avhighquality", mi(AVHighQuality)},
	{"AV Library Add", "AVLibraryAdd", "avlibraryadd", mi(AVLibraryAdd)},
	{"AV Library Books", "AVLibraryBooks", "avlibrarybooks", mi(AVLibraryBooks)},
	{"AV Library Music", "AVLibraryMusic", "avlibrarymusic", mi(AVLibraryMusic)},
	{"AV Loop", "AVLoop", "avloop", mi(AVLoop)},
	{"AV Mic", "AVMic", "avmic", mi(AVMic)},
	{"AV Mic None", "AVMicNone", "avmicnone", mi(AVMicNone)},
	{"AV Mic Off", "AVMicOff", "avmicoff", mi(AVMicOff)},
	{"AV Movie", "AVMovie", "avmovie", mi(AVMovie)},
	{"AV Music Video", "AVMusicVideo", "avmusicvideo", mi(AVMusicVideo)},
	{"AV New Releases", "AVNewReleases", "avnewreleases", mi(AVNewReleases)},
	{"AV Not Interested", "AVNotInterested", "avnotinterested", mi(AVNotInterested)},
	{"AV Note", "AVNote", "avnote", mi(AVNote)},
	{"AV Pause", "AVPause", "avpause", mi(AVPause)},
	{"AV Pause Circle Filled", "AVPauseCircleFilled", "avpausecirclefilled", mi(AVPauseCircleFilled)},
	{"AV Pause Circle Outline", "AVPauseCircleOutline", "avpausecircleoutline", mi(AVPauseCircleOutline)},
	{"AV Play Arrow", "AVPlayArrow", "avplayarrow", mi(AVPlayArrow)},
	{"AV Play Circle Filled", "AVPlayCircleFilled", "avplaycirclefilled", mi(AVPlayCircleFilled)},
	{"AV Play Circle Outline", "AVPlayCircleOutline", "avplaycircleoutline", mi(AVPlayCircleOutline)},
	{"AV Playlist Add", "AVPlaylistAdd", "avplaylistadd", mi(AVPlaylistAdd)},
	{"AV Playlist Add Check", "AVPlaylistAddCheck", "avplaylistaddcheck", mi(AVPlaylistAddCheck)},
	{"AV Playlist Play", "AVPlaylistPlay", "avplaylistplay", mi(AVPlaylistPlay)},
	{"AV Queue", "AVQueue", "avqueue", mi(AVQueue)},
	{"AV Queue Music", "AVQueueMusic", "avqueuemusic", mi(AVQueueMusic)},
	{"AV Queue Play Next", "AVQueuePlayNext", "avqueueplaynext", mi(AVQueuePlayNext)},
	{"AV Radio", "AVRadio", "avradio", mi(AVRadio)},
	{"AV Recent Actors", "AVRecentActors", "avrecentactors", mi(AVRecentActors)},
	{"AV Remove From Queue", "AVRemoveFromQueue", "avremovefromqueue", mi(AVRemoveFromQueue)},
	{"AV Repeat", "AVRepeat", "avrepeat", mi(AVRepeat)},
	{"AV Repeat One", "AVRepeatOne", "avrepeatone", mi(AVRepeatOne)},
	{"AV Replay", "AVReplay", "avreplay", mi(AVReplay)},
	{"AV Replay 10", "AVReplay10", "avreplay10", mi(AVReplay10)},
	{"AV Replay 30", "AVReplay30", "avreplay30", mi(AVReplay30)},
	{"AV Replay 5", "AVReplay5", "avreplay5", mi(AVReplay5)},
	{"AV Shuffle", "AVShuffle", "avshuffle", mi(AVShuffle)},
	{"AV Skip Next", "AVSkipNext", "avskipnext", mi(AVSkipNext)},
	{"AV Skip Previous", "AVSkipPrevious", "avskipprevious", mi(AVSkipPrevious)},
	{"AV Slow Motion Video", "AVSlowMotionVideo", "avslowmotionvideo", mi(AVSlowMotionVideo)},
	{"AV Snooze", "AVSnooze", "avsnooze", mi(AVSnooze)},
	{"AV Sort By Alpha", "AVSortByAlpha", "avsortbyalpha", mi(AVSortByAlpha)},
	{"AV Stop", "AVStop", "avstop", mi(AVStop)},
	{"AV Subscriptions", "AVSubscriptions", "avsubscriptions", mi(AVSubscriptions)},
	{"AV Subtitles", "AVSubtitles", "avsubtitles", mi(AVSubtitles)},
	{"AV Surround Sound", "AVSurroundSound", "avsurroundsound", mi(AVSurroundSound)},
	{"AV Video Call", "AVVideoCall", "avvideocall", mi(AVVideoCall)},
	{"AV Video Label", "AVVideoLabel", "avvideolabel", mi(AVVideoLabel)},
	{"AV Video Library", "AVVideoLibrary", "avvideolibrary", mi(AVVideoLibrary)},
	{"AV Videocam", "AVVideocam", "avvideocam", mi(AVVideocam)},
	{"AV Videocam Off", "AVVideocamOff", "avvideocamoff", mi(AVVideocamOff)},
	{"AV Volume Down", "AVVolumeDown", "avvolumedown", mi(AVVolumeDown)},
	{"AV Volume Mute", "AVVolumeMute", "avvolumemute", mi(AVVolumeMute)},
	{"AV Volume Off", "AVVolumeOff", "avvolumeoff", mi(AVVolumeOff)},
	{"AV Volume Up", "AVVolumeUp", "avvolumeup", mi(AVVolumeUp)},
	{"AV Web", "AVWeb", "avweb", mi(AVWeb)},
	{"AV Web Asset", "AVWebAsset", "avwebasset", mi(AVWebAsset)},
	{"Action 3 D Rotation", "Action3DRotation", "action3drotation", mi(Action3DRotation)},
	{"Action Accessibility", "ActionAccessibility", "actionaccessibility", mi(ActionAccessibility)},
	{"Action Accessible", "ActionAccessible", "actionaccessible", mi(ActionAccessible)},
	{"Action Account Balance", "ActionAccountBalance", "actionaccountbalance", mi(ActionAccountBalance)},
	{"Action Account Balance Wallet", "ActionAccountBalanceWallet", "actionaccountbalancewallet", mi(ActionAccountBalanceWallet)},
	{"Action Account Box", "ActionAccountBox", "actionaccountbox", mi(ActionAccountBox)},
	{"Action Account Circle", "ActionAccountCircle", "actionaccountcircle", mi(ActionAccountCircle)},
	{"Action Add Shopping Cart", "ActionAddShoppingCart", "actionaddshoppingcart", mi(ActionAddShoppingCart)},
	{"Action Alarm", "ActionAlarm", "actionalarm", mi(ActionAlarm)},
	{"Action Alarm Add", "ActionAlarmAdd", "actionalarmadd", mi(ActionAlarmAdd)},
	{"Action Alarm Off", "ActionAlarmOff", "actionalarmoff", mi(ActionAlarmOff)},
	{"Action Alarm On", "ActionAlarmOn", "actionalarmon", mi(ActionAlarmOn)},
	{"Action All Out", "ActionAllOut", "actionallout", mi(ActionAllOut)},
	{"Action Android", "ActionAndroid", "actionandroid", mi(ActionAndroid)},
	{"Action Announcement", "ActionAnnouncement", "actionannouncement", mi(ActionAnnouncement)},
	{"Action Aspect Ratio", "ActionAspectRatio", "actionaspectratio", mi(ActionAspectRatio)},
	{"Action Assessment", "ActionAssessment", "actionassessment", mi(ActionAssessment)},
	{"Action Assignment", "ActionAssignment", "actionassignment", mi(ActionAssignment)},
	{"Action Assignment Ind", "ActionAssignmentInd", "actionassignmentind", mi(ActionAssignmentInd)},
	{"Action Assignment Late", "ActionAssignmentLate", "actionassignmentlate", mi(ActionAssignmentLate)},
	{"Action Assignment Return", "ActionAssignmentReturn", "actionassignmentreturn", mi(ActionAssignmentReturn)},
	{"Action Assignment Returned", "ActionAssignmentReturned", "actionassignmentreturned", mi(ActionAssignmentReturned)},
	{"Action Assignment Turned In", "ActionAssignmentTurnedIn", "actionassignmentturnedin", mi(ActionAssignmentTurnedIn)},
	{"Action Autorenew", "ActionAutorenew", "actionautorenew", mi(ActionAutorenew)},
	{"Action Backup", "ActionBackup", "actionbackup", mi(ActionBackup)},
	{"Action Book", "ActionBook", "actionbook", mi(ActionBook)},
	{"Action Bookmark", "ActionBookmark", "actionbookmark", mi(ActionBookmark)},
	{"Action Bookmark Border", "ActionBookmarkBorder", "actionbookmarkborder", mi(ActionBookmarkBorder)},
	{"Action Bug Report", "ActionBugReport", "actionbugreport", mi(ActionBugReport)},
	{"Action Build", "ActionBuild", "actionbuild", mi(ActionBuild)},
	{"Action Cached", "ActionCached", "actioncached", mi(ActionCached)},
	{"Action Camera Enhance", "ActionCameraEnhance", "actioncameraenhance", mi(ActionCameraEnhance)},
	{"Action Card Giftcard", "ActionCardGiftcard", "actioncardgiftcard", mi(ActionCardGiftcard)},
	{"Action Card Membership", "ActionCardMembership", "actioncardmembership", mi(ActionCardMembership)},
	{"Action Card Travel", "ActionCardTravel", "actioncardtravel", mi(ActionCardTravel)},
	{"Action Change History", "ActionChangeHistory", "actionchangehistory", mi(ActionChangeHistory)},
	{"Action Check Circle", "ActionCheckCircle", "actioncheckcircle", mi(ActionCheckCircle)},
	{"Action Chrome Reader Mode", "ActionChromeReaderMode", "actionchromereadermode", mi(ActionChromeReaderMode)},
	{"Action Class", "ActionClass", "actionclass", mi(ActionClass)},
	{"Action Code", "ActionCode", "actioncode", mi(ActionCode)},
	{"Action Compare Arrows", "ActionCompareArrows", "actioncomparearrows", mi(ActionCompareArrows)},
	{"Action Copyright", "ActionCopyright", "actioncopyright", mi(ActionCopyright)},
	{"Action Credit Card", "ActionCreditCard", "actioncreditcard", mi(ActionCreditCard)},
	{"Action DNS", "ActionDNS", "actiondns", mi(ActionDNS)},
	{"Action Dashboard", "ActionDashboard", "actiondashboard", mi(ActionDashboard)},
	{"Action Date Range", "ActionDateRange", "actiondaterange", mi(ActionDateRange)},
	{"Action Delete", "ActionDelete", "actiondelete", mi(ActionDelete)},
	{"Action Delete Forever", "ActionDeleteForever", "actiondeleteforever", mi(ActionDeleteForever)},
	{"Action Description", "ActionDescription", "actiondescription", mi(ActionDescription)},
	{"Action Done", "ActionDone", "actiondone", mi(ActionDone)},
	{"Action Done All", "ActionDoneAll", "actiondoneall", mi(ActionDoneAll)},
	{"Action Donut Large", "ActionDonutLarge", "actiondonutlarge", mi(ActionDonutLarge)},
	{"Action Donut Small", "ActionDonutSmall", "actiondonutsmall", mi(ActionDonutSmall)},
	{"Action Eject", "ActionEject", "actioneject", mi(ActionEject)},
	{"Action Euro Symbol", "ActionEuroSymbol", "actioneurosymbol", mi(ActionEuroSymbol)},
	{"Action Event", "ActionEvent", "actionevent", mi(ActionEvent)},
	{"Action Event Seat", "ActionEventSeat", "actioneventseat", mi(ActionEventSeat)},
	{"Action Exit To App", "ActionExitToApp", "actionexittoapp", mi(ActionExitToApp)},
	{"Action Explore", "ActionExplore", "actionexplore", mi(ActionExplore)},
	{"Action Extension", "ActionExtension", "actionextension", mi(ActionExtension)},
	{"Action Face", "ActionFace", "actionface", mi(ActionFace)},
	{"Action Favorite", "ActionFavorite", "actionfavorite", mi(ActionFavorite)},
	{"Action Favorite Border", "ActionFavoriteBorder", "actionfavoriteborder", mi(ActionFavoriteBorder)},
	{"Action Feedback", "ActionFeedback", "actionfeedback", mi(ActionFeedback)},
	{"Action Find In Page", "ActionFindInPage", "actionfindinpage", mi(ActionFindInPage)},
	{"Action Find Replace", "ActionFindReplace", "actionfindreplace", mi(ActionFindReplace)},
	{"Action Fingerprint", "ActionFingerprint", "actionfingerprint", mi(ActionFingerprint)},
	{"Action Flight Land", "ActionFlightLand", "actionflightland", mi(ActionFlightLand)},
	{"Action Flight Takeoff", "ActionFlightTakeoff", "actionflighttakeoff", mi(ActionFlightTakeoff)},
	{"Action Flip To Back", "ActionFlipToBack", "actionfliptoback", mi(ActionFlipToBack)},
	{"Action Flip To Front", "ActionFlipToFront", "actionfliptofront", mi(ActionFlipToFront)},
	{"Action GIF", "ActionGIF", "actiongif", mi(ActionGIF)},
	{"Action G Translate", "ActionGTranslate", "actiongtranslate", mi(ActionGTranslate)},
	{"Action Gavel", "ActionGavel", "actiongavel", mi(ActionGavel)},
	{"Action Get App", "ActionGetApp", "actiongetapp", mi(ActionGetApp)},
	{"Action Grade", "ActionGrade", "actiongrade", mi(ActionGrade)},
	{"Action Group Work", "ActionGroupWork", "actiongroupwork", mi(ActionGroupWork)},
	{"Action HTTP", "ActionHTTP", "actionhttp", mi(ActionHTTP)},
	{"Action HTTPS", "ActionHTTPS", "actionhttps", mi(ActionHTTPS)},
	{"Action Help", "ActionHelp", "actionhelp", mi(ActionHelp)},
	{"Action Help Outline", "ActionHelpOutline", "actionhelpoutline", mi(ActionHelpOutline)},
	{"Action Highlight Off", "ActionHighlightOff", "actionhighlightoff", mi(ActionHighlightOff)},
	{"Action History", "ActionHistory", "actionhistory", mi(ActionHistory)},
	{"Action Home", "ActionHome", "actionhome", mi(ActionHome)},
	{"Action Hourglass Empty", "ActionHourglassEmpty", "actionhourglassempty", mi(ActionHourglassEmpty)},
	{"Action Hourglass Full", "ActionHourglassFull", "actionhourglassfull", mi(ActionHourglassFull)},
	{"Action Important Devices", "ActionImportantDevices", "actionimportantdevices", mi(ActionImportantDevices)},
	{"Action Info", "ActionInfo", "actioninfo", mi(ActionInfo)},
	{"Action Info Outline", "ActionInfoOutline", "actioninfooutline", mi(ActionInfoOutline)},
	{"Action Input", "ActionInput", "actioninput", mi(ActionInput)},
	{"Action Invert Colors", "ActionInvertColors", "actioninvertcolors", mi(ActionInvertColors)},
	{"Action Label", "ActionLabel", "actionlabel", mi(ActionLabel)},
	{"Action Label Outline", "ActionLabelOutline", "actionlabeloutline", mi(ActionLabelOutline)},
	{"Action Language", "ActionLanguage", "actionlanguage", mi(ActionLanguage)},
	{"Action Launch", "ActionLaunch", "actionlaunch", mi(ActionLaunch)},
	{"Action Lightbulb Outline", "ActionLightbulbOutline", "actionlightbulboutline", mi(ActionLightbulbOutline)},
	{"Action Line Style", "ActionLineStyle", "actionlinestyle", mi(ActionLineStyle)},
	{"Action Line Weight", "ActionLineWeight", "actionlineweight", mi(ActionLineWeight)},
	{"Action List", "ActionList", "actionlist", mi(ActionList)},
	{"Action Lock", "ActionLock", "actionlock", mi(ActionLock)},
	{"Action Lock Open", "ActionLockOpen", "actionlockopen", mi(ActionLockOpen)},
	{"Action Lock Outline", "ActionLockOutline", "actionlockoutline", mi(ActionLockOutline)},
	{"Action Loyalty", "ActionLoyalty", "actionloyalty", mi(ActionLoyalty)},
	{"Action Mark Unread Mailbox", "ActionMarkUnreadMailbox", "actionmarkunreadmailbox", mi(ActionMarkUnreadMailbox)},
	{"Action Motorcycle", "ActionMotorcycle", "actionmotorcycle", mi(ActionMotorcycle)},
	{"Action Note Add", "ActionNoteAdd", "actionnoteadd", mi(ActionNoteAdd)},
	{"Action Offline Pin", "ActionOfflinePin", "actionofflinepin", mi(ActionOfflinePin)},
	{"Action Opacity", "ActionOpacity", "actionopacity", mi(ActionOpacity)},
	{"Action Open In Browser", "ActionOpenInBrowser", "actionopeninbrowser", mi(ActionOpenInBrowser)},
	{"Action Open In New", "ActionOpenInNew", "actionopeninnew", mi(ActionOpenInNew)},
	{"Action Open With", "ActionOpenWith", "actionopenwith", mi(ActionOpenWith)},
	{"Action Pageview", "ActionPageview", "actionpageview", mi(ActionPageview)},
	{"Action Pan Tool", "ActionPanTool", "actionpantool", mi(ActionPanTool)},
	{"Action Payment", "ActionPayment", "actionpayment", mi(ActionPayment)},
	{"Action Perm Camera Mic", "ActionPermCameraMic", "actionpermcameramic", mi(ActionPermCameraMic)},
	{"Action Perm Contact Calendar", "ActionPermContactCalendar", "actionpermcontactcalendar", mi(ActionPermContactCalendar)},
	{"Action Perm Data Setting", "ActionPermDataSetting", "actionpermdatasetting", mi(ActionPermDataSetting)},
	{"Action Perm Device Information", "ActionPermDeviceInformation", "actionpermdeviceinformation", mi(ActionPermDeviceInformation)},
	{"Action Perm Identity", "ActionPermIdentity", "actionpermidentity", mi(ActionPermIdentity)},
	{"Action Perm Media", "ActionPermMedia", "actionpermmedia", mi(ActionPermMedia)},
	{"Action Perm Phone Msg", "ActionPermPhoneMsg", "actionpermphonemsg", mi(ActionPermPhoneMsg)},
	{"Action Perm Scan Wi Fi", "ActionPermScanWiFi", "actionpermscanwifi", mi(ActionPermScanWiFi)},
	{"Action Pets", "ActionPets", "actionpets", mi(ActionPets)},
	{"Action Picture In Picture", "ActionPictureInPicture", "actionpictureinpicture", mi(ActionPictureInPicture)},
	{"Action Picture In Picture Alt", "ActionPictureInPictureAlt", "actionpictureinpicturealt", mi(ActionPictureInPictureAlt)},
	{"Action Play For Work", "ActionPlayForWork", "actionplayforwork", mi(ActionPlayForWork)},
	{"Action Polymer", "ActionPolymer", "actionpolymer", mi(ActionPolymer)},
	{"Action Power Settings New", "ActionPowerSettingsNew", "actionpowersettingsnew", mi(ActionPowerSettingsNew)},
	{"Action Pregnant Woman", "ActionPregnantWoman", "actionpregnantwoman", mi(ActionPregnantWoman)},
	{"Action Print", "ActionPrint", "actionprint", mi(ActionPrint)},
	{"Action Query Builder", "ActionQueryBuilder", "actionquerybuilder", mi(ActionQueryBuilder)},
	{"Action Question Answer", "ActionQuestionAnswer", "actionquestionanswer", mi(ActionQuestionAnswer)},
	{"Action Receipt", "ActionReceipt", "actionreceipt", mi(ActionReceipt)},
	{"Action Record Voice Over", "ActionRecordVoiceOver", "actionrecordvoiceover", mi(ActionRecordVoiceOver)},
	{"Action Redeem", "ActionRedeem", "actionredeem", mi(ActionRedeem)},
	{"Action Remove Shopping Cart", "ActionRemoveShoppingCart", "actionremoveshoppingcart", mi(ActionRemoveShoppingCart)},
	{"Action Reorder", "ActionReorder", "actionreorder", mi(ActionReorder)},
	{"Action Report Problem", "ActionReportProblem", "actionreportproblem", mi(ActionReportProblem)},
	{"Action Restore", "ActionRestore", "actionrestore", mi(ActionRestore)},
	{"Action Restore Page", "ActionRestorePage", "actionrestorepage", mi(ActionRestorePage)},
	{"Action Room", "ActionRoom", "actionroom", mi(ActionRoom)},
	{"Action Rounded Corner", "ActionRoundedCorner", "actionroundedcorner", mi(ActionRoundedCorner)},
	{"Action Rowing", "ActionRowing", "actionrowing", mi(ActionRowing)},
	{"Action Schedule", "ActionSchedule", "actionschedule", mi(ActionSchedule)},
	{"Action Search", "ActionSearch", "actionsearch", mi(ActionSearch)},
	{"Action Settings", "ActionSettings", "actionsettings", mi(ActionSettings)},
	{"Action Settings Applications", "ActionSettingsApplications", "actionsettingsapplications", mi(ActionSettingsApplications)},
	{"Action Settings Backup Restore", "ActionSettingsBackupRestore", "actionsettingsbackuprestore", mi(ActionSettingsBackupRestore)},
	{"Action Settings Bluetooth", "ActionSettingsBluetooth", "actionsettingsbluetooth", mi(ActionSettingsBluetooth)},
	{"Action Settings Brightness", "ActionSettingsBrightness", "actionsettingsbrightness", mi(ActionSettingsBrightness)},
	{"Action Settings Cell", "ActionSettingsCell", "actionsettingscell", mi(ActionSettingsCell)},
	{"Action Settings Ethernet", "ActionSettingsEthernet", "actionsettingsethernet", mi(ActionSettingsEthernet)},
	{"Action Settings Input Antenna", "ActionSettingsInputAntenna", "actionsettingsinputantenna", mi(ActionSettingsInputAntenna)},
	{"Action Settings Input Component", "ActionSettingsInputComponent", "actionsettingsinputcomponent", mi(ActionSettingsInputComponent)},
	{"Action Settings Input Composite", "ActionSettingsInputComposite", "actionsettingsinputcomposite", mi(ActionSettingsInputComposite)},
	{"Action Settings Input HDMI", "ActionSettingsInputHDMI", "actionsettingsinputhdmi", mi(ActionSettingsInputHDMI)},
	{"Action Settings Input S Video", "ActionSettingsInputSVideo", "actionsettingsinputsvideo", mi(ActionSettingsInputSVideo)},
	{"Action Settings Overscan", "ActionSettingsOverscan", "actionsettingsoverscan", mi(ActionSettingsOverscan)},
	{"Action Settings Phone", "ActionSettingsPhone", "actionsettingsphone", mi(ActionSettingsPhone)},
	{"Action Settings Power", "ActionSettingsPower", "actionsettingspower", mi(ActionSettingsPower)},
	{"Action Settings Remote", "ActionSettingsRemote", "actionsettingsremote", mi(ActionSettingsRemote)},
	{"Action Settings Voice", "ActionSettingsVoice", "actionsettingsvoice", mi(ActionSettingsVoice)},
	{"Action Shop", "ActionShop", "actionshop", mi(ActionShop)},
	{"Action Shop Two", "ActionShopTwo", "actionshoptwo", mi(ActionShopTwo)},
	{"Action Shopping Basket", "ActionShoppingBasket", "actionshoppingbasket", mi(ActionShoppingBasket)},
	{"Action Shopping Cart", "ActionShoppingCart", "actionshoppingcart", mi(ActionShoppingCart)},
	{"Action Speaker Notes", "ActionSpeakerNotes", "actionspeakernotes", mi(ActionSpeakerNotes)},
	{"Action Speaker Notes Off", "ActionSpeakerNotesOff", "actionspeakernotesoff", mi(ActionSpeakerNotesOff)},
	{"Action Spellcheck", "ActionSpellcheck", "actionspellcheck", mi(ActionSpellcheck)},
	{"Action Star Rate", "ActionStarRate", "actionstarrate", mi(ActionStarRate)},
	{"Action Stars", "ActionStars", "actionstars", mi(ActionStars)},
	{"Action Store", "ActionStore", "actionstore", mi(ActionStore)},
	{"Action Subject", "ActionSubject", "actionsubject", mi(ActionSubject)},
	{"Action Supervisor Account", "ActionSupervisorAccount", "actionsupervisoraccount", mi(ActionSupervisorAccount)},
	{"Action Swap Horiz", "ActionSwapHoriz", "actionswaphoriz", mi(ActionSwapHoriz)},
	{"Action Swap Vert", "ActionSwapVert", "actionswapvert", mi(ActionSwapVert)},
	{"Action Swap Vertical Circle", "ActionSwapVerticalCircle", "actionswapverticalcircle", mi(ActionSwapVerticalCircle)},
	{"Action System Update Alt", "ActionSystemUpdateAlt", "actionsystemupdatealt", mi(ActionSystemUpdateAlt)},
	{"Action TOC", "ActionTOC", "actiontoc", mi(ActionTOC)},
	{"Action Tab", "ActionTab", "actiontab", mi(ActionTab)},
	{"Action Tab Unselected", "ActionTabUnselected", "actiontabunselected", mi(ActionTabUnselected)},
	{"Action Theaters", "ActionTheaters", "actiontheaters", mi(ActionTheaters)},
	{"Action Thumb Down", "ActionThumbDown", "actionthumbdown", mi(ActionThumbDown)},
	{"Action Thumb Up", "ActionThumbUp", "actionthumbup", mi(ActionThumbUp)},
	{"Action Thumbs Up Down", "ActionThumbsUpDown", "actionthumbsupdown", mi(ActionThumbsUpDown)},
	{"Action Timeline", "ActionTimeline", "actiontimeline", mi(ActionTimeline)},
	{"Action Today", "ActionToday", "actiontoday", mi(ActionToday)},
	{"Action Toll", "ActionToll", "actiontoll", mi(ActionToll)},
	{"Action Touch App", "ActionTouchApp", "actiontouchapp", mi(ActionTouchApp)},
	{"Action Track Changes", "ActionTrackChanges", "actiontrackchanges", mi(ActionTrackChanges)},
	{"Action Translate", "ActionTranslate", "actiontranslate", mi(ActionTranslate)},
	{"Action Trending Down", "ActionTrendingDown", "actiontrendingdown", mi(ActionTrendingDown)},
	{"Action Trending Flat", "ActionTrendingFlat", "actiontrendingflat", mi(ActionTrendingFlat)},
	{"Action Trending Up", "ActionTrendingUp", "actiontrendingup", mi(ActionTrendingUp)},
	{"Action Turned In", "ActionTurnedIn", "actionturnedin", mi(ActionTurnedIn)},
	{"Action Turned In Not", "ActionTurnedInNot", "actionturnedinnot", mi(ActionTurnedInNot)},
	{"Action Update", "ActionUpdate", "actionupdate", mi(ActionUpdate)},
	{"Action Verified User", "ActionVerifiedUser", "actionverifieduser", mi(ActionVerifiedUser)},
	{"Action View Agenda", "ActionViewAgenda", "actionviewagenda", mi(ActionViewAgenda)},
	{"Action View Array", "ActionViewArray", "actionviewarray", mi(ActionViewArray)},
	{"Action View Carousel", "ActionViewCarousel", "actionviewcarousel", mi(ActionViewCarousel)},
	{"Action View Column", "ActionViewColumn", "actionviewcolumn", mi(ActionViewColumn)},
	{"Action View Day", "ActionViewDay", "actionviewday", mi(ActionViewDay)},
	{"Action View Headline", "ActionViewHeadline", "actionviewheadline", mi(ActionViewHeadline)},
	{"Action View List", "ActionViewList", "actionviewlist", mi(ActionViewList)},
	{"Action View Module", "ActionViewModule", "actionviewmodule", mi(ActionViewModule)},
	{"Action View Quilt", "ActionViewQuilt", "actionviewquilt", mi(ActionViewQuilt)},
	{"Action View Stream", "ActionViewStream", "actionviewstream", mi(ActionViewStream)},
	{"Action View Week", "ActionViewWeek", "actionviewweek", mi(ActionViewWeek)},
	{"Action Visibility", "ActionVisibility", "actionvisibility", mi(ActionVisibility)},
	{"Action Visibility Off", "ActionVisibilityOff", "actionvisibilityoff", mi(ActionVisibilityOff)},
	{"Action Watch Later", "ActionWatchLater", "actionwatchlater", mi(ActionWatchLater)},
	{"Action Work", "ActionWork", "actionwork", mi(ActionWork)},
	{"Action Youtube Searched For", "ActionYoutubeSearchedFor", "actionyoutubesearchedfor", mi(ActionYoutubeSearchedFor)},
	{"Action Zoom In", "ActionZoomIn", "actionzoomin", mi(ActionZoomIn)},
	{"Action Zoom Out", "ActionZoomOut", "actionzoomout", mi(ActionZoomOut)},
	{"Alert Add Alert", "AlertAddAlert", "alertaddalert", mi(AlertAddAlert)},
	{"Alert Error", "AlertError", "alerterror", mi(AlertError)},
	{"Alert Error Outline", "AlertErrorOutline", "alerterroroutline", mi(AlertErrorOutline)},
	{"Alert Warning", "AlertWarning", "alertwarning", mi(AlertWarning)},
	{"Communication Business", "CommunicationBusiness", "communicationbusiness", mi(CommunicationBusiness)},
	{"Communication Call", "CommunicationCall", "communicationcall", mi(CommunicationCall)},
	{"Communication Call End", "CommunicationCallEnd", "communicationcallend", mi(CommunicationCallEnd)},
	{"Communication Call Made", "CommunicationCallMade", "communicationcallmade", mi(CommunicationCallMade)},
	{"Communication Call Merge", "CommunicationCallMerge", "communicationcallmerge", mi(CommunicationCallMerge)},
	{"Communication Call Missed", "CommunicationCallMissed", "communicationcallmissed", mi(CommunicationCallMissed)},
	{"Communication Call Missed Outgoing", "CommunicationCallMissedOutgoing", "communicationcallmissedoutgoing", mi(CommunicationCallMissedOutgoing)},
	{"Communication Call Received", "CommunicationCallReceived", "communicationcallreceived", mi(CommunicationCallReceived)},
	{"Communication Call Split", "CommunicationCallSplit", "communicationcallsplit", mi(CommunicationCallSplit)},
	{"Communication Chat", "CommunicationChat", "communicationchat", mi(CommunicationChat)},
	{"Communication Chat Bubble", "CommunicationChatBubble", "communicationchatbubble", mi(CommunicationChatBubble)},
	{"Communication Chat Bubble Outline", "CommunicationChatBubbleOutline", "communicationchatbubbleoutline", mi(CommunicationChatBubbleOutline)},
	{"Communication Clear All", "CommunicationClearAll", "communicationclearall", mi(CommunicationClearAll)},
	{"Communication Comment", "CommunicationComment", "communicationcomment", mi(CommunicationComment)},
	{"Communication Contact Mail", "CommunicationContactMail", "communicationcontactmail", mi(CommunicationContactMail)},
	{"Communication Contact Phone", "CommunicationContactPhone", "communicationcontactphone", mi(CommunicationContactPhone)},
	{"Communication Contacts", "CommunicationContacts", "communicationcontacts", mi(CommunicationContacts)},
	{"Communication Dialer SIP", "CommunicationDialerSIP", "communicationdialersip", mi(CommunicationDialerSIP)},
	{"Communication Dialpad", "CommunicationDialpad", "communicationdialpad", mi(CommunicationDialpad)},
	{"Communication Email", "CommunicationEmail", "communicationemail", mi(CommunicationEmail)},
	{"Communication Forum", "CommunicationForum", "communicationforum", mi(CommunicationForum)},
	{"Communication Import Contacts", "CommunicationImportContacts", "communicationimportcontacts", mi(CommunicationImportContacts)},
	{"Communication Import Export", "CommunicationImportExport", "communicationimportexport", mi(CommunicationImportExport)},
	{"Communication Invert Colors Off", "CommunicationInvertColorsOff", "communicationinvertcolorsoff", mi(CommunicationInvertColorsOff)},
	{"Communication Live Help", "CommunicationLiveHelp", "communicationlivehelp", mi(CommunicationLiveHelp)},
	{"Communication Location Off", "CommunicationLocationOff", "communicationlocationoff", mi(CommunicationLocationOff)},
	{"Communication Location On", "CommunicationLocationOn", "communicationlocationon", mi(CommunicationLocationOn)},
	{"Communication Mail Outline", "CommunicationMailOutline", "communicationmailoutline", mi(CommunicationMailOutline)},
	{"Communication Message", "CommunicationMessage", "communicationmessage", mi(CommunicationMessage)},
	{"Communication No SIM", "CommunicationNoSIM", "communicationnosim", mi(CommunicationNoSIM)},
	{"Communication Phone", "CommunicationPhone", "communicationphone", mi(CommunicationPhone)},
	{"Communication Phone Link Erase", "CommunicationPhoneLinkErase", "communicationphonelinkerase", mi(CommunicationPhoneLinkErase)},
	{"Communication Phone Link Lock", "CommunicationPhoneLinkLock", "communicationphonelinklock", mi(CommunicationPhoneLinkLock)},
	{"Communication Phone Link Ring", "CommunicationPhoneLinkRing", "communicationphonelinkring", mi(CommunicationPhoneLinkRing)},
	{"Communication Phone Link Setup", "CommunicationPhoneLinkSetup", "communicationphonelinksetup", mi(CommunicationPhoneLinkSetup)},
	{"Communication Portable Wi Fi Off", "CommunicationPortableWiFiOff", "communicationportablewifioff", mi(CommunicationPortableWiFiOff)},
	{"Communication Present To All", "CommunicationPresentToAll", "communicationpresenttoall", mi(CommunicationPresentToAll)},
	{"Communication RSS Feed", "CommunicationRSSFeed", "communicationrssfeed", mi(CommunicationRSSFeed)},
	{"Communication Ring Volume", "CommunicationRingVolume", "communicationringvolume", mi(CommunicationRingVolume)},
	{"Communication Screen Share", "CommunicationScreenShare", "communicationscreenshare", mi(CommunicationScreenShare)},
	{"Communication Speaker Phone", "CommunicationSpeakerPhone", "communicationspeakerphone", mi(CommunicationSpeakerPhone)},
	{"Communication Stay Current Landscape", "CommunicationStayCurrentLandscape", "communicationstaycurrentlandscape", mi(CommunicationStayCurrentLandscape)},
	{"Communication Stay Current Portrait", "CommunicationStayCurrentPortrait", "communicationstaycurrentportrait", mi(CommunicationStayCurrentPortrait)},
	{"Communication Stay Primary Landscape", "CommunicationStayPrimaryLandscape", "communicationstayprimarylandscape", mi(CommunicationStayPrimaryLandscape)},
	{"Communication Stay Primary Portrait", "CommunicationStayPrimaryPortrait", "communicationstayprimaryportrait", mi(CommunicationStayPrimaryPortrait)},
	{"Communication Stop Screen Share", "CommunicationStopScreenShare", "communicationstopscreenshare", mi(CommunicationStopScreenShare)},
	{"Communication Swap Calls", "CommunicationSwapCalls", "communicationswapcalls", mi(CommunicationSwapCalls)},
	{"Communication Text SMS", "CommunicationTextSMS", "communicationtextsms", mi(CommunicationTextSMS)},
	{"Communication VPN Key", "CommunicationVPNKey", "communicationvpnkey", mi(CommunicationVPNKey)},
	{"Communication Voicemail", "CommunicationVoicemail", "communicationvoicemail", mi(CommunicationVoicemail)},
	{"Content Add", "ContentAdd", "contentadd", mi(ContentAdd)},
	{"Content Add Box", "ContentAddBox", "contentaddbox", mi(ContentAddBox)},
	{"Content Add Circle", "ContentAddCircle", "contentaddcircle", mi(ContentAddCircle)},
	{"Content Add Circle Outline", "ContentAddCircleOutline", "contentaddcircleoutline", mi(ContentAddCircleOutline)},
	{"Content Archive", "ContentArchive", "contentarchive", mi(ContentArchive)},
	{"Content Backspace", "ContentBackspace", "contentbackspace", mi(ContentBackspace)},
	{"Content Block", "ContentBlock", "contentblock", mi(ContentBlock)},
	{"Content Clear", "ContentClear", "contentclear", mi(ContentClear)},
	{"Content Content Copy", "ContentContentCopy", "contentcontentcopy", mi(ContentContentCopy)},
	{"Content Content Cut", "ContentContentCut", "contentcontentcut", mi(ContentContentCut)},
	{"Content Content Paste", "ContentContentPaste", "contentcontentpaste", mi(ContentContentPaste)},
	{"Content Create", "ContentCreate", "contentcreate", mi(ContentCreate)},
	{"Content Delete Sweep", "ContentDeleteSweep", "contentdeletesweep", mi(ContentDeleteSweep)},
	{"Content Drafts", "ContentDrafts", "contentdrafts", mi(ContentDrafts)},
	{"Content Filter List", "ContentFilterList", "contentfilterlist", mi(ContentFilterList)},
	{"Content Flag", "ContentFlag", "contentflag", mi(ContentFlag)},
	{"Content Font Download", "ContentFontDownload", "contentfontdownload", mi(ContentFontDownload)},
	{"Content Forward", "ContentForward", "contentforward", mi(ContentForward)},
	{"Content Gesture", "ContentGesture", "contentgesture", mi(ContentGesture)},
	{"Content Inbox", "ContentInbox", "contentinbox", mi(ContentInbox)},
	{"Content Link", "ContentLink", "contentlink", mi(ContentLink)},
	{"Content Low Priority", "ContentLowPriority", "contentlowpriority", mi(ContentLowPriority)},
	{"Content Mail", "ContentMail", "contentmail", mi(ContentMail)},
	{"Content Mark Unread", "ContentMarkUnread", "contentmarkunread", mi(ContentMarkUnread)},
	{"Content Move To Inbox", "ContentMoveToInbox", "contentmovetoinbox", mi(ContentMoveToInbox)},
	{"Content Next Week", "ContentNextWeek", "contentnextweek", mi(ContentNextWeek)},
	{"Content Redo", "ContentRedo", "contentredo", mi(ContentRedo)},
	{"Content Remove", "ContentRemove", "contentremove", mi(ContentRemove)},
	{"Content Remove Circle", "ContentRemoveCircle", "contentremovecircle", mi(ContentRemoveCircle)},
	{"Content Remove Circle Outline", "ContentRemoveCircleOutline", "contentremovecircleoutline", mi(ContentRemoveCircleOutline)},
	{"Content Reply", "ContentReply", "contentreply", mi(ContentReply)},
	{"Content Reply All", "ContentReplyAll", "contentreplyall", mi(ContentReplyAll)},
	{"Content Report", "ContentReport", "contentreport", mi(ContentReport)},
	{"Content Save", "ContentSave", "contentsave", mi(ContentSave)},
	{"Content Select All", "ContentSelectAll", "contentselectall", mi(ContentSelectAll)},
	{"Content Send", "ContentSend", "contentsend", mi(ContentSend)},
	{"Content Sort", "ContentSort", "contentsort", mi(ContentSort)},
	{"Content Text Format", "ContentTextFormat", "contenttextformat", mi(ContentTextFormat)},
	{"Content Unarchive", "ContentUnarchive", "contentunarchive", mi(ContentUnarchive)},
	{"Content Undo", "ContentUndo", "contentundo", mi(ContentUndo)},
	{"Content Weekend", "ContentWeekend", "contentweekend", mi(ContentWeekend)},
	{"Device Access Alarm", "DeviceAccessAlarm", "deviceaccessalarm", mi(DeviceAccessAlarm)},
	{"Device Access Alarms", "DeviceAccessAlarms", "deviceaccessalarms", mi(DeviceAccessAlarms)},
	{"Device Access Time", "DeviceAccessTime", "deviceaccesstime", mi(DeviceAccessTime)},
	{"Device Add Alarm", "DeviceAddAlarm", "deviceaddalarm", mi(DeviceAddAlarm)},
	{"Device Airplane Mode Active", "DeviceAirplaneModeActive", "deviceairplanemodeactive", mi(DeviceAirplaneModeActive)},
	{"Device Airplane Mode Inactive", "DeviceAirplaneModeInactive", "deviceairplanemodeinactive", mi(DeviceAirplaneModeInactive)},
	{"Device Battery 20", "DeviceBattery20", "devicebattery20", mi(DeviceBattery20)},
	{"Device Battery 30", "DeviceBattery30", "devicebattery30", mi(DeviceBattery30)},
	{"Device Battery 50", "DeviceBattery50", "devicebattery50", mi(DeviceBattery50)},
	{"Device Battery 60", "DeviceBattery60", "devicebattery60", mi(DeviceBattery60)},
	{"Device Battery 80", "DeviceBattery80", "devicebattery80", mi(DeviceBattery80)},
	{"Device Battery 90", "DeviceBattery90", "devicebattery90", mi(DeviceBattery90)},
	{"Device Battery Alert", "DeviceBatteryAlert", "devicebatteryalert", mi(DeviceBatteryAlert)},
	{"Device Battery Charging 20", "DeviceBatteryCharging20", "devicebatterycharging20", mi(DeviceBatteryCharging20)},
	{"Device Battery Charging 30", "DeviceBatteryCharging30", "devicebatterycharging30", mi(DeviceBatteryCharging30)},
	{"Device Battery Charging 50", "DeviceBatteryCharging50", "devicebatterycharging50", mi(DeviceBatteryCharging50)},
	{"Device Battery Charging 60", "DeviceBatteryCharging60", "devicebatterycharging60", mi(DeviceBatteryCharging60)},
	{"Device Battery Charging 80", "DeviceBatteryCharging80", "devicebatterycharging80", mi(DeviceBatteryCharging80)},
	{"Device Battery Charging 90", "DeviceBatteryCharging90", "devicebatterycharging90", mi(DeviceBatteryCharging90)},
	{"Device Battery Charging Full", "DeviceBatteryChargingFull", "devicebatterychargingfull", mi(DeviceBatteryChargingFull)},
	{"Device Battery Full", "DeviceBatteryFull", "devicebatteryfull", mi(DeviceBatteryFull)},
	{"Device Battery Std", "DeviceBatteryStd", "devicebatterystd", mi(DeviceBatteryStd)},
	{"Device Battery Unknown", "DeviceBatteryUnknown", "devicebatteryunknown", mi(DeviceBatteryUnknown)},
	{"Device Bluetooth", "DeviceBluetooth", "devicebluetooth", mi(DeviceBluetooth)},
	{"Device Bluetooth Connected", "DeviceBluetoothConnected", "devicebluetoothconnected", mi(DeviceBluetoothConnected)},
	{"Device Bluetooth Disabled", "DeviceBluetoothDisabled", "devicebluetoothdisabled", mi(DeviceBluetoothDisabled)},
	{"Device Bluetooth Searching", "DeviceBluetoothSearching", "devicebluetoothsearching", mi(DeviceBluetoothSearching)},
	{"Device Brightness Auto", "DeviceBrightnessAuto", "devicebrightnessauto", mi(DeviceBrightnessAuto)},
	{"Device Brightness High", "DeviceBrightnessHigh", "devicebrightnesshigh", mi(DeviceBrightnessHigh)},
	{"Device Brightness Low", "DeviceBrightnessLow", "devicebrightnesslow", mi(DeviceBrightnessLow)},
	{"Device Brightness Medium", "DeviceBrightnessMedium", "devicebrightnessmedium", mi(DeviceBrightnessMedium)},
	{"Device DVR", "DeviceDVR", "devicedvr", mi(DeviceDVR)},
	{"Device Data Usage", "DeviceDataUsage", "devicedatausage", mi(DeviceDataUsage)},
	{"Device Developer Mode", "DeviceDeveloperMode", "devicedevelopermode", mi(DeviceDeveloperMode)},
	{"Device Devices", "DeviceDevices", "devicedevices", mi(DeviceDevices)},
	{"Device GPS Fixed", "DeviceGPSFixed", "devicegpsfixed", mi(DeviceGPSFixed)},
	{"Device GPS Not Fixed", "DeviceGPSNotFixed", "devicegpsnotfixed", mi(DeviceGPSNotFixed)},
	{"Device GPS Off", "DeviceGPSOff", "devicegpsoff", mi(DeviceGPSOff)},
	{"Device Graphic Eq", "DeviceGraphicEq", "devicegraphiceq", mi(DeviceGraphicEq)},
	{"Device Location Disabled", "DeviceLocationDisabled", "devicelocationdisabled", mi(DeviceLocationDisabled)},
	{"Device Location Searching", "DeviceLocationSearching", "devicelocationsearching", mi(DeviceLocationSearching)},
	{"Device NFC", "DeviceNFC", "devicenfc", mi(DeviceNFC)},
	{"Device Network Cell", "DeviceNetworkCell", "devicenetworkcell", mi(DeviceNetworkCell)},
	{"Device Network Wi Fi", "DeviceNetworkWiFi", "devicenetworkwifi", mi(DeviceNetworkWiFi)},
	{"Device SD Storage", "DeviceSDStorage", "devicesdstorage", mi(DeviceSDStorage)},
	{"Device Screen Lock Landscape", "DeviceScreenLockLandscape", "devicescreenlocklandscape", mi(DeviceScreenLockLandscape)},
	{"Device Screen Lock Portrait", "DeviceScreenLockPortrait", "devicescreenlockportrait", mi(DeviceScreenLockPortrait)},
	{"Device Screen Lock Rotation", "DeviceScreenLockRotation", "devicescreenlockrotation", mi(DeviceScreenLockRotation)},
	{"Device Screen Rotation", "DeviceScreenRotation", "devicescreenrotation", mi(DeviceScreenRotation)},
	{"Device Settings System Daydream", "DeviceSettingsSystemDaydream", "devicesettingssystemdaydream", mi(DeviceSettingsSystemDaydream)},
	{"Device Signal Cellular 0 Bar", "DeviceSignalCellular0Bar", "devicesignalcellular0bar", mi(DeviceSignalCellular0Bar)},
	{"Device Signal Cellular 1 Bar", "DeviceSignalCellular1Bar", "devicesignalcellular1bar", mi(DeviceSignalCellular1Bar)},
	{"Device Signal Cellular 2 Bar", "DeviceSignalCellular2Bar", "devicesignalcellular2bar", mi(DeviceSignalCellular2Bar)},
	{"Device Signal Cellular 3 Bar", "DeviceSignalCellular3Bar", "devicesignalcellular3bar", mi(DeviceSignalCellular3Bar)},
	{"Device Signal Cellular 4 Bar", "DeviceSignalCellular4Bar", "devicesignalcellular4bar", mi(DeviceSignalCellular4Bar)},
	{"Device Signal Cellular Connected No Internet 0 Bar", "DeviceSignalCellularConnectedNoInternet0Bar", "devicesignalcellularconnectednointernet0bar", mi(DeviceSignalCellularConnectedNoInternet0Bar)},
	{"Device Signal Cellular Connected No Internet 1 Bar", "DeviceSignalCellularConnectedNoInternet1Bar", "devicesignalcellularconnectednointernet1bar", mi(DeviceSignalCellularConnectedNoInternet1Bar)},
	{"Device Signal Cellular Connected No Internet 2 Bar", "DeviceSignalCellularConnectedNoInternet2Bar", "devicesignalcellularconnectednointernet2bar", mi(DeviceSignalCellularConnectedNoInternet2Bar)},
	{"Device Signal Cellular Connected No Internet 3 Bar", "DeviceSignalCellularConnectedNoInternet3Bar", "devicesignalcellularconnectednointernet3bar", mi(DeviceSignalCellularConnectedNoInternet3Bar)},
	{"Device Signal Cellular Connected No Internet 4 Bar", "DeviceSignalCellularConnectedNoInternet4Bar", "devicesignalcellularconnectednointernet4bar", mi(DeviceSignalCellularConnectedNoInternet4Bar)},
	{"Device Signal Cellular No SIM", "DeviceSignalCellularNoSIM", "devicesignalcellularnosim", mi(DeviceSignalCellularNoSIM)},
	{"Device Signal Cellular Null", "DeviceSignalCellularNull", "devicesignalcellularnull", mi(DeviceSignalCellularNull)},
	{"Device Signal Cellular Off", "DeviceSignalCellularOff", "devicesignalcellularoff", mi(DeviceSignalCellularOff)},
	{"Device Signal Wi Fi 0 Bar", "DeviceSignalWiFi0Bar", "devicesignalwifi0bar", mi(DeviceSignalWiFi0Bar)},
	{"Device Signal Wi Fi 1 Bar", "DeviceSignalWiFi1Bar", "devicesignalwifi1bar", mi(DeviceSignalWiFi1Bar)},
	{"Device Signal Wi Fi 1 Bar Lock", "DeviceSignalWiFi1BarLock", "devicesignalwifi1barlock", mi(DeviceSignalWiFi1BarLock)},
	{"Device Signal Wi Fi 2 Bar", "DeviceSignalWiFi2Bar", "devicesignalwifi2bar", mi(DeviceSignalWiFi2Bar)},
	{"Device Signal Wi Fi 2 Bar Lock", "DeviceSignalWiFi2BarLock", "devicesignalwifi2barlock", mi(DeviceSignalWiFi2BarLock)},
	{"Device Signal Wi Fi 3 Bar", "DeviceSignalWiFi3Bar", "devicesignalwifi3bar", mi(DeviceSignalWiFi3Bar)},
	{"Device Signal Wi Fi 3 Bar Lock", "DeviceSignalWiFi3BarLock", "devicesignalwifi3barlock", mi(DeviceSignalWiFi3BarLock)},
	{"Device Signal Wi Fi 4 Bar", "DeviceSignalWiFi4Bar", "devicesignalwifi4bar", mi(DeviceSignalWiFi4Bar)},
	{"Device Signal Wi Fi 4 Bar Lock", "DeviceSignalWiFi4BarLock", "devicesignalwifi4barlock", mi(DeviceSignalWiFi4BarLock)},
	{"Device Signal Wi Fi Off", "DeviceSignalWiFiOff", "devicesignalwifioff", mi(DeviceSignalWiFiOff)},
	{"Device Storage", "DeviceStorage", "devicestorage", mi(DeviceStorage)},
	{"Device USB", "DeviceUSB", "deviceusb", mi(DeviceUSB)},
	{"Device Wallpaper", "DeviceWallpaper", "devicewallpaper", mi(DeviceWallpaper)},
	{"Device Wi Fi Lock", "DeviceWiFiLock", "devicewifilock", mi(DeviceWiFiLock)},
	{"Device Wi Fi Tethering", "DeviceWiFiTethering", "devicewifitethering", mi(DeviceWiFiTethering)},
	{"Device Widgets", "DeviceWidgets", "devicewidgets", mi(DeviceWidgets)},
	{"Editor Attach File", "EditorAttachFile", "editorattachfile", mi(EditorAttachFile)},
	{"Editor Attach Money", "EditorAttachMoney", "editorattachmoney", mi(EditorAttachMoney)},
	{"Editor Border All", "EditorBorderAll", "editorborderall", mi(EditorBorderAll)},
	{"Editor Border Bottom", "EditorBorderBottom", "editorborderbottom", mi(EditorBorderBottom)},
	{"Editor Border Clear", "EditorBorderClear", "editorborderclear", mi(EditorBorderClear)},
	{"Editor Border Color", "EditorBorderColor", "editorbordercolor", mi(EditorBorderColor)},
	{"Editor Border Horizontal", "EditorBorderHorizontal", "editorborderhorizontal", mi(EditorBorderHorizontal)},
	{"Editor Border Inner", "EditorBorderInner", "editorborderinner", mi(EditorBorderInner)},
	{"Editor Border Left", "EditorBorderLeft", "editorborderleft", mi(EditorBorderLeft)},
	{"Editor Border Outer", "EditorBorderOuter", "editorborderouter", mi(EditorBorderOuter)},
	{"Editor Border Right", "EditorBorderRight", "editorborderright", mi(EditorBorderRight)},
	{"Editor Border Style", "EditorBorderStyle", "editorborderstyle", mi(EditorBorderStyle)},
	{"Editor Border Top", "EditorBorderTop", "editorbordertop", mi(EditorBorderTop)},
	{"Editor Border Vertical", "EditorBorderVertical", "editorbordervertical", mi(EditorBorderVertical)},
	{"Editor Bubble Chart", "EditorBubbleChart", "editorbubblechart", mi(EditorBubbleChart)},
	{"Editor Drag Handle", "EditorDragHandle", "editordraghandle", mi(EditorDragHandle)},
	{"Editor Format Align Center", "EditorFormatAlignCenter", "editorformataligncenter", mi(EditorFormatAlignCenter)},
	{"Editor Format Align Justify", "EditorFormatAlignJustify", "editorformatalignjustify", mi(EditorFormatAlignJustify)},
	{"Editor Format Align Left", "EditorFormatAlignLeft", "editorformatalignleft", mi(EditorFormatAlignLeft)},
	{"Editor Format Align Right", "EditorFormatAlignRight", "editorformatalignright", mi(EditorFormatAlignRight)},
	{"Editor Format Bold", "EditorFormatBold", "editorformatbold", mi(EditorFormatBold)},
	{"Editor Format Clear", "EditorFormatClear", "editorformatclear", mi(EditorFormatClear)},
	{"Editor Format Color Fill", "EditorFormatColorFill", "editorformatcolorfill", mi(EditorFormatColorFill)},
	{"Editor Format Color Reset", "EditorFormatColorReset", "editorformatcolorreset", mi(EditorFormatColorReset)},
	{"Editor Format Color Text", "EditorFormatColorText", "editorformatcolortext", mi(EditorFormatColorText)},
	{"Editor Format Indent Decrease", "EditorFormatIndentDecrease", "editorformatindentdecrease", mi(EditorFormatIndentDecrease)},
	{"Editor Format Indent Increase", "EditorFormatIndentIncrease", "editorformatindentincrease", mi(EditorFormatIndentIncrease)},
	{"Editor Format Italic", "EditorFormatItalic", "editorformatitalic", mi(EditorFormatItalic)},
	{"Editor Format Line Spacing", "EditorFormatLineSpacing", "editorformatlinespacing", mi(EditorFormatLineSpacing)},
	{"Editor Format List Bulleted", "EditorFormatListBulleted", "editorformatlistbulleted", mi(EditorFormatListBulleted)},
	{"Editor Format List Numbered", "EditorFormatListNumbered", "editorformatlistnumbered", mi(EditorFormatListNumbered)},
	{"Editor Format Paint", "EditorFormatPaint", "editorformatpaint", mi(EditorFormatPaint)},
	{"Editor Format Quote", "EditorFormatQuote", "editorformatquote", mi(EditorFormatQuote)},
	{"Editor Format Shapes", "EditorFormatShapes", "editorformatshapes", mi(EditorFormatShapes)},
	{"Editor Format Size", "EditorFormatSize", "editorformatsize", mi(EditorFormatSize)},
	{"Editor Format Strikethrough", "EditorFormatStrikethrough", "editorformatstrikethrough", mi(EditorFormatStrikethrough)},
	{"Editor Format Text Direction L To R", "EditorFormatTextDirectionLToR", "editorformattextdirectionltor", mi(EditorFormatTextDirectionLToR)},
	{"Editor Format Text Direction R To L", "EditorFormatTextDirectionRToL", "editorformattextdirectionrtol", mi(EditorFormatTextDirectionRToL)},
	{"Editor Format Underlined", "EditorFormatUnderlined", "editorformatunderlined", mi(EditorFormatUnderlined)},
	{"Editor Functions", "EditorFunctions", "editorfunctions", mi(EditorFunctions)},
	{"Editor Highlight", "EditorHighlight", "editorhighlight", mi(EditorHighlight)},
	{"Editor Insert Chart", "EditorInsertChart", "editorinsertchart", mi(EditorInsertChart)},
	{"Editor Insert Comment", "EditorInsertComment", "editorinsertcomment", mi(EditorInsertComment)},
	{"Editor Insert Drive File", "EditorInsertDriveFile", "editorinsertdrivefile", mi(EditorInsertDriveFile)},
	{"Editor Insert Emoticon", "EditorInsertEmoticon", "editorinsertemoticon", mi(EditorInsertEmoticon)},
	{"Editor Insert Invitation", "EditorInsertInvitation", "editorinsertinvitation", mi(EditorInsertInvitation)},
	{"Editor Insert Link", "EditorInsertLink", "editorinsertlink", mi(EditorInsertLink)},
	{"Editor Insert Photo", "EditorInsertPhoto", "editorinsertphoto", mi(EditorInsertPhoto)},
	{"Editor Linear Scale", "EditorLinearScale", "editorlinearscale", mi(EditorLinearScale)},
	{"Editor Merge Type", "EditorMergeType", "editormergetype", mi(EditorMergeType)},
	{"Editor Mode Comment", "EditorModeComment", "editormodecomment", mi(EditorModeComment)},
	{"Editor Mode Edit", "EditorModeEdit", "editormodeedit", mi(EditorModeEdit)},
	{"Editor Monetization On", "EditorMonetizationOn", "editormonetizationon", mi(EditorMonetizationOn)},
	{"Editor Money Off", "EditorMoneyOff", "editormoneyoff", mi(EditorMoneyOff)},
	{"Editor Multiline Chart", "EditorMultilineChart", "editormultilinechart", mi(EditorMultilineChart)},
	{"Editor Pie Chart", "EditorPieChart", "editorpiechart", mi(EditorPieChart)},
	{"Editor Pie Chart Outlined", "EditorPieChartOutlined", "editorpiechartoutlined", mi(EditorPieChartOutlined)},
	{"Editor Publish", "EditorPublish", "editorpublish", mi(EditorPublish)},
	{"Editor Short Text", "EditorShortText", "editorshorttext", mi(EditorShortText)},
	{"Editor Show Chart", "EditorShowChart", "editorshowchart", mi(EditorShowChart)},
	{"Editor Space Bar", "EditorSpaceBar", "editorspacebar", mi(EditorSpaceBar)},
	{"Editor Strikethrough S", "EditorStrikethroughS", "editorstrikethroughs", mi(EditorStrikethroughS)},
	{"Editor Text Fields", "EditorTextFields", "editortextfields", mi(EditorTextFields)},
	{"Editor Title", "EditorTitle", "editortitle", mi(EditorTitle)},
	{"Editor Vertical Align Bottom", "EditorVerticalAlignBottom", "editorverticalalignbottom", mi(EditorVerticalAlignBottom)},
	{"Editor Vertical Align Center", "EditorVerticalAlignCenter", "editorverticalaligncenter", mi(EditorVerticalAlignCenter)},
	{"Editor Vertical Align Top", "EditorVerticalAlignTop", "editorverticalaligntop", mi(EditorVerticalAlignTop)},
	{"Editor Wrap Text", "EditorWrapText", "editorwraptext", mi(EditorWrapText)},
	{"File Attachment", "FileAttachment", "fileattachment", mi(FileAttachment)},
	{"File Cloud", "FileCloud", "filecloud", mi(FileCloud)},
	{"File Cloud Circle", "FileCloudCircle", "filecloudcircle", mi(FileCloudCircle)},
	{"File Cloud Done", "FileCloudDone", "fileclouddone", mi(FileCloudDone)},
	{"File Cloud Download", "FileCloudDownload", "fileclouddownload", mi(FileCloudDownload)},
	{"File Cloud Off", "FileCloudOff", "filecloudoff", mi(FileCloudOff)},
	{"File Cloud Queue", "FileCloudQueue", "filecloudqueue", mi(FileCloudQueue)},
	{"File Cloud Upload", "FileCloudUpload", "filecloudupload", mi(FileCloudUpload)},
	{"File Create New Folder", "FileCreateNewFolder", "filecreatenewfolder", mi(FileCreateNewFolder)},
	{"File File Download", "FileFileDownload", "filefiledownload", mi(FileFileDownload)},
	{"File File Upload", "FileFileUpload", "filefileupload", mi(FileFileUpload)},
	{"File Folder", "FileFolder", "filefolder", mi(FileFolder)},
	{"File Folder Open", "FileFolderOpen", "filefolderopen", mi(FileFolderOpen)},
	{"File Folder Shared", "FileFolderShared", "filefoldershared", mi(FileFolderShared)},
	{"Hardware Cast", "HardwareCast", "hardwarecast", mi(HardwareCast)},
	{"Hardware Cast Connected", "HardwareCastConnected", "hardwarecastconnected", mi(HardwareCastConnected)},
	{"Hardware Computer", "HardwareComputer", "hardwarecomputer", mi(HardwareComputer)},
	{"Hardware Desktop Mac", "HardwareDesktopMac", "hardwaredesktopmac", mi(HardwareDesktopMac)},
	{"Hardware Desktop Windows", "HardwareDesktopWindows", "hardwaredesktopwindows", mi(HardwareDesktopWindows)},
	{"Hardware Developer Board", "HardwareDeveloperBoard", "hardwaredeveloperboard", mi(HardwareDeveloperBoard)},
	{"Hardware Device Hub", "HardwareDeviceHub", "hardwaredevicehub", mi(HardwareDeviceHub)},
	{"Hardware Devices Other", "HardwareDevicesOther", "hardwaredevicesother", mi(HardwareDevicesOther)},
	{"Hardware Dock", "HardwareDock", "hardwaredock", mi(HardwareDock)},
	{"Hardware Gamepad", "HardwareGamepad", "hardwaregamepad", mi(HardwareGamepad)},
	{"Hardware Headset", "HardwareHeadset", "hardwareheadset", mi(HardwareHeadset)},
	{"Hardware Headset Mic", "HardwareHeadsetMic", "hardwareheadsetmic", mi(HardwareHeadsetMic)},
	{"Hardware Keyboard", "HardwareKeyboard", "hardwarekeyboard", mi(HardwareKeyboard)},
	{"Hardware Keyboard Arrow Down", "HardwareKeyboardArrowDown", "hardwarekeyboardarrowdown", mi(HardwareKeyboardArrowDown)},
	{"Hardware Keyboard Arrow Left", "HardwareKeyboardArrowLeft", "hardwarekeyboardarrowleft", mi(HardwareKeyboardArrowLeft)},
	{"Hardware Keyboard Arrow Right", "HardwareKeyboardArrowRight", "hardwarekeyboardarrowright", mi(HardwareKeyboardArrowRight)},
	{"Hardware Keyboard Arrow Up", "HardwareKeyboardArrowUp", "hardwarekeyboardarrowup", mi(HardwareKeyboardArrowUp)},
	{"Hardware Keyboard Backspace", "HardwareKeyboardBackspace", "hardwarekeyboardbackspace", mi(HardwareKeyboardBackspace)},
	{"Hardware Keyboard Capslock", "HardwareKeyboardCapslock", "hardwarekeyboardcapslock", mi(HardwareKeyboardCapslock)},
	{"Hardware Keyboard Hide", "HardwareKeyboardHide", "hardwarekeyboardhide", mi(HardwareKeyboardHide)},
	{"Hardware Keyboard Return", "HardwareKeyboardReturn", "hardwarekeyboardreturn", mi(HardwareKeyboardReturn)},
	{"Hardware Keyboard Tab", "HardwareKeyboardTab", "hardwarekeyboardtab", mi(HardwareKeyboardTab)},
	{"Hardware Keyboard Voice", "HardwareKeyboardVoice", "hardwarekeyboardvoice", mi(HardwareKeyboardVoice)},
	{"Hardware Laptop", "HardwareLaptop", "hardwarelaptop", mi(HardwareLaptop)},
	{"Hardware Laptop Chromebook", "HardwareLaptopChromebook", "hardwarelaptopchromebook", mi(HardwareLaptopChromebook)},
	{"Hardware Laptop Mac", "HardwareLaptopMac", "hardwarelaptopmac", mi(HardwareLaptopMac)},
	{"Hardware Laptop Windows", "HardwareLaptopWindows", "hardwarelaptopwindows", mi(HardwareLaptopWindows)},
	{"Hardware Memory", "HardwareMemory", "hardwarememory", mi(HardwareMemory)},
	{"Hardware Mouse", "HardwareMouse", "hardwaremouse", mi(HardwareMouse)},
	{"Hardware Phone Android", "HardwarePhoneAndroid", "hardwarephoneandroid", mi(HardwarePhoneAndroid)},
	{"Hardware Phone I Phone", "HardwarePhoneIPhone", "hardwarephoneiphone", mi(HardwarePhoneIPhone)},
	{"Hardware Phone Link", "HardwarePhoneLink", "hardwarephonelink", mi(HardwarePhoneLink)},
	{"Hardware Phone Link Off", "HardwarePhoneLinkOff", "hardwarephonelinkoff", mi(HardwarePhoneLinkOff)},
	{"Hardware Power Input", "HardwarePowerInput", "hardwarepowerinput", mi(HardwarePowerInput)},
	{"Hardware Router", "HardwareRouter", "hardwarerouter", mi(HardwareRouter)},
	{"Hardware SIM Card", "HardwareSIMCard", "hardwaresimcard", mi(HardwareSIMCard)},
	{"Hardware Scanner", "HardwareScanner", "hardwarescanner", mi(HardwareScanner)},
	{"Hardware Security", "HardwareSecurity", "hardwaresecurity", mi(HardwareSecurity)},
	{"Hardware Smartphone", "HardwareSmartphone", "hardwaresmartphone", mi(HardwareSmartphone)},
	{"Hardware Speaker", "HardwareSpeaker", "hardwarespeaker", mi(HardwareSpeaker)},
	{"Hardware Speaker Group", "HardwareSpeakerGroup", "hardwarespeakergroup", mi(HardwareSpeakerGroup)},
	{"Hardware TV", "HardwareTV", "hardwaretv", mi(HardwareTV)},
	{"Hardware Tablet", "HardwareTablet", "hardwaretablet", mi(HardwareTablet)},
	{"Hardware Tablet Android", "HardwareTabletAndroid", "hardwaretabletandroid", mi(HardwareTabletAndroid)},
	{"Hardware Tablet Mac", "HardwareTabletMac", "hardwaretabletmac", mi(HardwareTabletMac)},
	{"Hardware Toys", "HardwareToys", "hardwaretoys", mi(HardwareToys)},
	{"Hardware Videogame Asset", "HardwareVideogameAsset", "hardwarevideogameasset", mi(HardwareVideogameAsset)},
	{"Hardware Watch", "HardwareWatch", "hardwarewatch", mi(HardwareWatch)},
	{"Image Add A Photo", "ImageAddAPhoto", "imageaddaphoto", mi(ImageAddAPhoto)},
	{"Image Add To Photos", "ImageAddToPhotos", "imageaddtophotos", mi(ImageAddToPhotos)},
	{"Image Adjust", "ImageAdjust", "imageadjust", mi(ImageAdjust)},
	{"Image Assistant", "ImageAssistant", "imageassistant", mi(ImageAssistant)},
	{"Image Assistant Photo", "ImageAssistantPhoto", "imageassistantphoto", mi(ImageAssistantPhoto)},
	{"Image Audiotrack", "ImageAudiotrack", "imageaudiotrack", mi(ImageAudiotrack)},
	{"Image Blur Circular", "ImageBlurCircular", "imageblurcircular", mi(ImageBlurCircular)},
	{"Image Blur Linear", "ImageBlurLinear", "imageblurlinear", mi(ImageBlurLinear)},
	{"Image Blur Off", "ImageBlurOff", "imagebluroff", mi(ImageBlurOff)},
	{"Image Blur On", "ImageBlurOn", "imagebluron", mi(ImageBlurOn)},
	{"Image Brightness 1", "ImageBrightness1", "imagebrightness1", mi(ImageBrightness1)},
	{"Image Brightness 2", "ImageBrightness2", "imagebrightness2", mi(ImageBrightness2)},
	{"Image Brightness 3", "ImageBrightness3", "imagebrightness3", mi(ImageBrightness3)},
	{"Image Brightness 4", "ImageBrightness4", "imagebrightness4", mi(ImageBrightness4)},
	{"Image Brightness 5", "ImageBrightness5", "imagebrightness5", mi(ImageBrightness5)},
	{"Image Brightness 6", "ImageBrightness6", "imagebrightness6", mi(ImageBrightness6)},
	{"Image Brightness 7", "ImageBrightness7", "imagebrightness7", mi(ImageBrightness7)},
	{"Image Broken Image", "ImageBrokenImage", "imagebrokenimage", mi(ImageBrokenImage)},
	{"Image Brush", "ImageBrush", "imagebrush", mi(ImageBrush)},
	{"Image Burst Mode", "ImageBurstMode", "imageburstmode", mi(ImageBurstMode)},
	{"Image Camera", "ImageCamera", "imagecamera", mi(ImageCamera)},
	{"Image Camera Alt", "ImageCameraAlt", "imagecameraalt", mi(ImageCameraAlt)},
	{"Image Camera Front", "ImageCameraFront", "imagecamerafront", mi(ImageCameraFront)},
	{"Image Camera Rear", "ImageCameraRear", "imagecamerarear", mi(ImageCameraRear)},
	{"Image Camera Roll", "ImageCameraRoll", "imagecameraroll", mi(ImageCameraRoll)},
	{"Image Center Focus Strong", "ImageCenterFocusStrong", "imagecenterfocusstrong", mi(ImageCenterFocusStrong)},
	{"Image Center Focus Weak", "ImageCenterFocusWeak", "imagecenterfocusweak", mi(ImageCenterFocusWeak)},
	{"Image Collections", "ImageCollections", "imagecollections", mi(ImageCollections)},
	{"Image Collections Bookmark", "ImageCollectionsBookmark", "imagecollectionsbookmark", mi(ImageCollectionsBookmark)},
	{"Image Color Lens", "ImageColorLens", "imagecolorlens", mi(ImageColorLens)},
	{"Image Colorize", "ImageColorize", "imagecolorize", mi(ImageColorize)},
	{"Image Compare", "ImageCompare", "imagecompare", mi(ImageCompare)},
	{"Image Control Point", "ImageControlPoint", "imagecontrolpoint", mi(ImageControlPoint)},
	{"Image Control Point Duplicate", "ImageControlPointDuplicate", "imagecontrolpointduplicate", mi(ImageControlPointDuplicate)},
	{"Image Crop", "ImageCrop", "imagecrop", mi(ImageCrop)},
	{"Image Crop 169", "ImageCrop169", "imagecrop169", mi(ImageCrop169)},
	{"Image Crop 32", "ImageCrop32", "imagecrop32", mi(ImageCrop32)},
	{"Image Crop 54", "ImageCrop54", "imagecrop54", mi(ImageCrop54)},
	{"Image Crop 75", "ImageCrop75", "imagecrop75", mi(ImageCrop75)},
	{"Image Crop DIN", "ImageCropDIN", "imagecropdin", mi(ImageCropDIN)},
	{"Image Crop Free", "ImageCropFree", "imagecropfree", mi(ImageCropFree)},
	{"Image Crop Landscape", "ImageCropLandscape", "imagecroplandscape", mi(ImageCropLandscape)},
	{"Image Crop Original", "ImageCropOriginal", "imagecroporiginal", mi(ImageCropOriginal)},
	{"Image Crop Portrait", "ImageCropPortrait", "imagecropportrait", mi(ImageCropPortrait)},
	{"Image Crop Rotate", "ImageCropRotate", "imagecroprotate", mi(ImageCropRotate)},
	{"Image Crop Square", "ImageCropSquare", "imagecropsquare", mi(ImageCropSquare)},
	{"Image Dehaze", "ImageDehaze", "imagedehaze", mi(ImageDehaze)},
	{"Image Details", "ImageDetails", "imagedetails", mi(ImageDetails)},
	{"Image Edit", "ImageEdit", "imageedit", mi(ImageEdit)},
	{"Image Exposure", "ImageExposure", "imageexposure", mi(ImageExposure)},
	{"Image Exposure Neg 1", "ImageExposureNeg1", "imageexposureneg1", mi(ImageExposureNeg1)},
	{"Image Exposure Neg 2", "ImageExposureNeg2", "imageexposureneg2", mi(ImageExposureNeg2)},
	{"Image Exposure Plus 1", "ImageExposurePlus1", "imageexposureplus1", mi(ImageExposurePlus1)},
	{"Image Exposure Plus 2", "ImageExposurePlus2", "imageexposureplus2", mi(ImageExposurePlus2)},
	{"Image Exposure Zero", "ImageExposureZero", "imageexposurezero", mi(ImageExposureZero)},
	{"Image Filter", "ImageFilter", "imagefilter", mi(ImageFilter)},
	{"Image Filter 1", "ImageFilter1", "imagefilter1", mi(ImageFilter1)},
	{"Image Filter 2", "ImageFilter2", "imagefilter2", mi(ImageFilter2)},
	{"Image Filter 3", "ImageFilter3", "imagefilter3", mi(ImageFilter3)},
	{"Image Filter 4", "ImageFilter4", "imagefilter4", mi(ImageFilter4)},
	{"Image Filter 5", "ImageFilter5", "imagefilter5", mi(ImageFilter5)},
	{"Image Filter 6", "ImageFilter6", "imagefilter6", mi(ImageFilter6)},
	{"Image Filter 7", "ImageFilter7", "imagefilter7", mi(ImageFilter7)},
	{"Image Filter 8", "ImageFilter8", "imagefilter8", mi(ImageFilter8)},
	{"Image Filter 9", "ImageFilter9", "imagefilter9", mi(ImageFilter9)},
	{"Image Filter 9 Plus", "ImageFilter9Plus", "imagefilter9plus", mi(ImageFilter9Plus)},
	{"Image Filter B And W", "ImageFilterBAndW", "imagefilterbandw", mi(ImageFilterBAndW)},
	{"Image Filter Center Focus", "ImageFilterCenterFocus", "imagefiltercenterfocus", mi(ImageFilterCenterFocus)},
	{"Image Filter Drama", "ImageFilterDrama", "imagefilterdrama", mi(ImageFilterDrama)},
	{"Image Filter Frames", "ImageFilterFrames", "imagefilterframes", mi(ImageFilterFrames)},
	{"Image Filter HDR", "ImageFilterHDR", "imagefilterhdr", mi(ImageFilterHDR)},
	{"Image Filter None", "ImageFilterNone", "imagefilternone", mi(ImageFilterNone)},
	{"Image Filter Tilt Shift", "ImageFilterTiltShift", "imagefiltertiltshift", mi(ImageFilterTiltShift)},
	{"Image Filter Vintage", "ImageFilterVintage", "imagefiltervintage", mi(ImageFilterVintage)},
	{"Image Flare", "ImageFlare", "imageflare", mi(ImageFlare)},
	{"Image Flash Auto", "ImageFlashAuto", "imageflashauto", mi(ImageFlashAuto)},
	{"Image Flash Off", "ImageFlashOff", "imageflashoff", mi(ImageFlashOff)},
	{"Image Flash On", "ImageFlashOn", "imageflashon", mi(ImageFlashOn)},
	{"Image Flip", "ImageFlip", "imageflip", mi(ImageFlip)},
	{"Image Gradient", "ImageGradient", "imagegradient", mi(ImageGradient)},
	{"Image Grain", "ImageGrain", "imagegrain", mi(ImageGrain)},
	{"Image Grid Off", "ImageGridOff", "imagegridoff", mi(ImageGridOff)},
	{"Image Grid On", "ImageGridOn", "imagegridon", mi(ImageGridOn)},
	{"Image HDR Off", "ImageHDROff", "imagehdroff", mi(ImageHDROff)},
	{"Image HDR On", "ImageHDROn", "imagehdron", mi(ImageHDROn)},
	{"Image HDR Strong", "ImageHDRStrong", "imagehdrstrong", mi(ImageHDRStrong)},
	{"Image HDR Weak", "ImageHDRWeak", "imagehdrweak", mi(ImageHDRWeak)},
	{"Image Healing", "ImageHealing", "imagehealing", mi(ImageHealing)},
	{"Image ISO", "ImageISO", "imageiso", mi(ImageISO)},
	{"Image Image", "ImageImage", "imageimage", mi(ImageImage)},
	{"Image Image Aspect Ratio", "ImageImageAspectRatio", "imageimageaspectratio", mi(ImageImageAspectRatio)},
	{"Image Landscape", "ImageLandscape", "imagelandscape", mi(ImageLandscape)},
	{"Image Leak Add", "ImageLeakAdd", "imageleakadd", mi(ImageLeakAdd)},
	{"Image Leak Remove", "ImageLeakRemove", "imageleakremove", mi(ImageLeakRemove)},
	{"Image Lens", "ImageLens", "imagelens", mi(ImageLens)},
	{"Image Linked Camera", "ImageLinkedCamera", "imagelinkedcamera", mi(ImageLinkedCamera)},
	{"Image Looks", "ImageLooks", "imagelooks", mi(ImageLooks)},
	{"Image Looks 3", "ImageLooks3", "imagelooks3", mi(ImageLooks3)},
	{"Image Looks 4", "ImageLooks4", "imagelooks4", mi(ImageLooks4)},
	{"Image Looks 5", "ImageLooks5", "imagelooks5", mi(ImageLooks5)},
	{"Image Looks 6", "ImageLooks6", "imagelooks6", mi(ImageLooks6)},
	{"Image Looks One", "ImageLooksOne", "imagelooksone", mi(ImageLooksOne)},
	{"Image Looks Two", "ImageLooksTwo", "imagelookstwo", mi(ImageLooksTwo)},
	{"Image Loupe", "ImageLoupe", "imageloupe", mi(ImageLoupe)},
	{"Image Monochrome Photos", "ImageMonochromePhotos", "imagemonochromephotos", mi(ImageMonochromePhotos)},
	{"Image Movie Creation", "ImageMovieCreation", "imagemoviecreation", mi(ImageMovieCreation)},
	{"Image Movie Filter", "ImageMovieFilter", "imagemoviefilter", mi(ImageMovieFilter)},
	{"Image Music Note", "ImageMusicNote", "imagemusicnote", mi(ImageMusicNote)},
	{"Image Nature", "ImageNature", "imagenature", mi(ImageNature)},
	{"Image Nature People", "ImageNaturePeople", "imagenaturepeople", mi(ImageNaturePeople)},
	{"Image Navigate Before", "ImageNavigateBefore", "imagenavigatebefore", mi(ImageNavigateBefore)},
	{"Image Navigate Next", "ImageNavigateNext", "imagenavigatenext", mi(ImageNavigateNext)},
	{"Image Palette", "ImagePalette", "imagepalette", mi(ImagePalette)},
	{"Image Panorama", "ImagePanorama", "imagepanorama", mi(ImagePanorama)},
	{"Image Panorama Fish Eye", "ImagePanoramaFishEye", "imagepanoramafisheye", mi(ImagePanoramaFishEye)},
	{"Image Panorama Horizontal", "ImagePanoramaHorizontal", "imagepanoramahorizontal", mi(ImagePanoramaHorizontal)},
	{"Image Panorama Vertical", "ImagePanoramaVertical", "imagepanoramavertical", mi(ImagePanoramaVertical)},
	{"Image Panorama Wide Angle", "ImagePanoramaWideAngle", "imagepanoramawideangle", mi(ImagePanoramaWideAngle)},
	{"Image Photo", "ImagePhoto", "imagephoto", mi(ImagePhoto)},
	{"Image Photo Album", "ImagePhotoAlbum", "imagephotoalbum", mi(ImagePhotoAlbum)},
	{"Image Photo Camera", "ImagePhotoCamera", "imagephotocamera", mi(ImagePhotoCamera)},
	{"Image Photo Filter", "ImagePhotoFilter", "imagephotofilter", mi(ImagePhotoFilter)},
	{"Image Photo Library", "ImagePhotoLibrary", "imagephotolibrary", mi(ImagePhotoLibrary)},
	{"Image Photo Size Select Actual", "ImagePhotoSizeSelectActual", "imagephotosizeselectactual", mi(ImagePhotoSizeSelectActual)},
	{"Image Photo Size Select Large", "ImagePhotoSizeSelectLarge", "imagephotosizeselectlarge", mi(ImagePhotoSizeSelectLarge)},
	{"Image Photo Size Select Small", "ImagePhotoSizeSelectSmall", "imagephotosizeselectsmall", mi(ImagePhotoSizeSelectSmall)},
	{"Image Picture As PDF", "ImagePictureAsPDF", "imagepictureaspdf", mi(ImagePictureAsPDF)},
	{"Image Portrait", "ImagePortrait", "imageportrait", mi(ImagePortrait)},
	{"Image Remove Red Eye", "ImageRemoveRedEye", "imageremoveredeye", mi(ImageRemoveRedEye)},
	{"Image Rotate 90 Degrees CCW", "ImageRotate90DegreesCCW", "imagerotate90degreesccw", mi(ImageRotate90DegreesCCW)},
	{"Image Rotate Left", "ImageRotateLeft", "imagerotateleft", mi(ImageRotateLeft)},
	{"Image Rotate Right", "ImageRotateRight", "imagerotateright", mi(ImageRotateRight)},
	{"Image Slideshow", "ImageSlideshow", "imageslideshow", mi(ImageSlideshow)},
	{"Image Straighten", "ImageStraighten", "imagestraighten", mi(ImageStraighten)},
	{"Image Style", "ImageStyle", "imagestyle", mi(ImageStyle)},
	{"Image Switch Camera", "ImageSwitchCamera", "imageswitchcamera", mi(ImageSwitchCamera)},
	{"Image Switch Video", "ImageSwitchVideo", "imageswitchvideo", mi(ImageSwitchVideo)},
	{"Image Tag Faces", "ImageTagFaces", "imagetagfaces", mi(ImageTagFaces)},
	{"Image Texture", "ImageTexture", "imagetexture", mi(ImageTexture)},
	{"Image Time Lapse", "ImageTimeLapse", "imagetimelapse", mi(ImageTimeLapse)},
	{"Image Timer", "ImageTimer", "imagetimer", mi(ImageTimer)},
	{"Image Timer 10", "ImageTimer10", "imagetimer10", mi(ImageTimer10)},
	{"Image Timer 3", "ImageTimer3", "imagetimer3", mi(ImageTimer3)},
	{"Image Timer Off", "ImageTimerOff", "imagetimeroff", mi(ImageTimerOff)},
	{"Image Tonality", "ImageTonality", "imagetonality", mi(ImageTonality)},
	{"Image Transform", "ImageTransform", "imagetransform", mi(ImageTransform)},
	{"Image Tune", "ImageTune", "imagetune", mi(ImageTune)},
	{"Image View Comfy", "ImageViewComfy", "imageviewcomfy", mi(ImageViewComfy)},
	{"Image View Compact", "ImageViewCompact", "imageviewcompact", mi(ImageViewCompact)},
	{"Image Vignette", "ImageVignette", "imagevignette", mi(ImageVignette)},
	{"Image WB Auto", "ImageWBAuto", "imagewbauto", mi(ImageWBAuto)},
	{"Image WB Cloudy", "ImageWBCloudy", "imagewbcloudy", mi(ImageWBCloudy)},
	{"Image WB Incandescent", "ImageWBIncandescent", "imagewbincandescent", mi(ImageWBIncandescent)},
	{"Image WB Iridescent", "ImageWBIridescent", "imagewbiridescent", mi(ImageWBIridescent)},
	{"Image WB Sunny", "ImageWBSunny", "imagewbsunny", mi(ImageWBSunny)},
	{"Maps Add Location", "MapsAddLocation", "mapsaddlocation", mi(MapsAddLocation)},
	{"Maps Beenhere", "MapsBeenhere", "mapsbeenhere", mi(MapsBeenhere)},
	{"Maps Directions", "MapsDirections", "mapsdirections", mi(MapsDirections)},
	{"Maps Directions Bike", "MapsDirectionsBike", "mapsdirectionsbike", mi(MapsDirectionsBike)},
	{"Maps Directions Boat", "MapsDirectionsBoat", "mapsdirectionsboat", mi(MapsDirectionsBoat)},
	{"Maps Directions Bus", "MapsDirectionsBus", "mapsdirectionsbus", mi(MapsDirectionsBus)},
	{"Maps Directions Car", "MapsDirectionsCar", "mapsdirectionscar", mi(MapsDirectionsCar)},
	{"Maps Directions Railway", "MapsDirectionsRailway", "mapsdirectionsrailway", mi(MapsDirectionsRailway)},
	{"Maps Directions Run", "MapsDirectionsRun", "mapsdirectionsrun", mi(MapsDirectionsRun)},
	{"Maps Directions Subway", "MapsDirectionsSubway", "mapsdirectionssubway", mi(MapsDirectionsSubway)},
	{"Maps Directions Transit", "MapsDirectionsTransit", "mapsdirectionstransit", mi(MapsDirectionsTransit)},
	{"Maps Directions Walk", "MapsDirectionsWalk", "mapsdirectionswalk", mi(MapsDirectionsWalk)},
	{"Maps EV Station", "MapsEVStation", "mapsevstation", mi(MapsEVStation)},
	{"Maps Edit Location", "MapsEditLocation", "mapseditlocation", mi(MapsEditLocation)},
	{"Maps Flight", "MapsFlight", "mapsflight", mi(MapsFlight)},
	{"Maps Hotel", "MapsHotel", "mapshotel", mi(MapsHotel)},
	{"Maps Layers", "MapsLayers", "mapslayers", mi(MapsLayers)},
	{"Maps Layers Clear", "MapsLayersClear", "mapslayersclear", mi(MapsLayersClear)},
	{"Maps Local ATM", "MapsLocalATM", "mapslocalatm", mi(MapsLocalATM)},
	{"Maps Local Activity", "MapsLocalActivity", "mapslocalactivity", mi(MapsLocalActivity)},
	{"Maps Local Airport", "MapsLocalAirport", "mapslocalairport", mi(MapsLocalAirport)},
	{"Maps Local Bar", "MapsLocalBar", "mapslocalbar", mi(MapsLocalBar)},
	{"Maps Local Cafe", "MapsLocalCafe", "mapslocalcafe", mi(MapsLocalCafe)},
	{"Maps Local Car Wash", "MapsLocalCarWash", "mapslocalcarwash", mi(MapsLocalCarWash)},
	{"Maps Local Convenience Store", "MapsLocalConvenienceStore", "mapslocalconveniencestore", mi(MapsLocalConvenienceStore)},
	{"Maps Local Dining", "MapsLocalDining", "mapslocaldining", mi(MapsLocalDining)},
	{"Maps Local Drink", "MapsLocalDrink", "mapslocaldrink", mi(MapsLocalDrink)},
	{"Maps Local Florist", "MapsLocalFlorist", "mapslocalflorist", mi(MapsLocalFlorist)},
	{"Maps Local Gas Station", "MapsLocalGasStation", "mapslocalgasstation", mi(MapsLocalGasStation)},
	{"Maps Local Grocery Store", "MapsLocalGroceryStore", "mapslocalgrocerystore", mi(MapsLocalGroceryStore)},
	{"Maps Local Hospital", "MapsLocalHospital", "mapslocalhospital", mi(MapsLocalHospital)},
	{"Maps Local Hotel", "MapsLocalHotel", "mapslocalhotel", mi(MapsLocalHotel)},
	{"Maps Local Laundry Service", "MapsLocalLaundryService", "mapslocallaundryservice", mi(MapsLocalLaundryService)},
	{"Maps Local Library", "MapsLocalLibrary", "mapslocallibrary", mi(MapsLocalLibrary)},
	{"Maps Local Mall", "MapsLocalMall", "mapslocalmall", mi(MapsLocalMall)},
	{"Maps Local Movies", "MapsLocalMovies", "mapslocalmovies", mi(MapsLocalMovies)},
	{"Maps Local Offer", "MapsLocalOffer", "mapslocaloffer", mi(MapsLocalOffer)},
	{"Maps Local Parking", "MapsLocalParking", "mapslocalparking", mi(MapsLocalParking)},
	{"Maps Local Pharmacy", "MapsLocalPharmacy", "mapslocalpharmacy", mi(MapsLocalPharmacy)},
	{"Maps Local Phone", "MapsLocalPhone", "mapslocalphone", mi(MapsLocalPhone)},
	{"Maps Local Pizza", "MapsLocalPizza", "mapslocalpizza", mi(MapsLocalPizza)},
	{"Maps Local Play", "MapsLocalPlay", "mapslocalplay", mi(MapsLocalPlay)},
	{"Maps Local Post Office", "MapsLocalPostOffice", "mapslocalpostoffice", mi(MapsLocalPostOffice)},
	{"Maps Local Printshop", "MapsLocalPrintshop", "mapslocalprintshop", mi(MapsLocalPrintshop)},
	{"Maps Local See", "MapsLocalSee", "mapslocalsee", mi(MapsLocalSee)},
	{"Maps Local Shipping", "MapsLocalShipping", "mapslocalshipping", mi(MapsLocalShipping)},
	{"Maps Local Taxi", "MapsLocalTaxi", "mapslocaltaxi", mi(MapsLocalTaxi)},
	{"Maps Map", "MapsMap", "mapsmap", mi(MapsMap)},
	{"Maps My Location", "MapsMyLocation", "mapsmylocation", mi(MapsMyLocation)},
	{"Maps Navigation", "MapsNavigation", "mapsnavigation", mi(MapsNavigation)},
	{"Maps Near Me", "MapsNearMe", "mapsnearme", mi(MapsNearMe)},
	{"Maps Person Pin", "MapsPersonPin", "mapspersonpin", mi(MapsPersonPin)},
	{"Maps Person Pin Circle", "MapsPersonPinCircle", "mapspersonpincircle", mi(MapsPersonPinCircle)},
	{"Maps Pin Drop", "MapsPinDrop", "mapspindrop", mi(MapsPinDrop)},
	{"Maps Place", "MapsPlace", "mapsplace", mi(MapsPlace)},
	{"Maps Rate Review", "MapsRateReview", "mapsratereview", mi(MapsRateReview)},
	{"Maps Restaurant", "MapsRestaurant", "mapsrestaurant", mi(MapsRestaurant)},
	{"Maps Restaurant Menu", "MapsRestaurantMenu", "mapsrestaurantmenu", mi(MapsRestaurantMenu)},
	{"Maps Satellite", "MapsSatellite", "mapssatellite", mi(MapsSatellite)},
	{"Maps Store Mall Directory", "MapsStoreMallDirectory", "mapsstoremalldirectory", mi(MapsStoreMallDirectory)},
	{"Maps Street View", "MapsStreetView", "mapsstreetview", mi(MapsStreetView)},
	{"Maps Subway", "MapsSubway", "mapssubway", mi(MapsSubway)},
	{"Maps Terrain", "MapsTerrain", "mapsterrain", mi(MapsTerrain)},
	{"Maps Traffic", "MapsTraffic", "mapstraffic", mi(MapsTraffic)},
	{"Maps Train", "MapsTrain", "mapstrain", mi(MapsTrain)},
	{"Maps Tram", "MapsTram", "mapstram", mi(MapsTram)},
	{"Maps Transfer Within A Station", "MapsTransferWithinAStation", "mapstransferwithinastation", mi(MapsTransferWithinAStation)},
	{"Maps Zoom Out Map", "MapsZoomOutMap", "mapszoomoutmap", mi(MapsZoomOutMap)},
	{"Navigation Apps", "NavigationApps", "navigationapps", mi(NavigationApps)},
	{"Navigation Arrow Back", "NavigationArrowBack", "navigationarrowback", mi(NavigationArrowBack)},
	{"Navigation Arrow Downward", "NavigationArrowDownward", "navigationarrowdownward", mi(NavigationArrowDownward)},
	{"Navigation Arrow Drop Down", "NavigationArrowDropDown", "navigationarrowdropdown", mi(NavigationArrowDropDown)},
	{"Navigation Arrow Drop Down Circle", "NavigationArrowDropDownCircle", "navigationarrowdropdowncircle", mi(NavigationArrowDropDownCircle)},
	{"Navigation Arrow Drop Up", "NavigationArrowDropUp", "navigationarrowdropup", mi(NavigationArrowDropUp)},
	{"Navigation Arrow Forward", "NavigationArrowForward", "navigationarrowforward", mi(NavigationArrowForward)},
	{"Navigation Arrow Upward", "NavigationArrowUpward", "navigationarrowupward", mi(NavigationArrowUpward)},
	{"Navigation Cancel", "NavigationCancel", "navigationcancel", mi(NavigationCancel)},
	{"Navigation Check", "NavigationCheck", "navigationcheck", mi(NavigationCheck)},
	{"Navigation Chevron Left", "NavigationChevronLeft", "navigationchevronleft", mi(NavigationChevronLeft)},
	{"Navigation Chevron Right", "NavigationChevronRight", "navigationchevronright", mi(NavigationChevronRight)},
	{"Navigation Close", "NavigationClose", "navigationclose", mi(NavigationClose)},
	{"Navigation Expand Less", "NavigationExpandLess", "navigationexpandless", mi(NavigationExpandLess)},
	{"Navigation Expand More", "NavigationExpandMore", "navigationexpandmore", mi(NavigationExpandMore)},
	{"Navigation First Page", "NavigationFirstPage", "navigationfirstpage", mi(NavigationFirstPage)},
	{"Navigation Fullscreen", "NavigationFullscreen", "navigationfullscreen", mi(NavigationFullscreen)},
	{"Navigation Fullscreen Exit", "NavigationFullscreenExit", "navigationfullscreenexit", mi(NavigationFullscreenExit)},
	{"Navigation Last Page", "NavigationLastPage", "navigationlastpage", mi(NavigationLastPage)},
	{"Navigation Menu", "NavigationMenu", "navigationmenu", mi(NavigationMenu)},
	{"Navigation More Horiz", "NavigationMoreHoriz", "navigationmorehoriz", mi(NavigationMoreHoriz)},
	{"Navigation More Vert", "NavigationMoreVert", "navigationmorevert", mi(NavigationMoreVert)},
	{"Navigation Refresh", "NavigationRefresh", "navigationrefresh", mi(NavigationRefresh)},
	{"Navigation Subdirectory Arrow Left", "NavigationSubdirectoryArrowLeft", "navigationsubdirectoryarrowleft", mi(NavigationSubdirectoryArrowLeft)},
	{"Navigation Subdirectory Arrow Right", "NavigationSubdirectoryArrowRight", "navigationsubdirectoryarrowright", mi(NavigationSubdirectoryArrowRight)},
	{"Navigation Unfold Less", "NavigationUnfoldLess", "navigationunfoldless", mi(NavigationUnfoldLess)},
	{"Navigation Unfold More", "NavigationUnfoldMore", "navigationunfoldmore", mi(NavigationUnfoldMore)},
	{"Notification ADB", "NotificationADB", "notificationadb", mi(NotificationADB)},
	{"Notification Airline Seat Flat", "NotificationAirlineSeatFlat", "notificationairlineseatflat", mi(NotificationAirlineSeatFlat)},
	{"Notification Airline Seat Flat Angled", "NotificationAirlineSeatFlatAngled", "notificationairlineseatflatangled", mi(NotificationAirlineSeatFlatAngled)},
	{"Notification Airline Seat Individual Suite", "NotificationAirlineSeatIndividualSuite", "notificationairlineseatindividualsuite", mi(NotificationAirlineSeatIndividualSuite)},
	{"Notification Airline Seat Legroom Extra", "NotificationAirlineSeatLegroomExtra", "notificationairlineseatlegroomextra", mi(NotificationAirlineSeatLegroomExtra)},
	{"Notification Airline Seat Legroom Normal", "NotificationAirlineSeatLegroomNormal", "notificationairlineseatlegroomnormal", mi(NotificationAirlineSeatLegroomNormal)},
	{"Notification Airline Seat Legroom Reduced", "NotificationAirlineSeatLegroomReduced", "notificationairlineseatlegroomreduced", mi(NotificationAirlineSeatLegroomReduced)},
	{"Notification Airline Seat Recline Extra", "NotificationAirlineSeatReclineExtra", "notificationairlineseatreclineextra", mi(NotificationAirlineSeatReclineExtra)},
	{"Notification Airline Seat Recline Normal", "NotificationAirlineSeatReclineNormal", "notificationairlineseatreclinenormal", mi(NotificationAirlineSeatReclineNormal)},
	{"Notification Bluetooth Audio", "NotificationBluetoothAudio", "notificationbluetoothaudio", mi(NotificationBluetoothAudio)},
	{"Notification Confirmation Number", "NotificationConfirmationNumber", "notificationconfirmationnumber", mi(NotificationConfirmationNumber)},
	{"Notification Disc Full", "NotificationDiscFull", "notificationdiscfull", mi(NotificationDiscFull)},
	{"Notification Do Not Disturb", "NotificationDoNotDisturb", "notificationdonotdisturb", mi(NotificationDoNotDisturb)},
	{"Notification Do Not Disturb Alt", "NotificationDoNotDisturbAlt", "notificationdonotdisturbalt", mi(NotificationDoNotDisturbAlt)},
	{"Notification Do Not Disturb Off", "NotificationDoNotDisturbOff", "notificationdonotdisturboff", mi(NotificationDoNotDisturbOff)},
	{"Notification Do Not Disturb On", "NotificationDoNotDisturbOn", "notificationdonotdisturbon", mi(NotificationDoNotDisturbOn)},
	{"Notification Drive ETA", "NotificationDriveETA", "notificationdriveeta", mi(NotificationDriveETA)},
	{"Notification Enhanced Encryption", "NotificationEnhancedEncryption", "notificationenhancedencryption", mi(NotificationEnhancedEncryption)},
	{"Notification Event Available", "NotificationEventAvailable", "notificationeventavailable", mi(NotificationEventAvailable)},
	{"Notification Event Busy", "NotificationEventBusy", "notificationeventbusy", mi(NotificationEventBusy)},
	{"Notification Event Note", "NotificationEventNote", "notificationeventnote", mi(NotificationEventNote)},
	{"Notification Folder Special", "NotificationFolderSpecial", "notificationfolderspecial", mi(NotificationFolderSpecial)},
	{"Notification Live TV", "NotificationLiveTV", "notificationlivetv", mi(NotificationLiveTV)},
	{"Notification MMS", "NotificationMMS", "notificationmms", mi(NotificationMMS)},
	{"Notification More", "NotificationMore", "notificationmore", mi(NotificationMore)},
	{"Notification Network Check", "NotificationNetworkCheck", "notificationnetworkcheck", mi(NotificationNetworkCheck)},
	{"Notification Network Locked", "NotificationNetworkLocked", "notificationnetworklocked", mi(NotificationNetworkLocked)},
	{"Notification No Encryption", "NotificationNoEncryption", "notificationnoencryption", mi(NotificationNoEncryption)},
	{"Notification On Demand Video", "NotificationOnDemandVideo", "notificationondemandvideo", mi(NotificationOnDemandVideo)},
	{"Notification Personal Video", "NotificationPersonalVideo", "notificationpersonalvideo", mi(NotificationPersonalVideo)},
	{"Notification Phone Bluetooth Speaker", "NotificationPhoneBluetoothSpeaker", "notificationphonebluetoothspeaker", mi(NotificationPhoneBluetoothSpeaker)},
	{"Notification Phone Forwarded", "NotificationPhoneForwarded", "notificationphoneforwarded", mi(NotificationPhoneForwarded)},
	{"Notification Phone In Talk", "NotificationPhoneInTalk", "notificationphoneintalk", mi(NotificationPhoneInTalk)},
	{"Notification Phone Locked", "NotificationPhoneLocked", "notificationphonelocked", mi(NotificationPhoneLocked)},
	{"Notification Phone Missed", "NotificationPhoneMissed", "notificationphonemissed", mi(NotificationPhoneMissed)},
	{"Notification Phone Paused", "NotificationPhonePaused", "notificationphonepaused", mi(NotificationPhonePaused)},
	{"Notification Power", "NotificationPower", "notificationpower", mi(NotificationPower)},
	{"Notification Priority High", "NotificationPriorityHigh", "notificationpriorityhigh", mi(NotificationPriorityHigh)},
	{"Notification RV Hookup", "NotificationRVHookup", "notificationrvhookup", mi(NotificationRVHookup)},
	{"Notification SD Card", "NotificationSDCard", "notificationsdcard", mi(NotificationSDCard)},
	{"Notification SIM Card Alert", "NotificationSIMCardAlert", "notificationsimcardalert", mi(NotificationSIMCardAlert)},
	{"Notification SMS", "NotificationSMS", "notificationsms", mi(NotificationSMS)},
	{"Notification SMS Failed", "NotificationSMSFailed", "notificationsmsfailed", mi(NotificationSMSFailed)},
	{"Notification Sync", "NotificationSync", "notificationsync", mi(NotificationSync)},
	{"Notification Sync Disabled", "NotificationSyncDisabled", "notificationsyncdisabled", mi(NotificationSyncDisabled)},
	{"Notification Sync Problem", "NotificationSyncProblem", "notificationsyncproblem", mi(NotificationSyncProblem)},
	{"Notification System Update", "NotificationSystemUpdate", "notificationsystemupdate", mi(NotificationSystemUpdate)},
	{"Notification Tap And Play", "NotificationTapAndPlay", "notificationtapandplay", mi(NotificationTapAndPlay)},
	{"Notification Time To Leave", "NotificationTimeToLeave", "notificationtimetoleave", mi(NotificationTimeToLeave)},
	{"Notification VPN Lock", "NotificationVPNLock", "notificationvpnlock", mi(NotificationVPNLock)},
	{"Notification Vibration", "NotificationVibration", "notificationvibration", mi(NotificationVibration)},
	{"Notification Voice Chat", "NotificationVoiceChat", "notificationvoicechat", mi(NotificationVoiceChat)},
	{"Notification WC", "NotificationWC", "notificationwc", mi(NotificationWC)},
	{"Notification Wi Fi", "NotificationWiFi", "notificationwifi", mi(NotificationWiFi)},
	{"Places AC Unit", "PlacesACUnit", "placesacunit", mi(PlacesACUnit)},
	{"Places Airport Shuttle", "PlacesAirportShuttle", "placesairportshuttle", mi(PlacesAirportShuttle)},
	{"Places All Inclusive", "PlacesAllInclusive", "placesallinclusive", mi(PlacesAllInclusive)},
	{"Places Beach Access", "PlacesBeachAccess", "placesbeachaccess", mi(PlacesBeachAccess)},
	{"Places Business Center", "PlacesBusinessCenter", "placesbusinesscenter", mi(PlacesBusinessCenter)},
	{"Places Casino", "PlacesCasino", "placescasino", mi(PlacesCasino)},
	{"Places Child Care", "PlacesChildCare", "placeschildcare", mi(PlacesChildCare)},
	{"Places Child Friendly", "PlacesChildFriendly", "placeschildfriendly", mi(PlacesChildFriendly)},
	{"Places Fitness Center", "PlacesFitnessCenter", "placesfitnesscenter", mi(PlacesFitnessCenter)},
	{"Places Free Breakfast", "PlacesFreeBreakfast", "placesfreebreakfast", mi(PlacesFreeBreakfast)},
	{"Places Golf Course", "PlacesGolfCourse", "placesgolfcourse", mi(PlacesGolfCourse)},
	{"Places Hot Tub", "PlacesHotTub", "placeshottub", mi(PlacesHotTub)},
	{"Places Kitchen", "PlacesKitchen", "placeskitchen", mi(PlacesKitchen)},
	{"Places Pool", "PlacesPool", "placespool", mi(PlacesPool)},
	{"Places RV Hookup", "PlacesRVHookup", "placesrvhookup", mi(PlacesRVHookup)},
	{"Places Room Service", "PlacesRoomService", "placesroomservice", mi(PlacesRoomService)},
	{"Places Smoke Free", "PlacesSmokeFree", "placessmokefree", mi(PlacesSmokeFree)},
	{"Places Smoking Rooms", "PlacesSmokingRooms", "placessmokingrooms", mi(PlacesSmokingRooms)},
	{"Places Spa", "PlacesSpa", "placesspa", mi(PlacesSpa)},
	{"Social Cake", "SocialCake", "socialcake", mi(SocialCake)},
	{"Social Domain", "SocialDomain", "socialdomain", mi(SocialDomain)},
	{"Social Group", "SocialGroup", "socialgroup", mi(SocialGroup)},
	{"Social Group Add", "SocialGroupAdd", "socialgroupadd", mi(SocialGroupAdd)},
	{"Social Location City", "SocialLocationCity", "sociallocationcity", mi(SocialLocationCity)},
	{"Social Mood", "SocialMood", "socialmood", mi(SocialMood)},
	{"Social Mood Bad", "SocialMoodBad", "socialmoodbad", mi(SocialMoodBad)},
	{"Social Notifications", "SocialNotifications", "socialnotifications", mi(SocialNotifications)},
	{"Social Notifications Active", "SocialNotificationsActive", "socialnotificationsactive", mi(SocialNotificationsActive)},
	{"Social Notifications None", "SocialNotificationsNone", "socialnotificationsnone", mi(SocialNotificationsNone)},
	{"Social Notifications Off", "SocialNotificationsOff", "socialnotificationsoff", mi(SocialNotificationsOff)},
	{"Social Notifications Paused", "SocialNotificationsPaused", "socialnotificationspaused", mi(SocialNotificationsPaused)},
	{"Social Pages", "SocialPages", "socialpages", mi(SocialPages)},
	{"Social Party Mode", "SocialPartyMode", "socialpartymode", mi(SocialPartyMode)},
	{"Social People", "SocialPeople", "socialpeople", mi(SocialPeople)},
	{"Social People Outline", "SocialPeopleOutline", "socialpeopleoutline", mi(SocialPeopleOutline)},
	{"Social Person", "SocialPerson", "socialperson", mi(SocialPerson)},
	{"Social Person Add", "SocialPersonAdd", "socialpersonadd", mi(SocialPersonAdd)},
	{"Social Person Outline", "SocialPersonOutline", "socialpersonoutline", mi(SocialPersonOutline)},
	{"Social Plus One", "SocialPlusOne", "socialplusone", mi(SocialPlusOne)},
	{"Social Poll", "SocialPoll", "socialpoll", mi(SocialPoll)},
	{"Social Public", "SocialPublic", "socialpublic", mi(SocialPublic)},
	{"Social School", "SocialSchool", "socialschool", mi(SocialSchool)},
	{"Social Sentiment Dissatisfied", "SocialSentimentDissatisfied", "socialsentimentdissatisfied", mi(SocialSentimentDissatisfied)},
	{"Social Sentiment Neutral", "SocialSentimentNeutral", "socialsentimentneutral", mi(SocialSentimentNeutral)},
	{"Social Sentiment Satisfied", "SocialSentimentSatisfied", "socialsentimentsatisfied", mi(SocialSentimentSatisfied)},
	{"Social Sentiment Very Dissatisfied", "SocialSentimentVeryDissatisfied", "socialsentimentverydissatisfied", mi(SocialSentimentVeryDissatisfied)},
	{"Social Sentiment Very Satisfied", "SocialSentimentVerySatisfied", "socialsentimentverysatisfied", mi(SocialSentimentVerySatisfied)},
	{"Social Share", "SocialShare", "socialshare", mi(SocialShare)},
	{"Social Whats Hot", "SocialWhatsHot", "socialwhatshot", mi(SocialWhatsHot)},
	{"Toggle Check Box", "ToggleCheckBox", "togglecheckbox", mi(ToggleCheckBox)},
	{"Toggle Check Box Outline Blank", "ToggleCheckBoxOutlineBlank", "togglecheckboxoutlineblank", mi(ToggleCheckBoxOutlineBlank)},
	{"Toggle Indeterminate Check Box", "ToggleIndeterminateCheckBox", "toggleindeterminatecheckbox", mi(ToggleIndeterminateCheckBox)},
	{"Toggle Radio Button Checked", "ToggleRadioButtonChecked", "toggleradiobuttonchecked", mi(ToggleRadioButtonChecked)},
	{"Toggle Radio Button Unchecked", "ToggleRadioButtonUnchecked", "toggleradiobuttonunchecked", mi(ToggleRadioButtonUnchecked)},
	{"Toggle Star", "ToggleStar", "togglestar", mi(ToggleStar)},
	{"Toggle Star Border", "ToggleStarBorder", "togglestarborder", mi(ToggleStarBorder)},
	{"Toggle Star Half", "ToggleStarHalf", "togglestarhalf", mi(ToggleStarHalf)},
}
