# https://taskfile.dev

version: '3'

tasks:
  default:
    - task: fmt
    - go build -ldflags="-s -w"
    - task: lint

  nowayland:
    - task: fmt
    - go build -ldflags="-s -w" -tags nowayland
    - task: lint

  wasm:
    - gogio -target js -ldflags="-s -w" -o wasm_assets github.com/steverusso/gio-icon-browser

  fmt:
    - goimports -w -l .
    - gofumpt -w -l .

  lint:
    - go vet ./...
